### ISSUE TITLE
Where have the releases gone?

### ISSUE THREAD

**Issue by aubergine10** [krzychu124/Cities-Skylines-Traffic-Manager-President-Edition#107]
I'm sure that for 1.10.15 there was a release made in the git repo, but it's not showing;

https://github.com/krzychu124/Cities-Skylines-Traffic-Manager-President-Edition/releases

**Comment by krzychu124** [comment]
I didn't added that ;)

**Comment by krzychu124** [comment]
I've added missing releases including current

**Comment by aubergine10** [comment]
LGTM!
