### ISSUE TITLE
Error: Could not load type: TrafficManager.Manager.Impl.VehicleBehaviorManager

### ISSUE THREAD

**Issue by aubergine10** [krzychu124/Cities-Skylines-Traffic-Manager-President-Edition#113]
I've asked for log file to get full stack trace

![ef7e127749296893b01eb265bff0cd8f](https://user-images.githubusercontent.com/1386719/53349147-59c93b00-3914-11e9-8c4b-a34513e904ad.png)

@pcfantasy Is it possible this is from one of your mods?

# Temporary Workaround

Disable the  "AdvancedJunctionRule" mod and send the author a copy of your ```AdvancedJunctionRule.txt``` to help with bug fixing.

**Comment by krzychu124** [comment]
Current Steam build version ```1.0.6994.37925```

**Comment by krzychu124** [comment]
BTW it's the same build like in #90  - our previous version (1.10.15)

**Comment by pcfantasy** [comment]
@aubergine10 
Yes, I do require VehicleBehaviorManager.maychangesegment.

You can also let him send  AdvancedJunctionRule.txt if they use this mod for debug.

**Comment by aubergine10** [comment]
@pcfantasy Do you know if this issue would still exist?

**Comment by pcfantasy** [comment]
@aubergine10 

You can close this issue now, I add warning window to detect if someone do not enable TMPE.

**Comment by aubergine10** [comment]
Awesome, thanks!
