### ISSUE TITLE
Migration to Harmony

### ISSUE THREAD

**Issue by krzychu124** [krzychu124/Cities-Skylines-Traffic-Manager-President-Edition#119]
_As we know there are serious problems with overriding our methods by other mods._

__@VictorPhilipp__ did great job with implementation in separate branch. It is more than __5 patches__ behind of our current version (about __140 commits__ :smile: ) but it has some other changes to citizen manager, Flags and other things that looks promissing but not released yet. 
I have to test if everything it in place and _'working'_.

I will try to merge our latest changes and push it to new branch, probably 1.11.0-pre-alpha to give you opportunity to do more tests on different environments, check compatibility with savegames(loading/saving) etc. 

Maybe I'll even add compiled dlls to speed up testing.

**Comment by Strdate** [comment]
It has always been in the old TMPE repo? :)

**Comment by krzychu124** [comment]
Yup

**Comment by VictorPhilipp** [comment]
That's the same branch where I started to implement the emergency evasion feature. I will update the code to the latest version of C:S.

**Comment by pcfantasy** [comment]
@krzychu124  @VictorPhilipp 

Yes, I aslo start to use harmony in my mod, it is a fantastic lib for detour.

But I have a question, harmony is very useful for adding prefix and postfix in vanilla methods. But for some other vanilla methods, we have totally rewrite all the logics, is it better to use old cities-skylines-detour
https://github.com/sschoener/cities-skylines-detour

**Comment by VictorPhilipp** [comment]
Harmony has its limits, I agree.

As you said it's good for prefixes and postfixes but transpiling (=replacing) methods with Harmony gives ton of problems:
- Detouring struct methods seems impossible with Harmony and Harmony cannot handle methods that return structs (https://github.com/pardeike/Harmony/issues/77)
- Calls to base class methods are impossible.
- Annotation driven patching does not work when there are multiple candidate methods that receive struct references as arguments (you would need to put a `typeof(TheStructType).MakeByRefType()` which is not a constant expression).

**Comment by aubergine10** [comment]
I  guess we just port to harmony where possible (as that will reduce conflict points with other mods and lower risk of problems with new game versions) and stick to detouring for the other stuff?

**Comment by Strdate** [comment]
Why do you need method transpiling? If you want to override the method
completely, just use prefix and return false to indicate that the original
method should not be run. Or I didn't get the point.
I don't even know what transpiling is for, besides accessing original IL
code, which you surely don't need in this case.

**Comment by pcfantasy** [comment]
@Strdate 

No, if in your case, we do not need to use harmony. We`d like to use harmony to reduce conflict, that other modders can also do some patch on the same method.

**Comment by VictorPhilipp** [comment]
@Strdate 
Prefix methods cannot set the return value, transpilers can

**Comment by Strdate** [comment]
@VictorPhilipp Are you sure? Just obtain the result pointer with the
`ref object __result`
and you are done. If you don't run the original method the return value should persist. (I didn't test it myself)
