### ISSUE TITLE
(EN) Idea: Different texture for junctions without zebra crossings. Collaboration with Network Skins? (DE) Idee: Andere Textur für Kreuzungen ohne Zebrastreifen. Zusammenarbeit mit NetworkSkins?

### ISSUE THREAD

**Issue by VictorPhilipp** [krzychu124/Cities-Skylines-Traffic-Manager-President-Edition#129]
https://github.com/VictorPhilipp/Cities-Skylines-Traffic-Manager-President-Edition/issues/16

**Comment by VictorPhilipp** [comment]
My original comment (in German)
"Ach hier hast du mich kontaktiert. :-D

Ja, so ein Feature wäre prinzipiell nicht verkehrt. Ich selbst habe mit Texturen noch nicht gearbeitet. Ich kann mir vorstellen, dass es einiges an Arbeit kosten wird, Texturen für sämtliche Straßentypen zu erstellen.

Wenn du abfragen willst, ob Fußgänger an einem Segment/Knoten die Straße überqueren können, kannst du die Methode JunctionRestrictionsManager.Instance().IsPedestrianCrossingAllowed(ushort segmentId, bool startNode) nutzen. segmentId ist die Id des Segments und startNode gibt an, ob du den Fußgängerüberweg am Startknoten (true) oder am Endknoten (false) meinst.

Wie würden die Mods denn miteinander kommunizieren können? Über Reflection oder gibt's da einen eleganteren Weg?"

**Comment by aubergine10** [comment]
![687474703a2f2f692e696d6775722e636f6d2f6f7958456e43752e6a7067](https://user-images.githubusercontent.com/1386719/53698112-4ca6c300-3dd0-11e9-9c02-a73b34b0b9be.jpg)

**Comment by aubergine10** [comment]
This is duplicate of #27 I think, Can it be closed? See also note in #27 that Boformer might have found a way to hide crossing decal per segment.

**Comment by aubergine10** [comment]
closing as duplicate
