### ISSUE TITLE
Automatic timed traffic light step setup

### ISSUE THREAD

**Issue by VictorPhilipp** [krzychu124/Cities-Skylines-Traffic-Manager-President-Edition#131]
The step sequence of a timed traffic light can be created automatically based on the lane arrows that are present at the corresponding junction. The algorithm has first to find compatible traffic light states (green/red) and then build steps that incorporate these.
https://github.com/VictorPhilipp/Cities-Skylines-Traffic-Manager-President-Edition/issues/28

**Comment by aubergine10** [comment]
Duplicate of #5
