### ISSUE TITLE
MPH vs KPH 

### ISSUE THREAD

**Issue by VictorPhilipp** [krzychu124/Cities-Skylines-Traffic-Manager-President-Edition#139]
"Is there an option to use MPH instead of the default KPH, along with the corresponding icons?"

see http://steamcommunity.com/workshop/filedetails/discussion/583429740/142261027571919093/

https://github.com/VictorPhilipp/Cities-Skylines-Traffic-Manager-President-Edition/issues/61

**Comment by VictorPhilipp** [comment]
Adding my vote to this. I recently realised that all my "30" roads are actually 30 KMH which works out at ~19 MPH

No wonder my traffic was going so slow!

**Comment by aubergine10** [comment]
Duplicate of #13
