### ISSUE TITLE
Traffic info view: Toggle between "congestion" and "volume" view

### ISSUE THREAD

**Issue by VictorPhilipp** [krzychu124/Cities-Skylines-Traffic-Manager-President-Edition#142]
shaundoddmusic says: "The other day I was thinking about the traffic view tool in SC4. You could switch between congestion veiw, and volume veiw. It seems that the version in cities is a blend of the two, though it is weighted towards showing congestion. Do you think you could split this into a congestion and a volume tool? The volume tool would better show the effectivness (or pointlessness) of highways for example."

https://github.com/VictorPhilipp/Cities-Skylines-Traffic-Manager-President-Edition/issues/63

moved from https://github.com/VictorPhilipp/Cities-Skylines-Traffic-Manager-President-Edition/issues/67

**Comment by aubergine10** [comment]
We already have some work going on in this respect, see #66 (traffic measurement methods).
