### ISSUE TITLE
New option: Trucks prefer inner lanes

### ISSUE THREAD

**Issue by VictorPhilipp** [krzychu124/Cities-Skylines-Traffic-Manager-President-Edition#146]
@Painful Agenda says: "Can you have option for trucks prefer inner lanes as my left hand lanes are my slow lanes do don't have to ban trucks on right hand lane in uk roads."

https://github.com/VictorPhilipp/Cities-Skylines-Traffic-Manager-President-Edition/issues/80

**Comment by VictorPhilipp** [comment]
This feature is implemented - issue can be closed?

**Comment by aubergine10** [comment]
Feature available via Policies tab in mod options.
