### ISSUE TITLE
Lane-wise default speed limits

### ISSUE THREAD

**Issue by VictorPhilipp** [krzychu124/Cities-Skylines-Traffic-Manager-President-Edition#147]
@Painful Agenda says: "Second in default roads speeds can have the option for lane specific speeds as I spend hours making a highway 50. 60. 70. It apply to all sections like the restrictions"

https://github.com/VictorPhilipp/Cities-Skylines-Traffic-Manager-President-Edition/issues/81

**Comment by VictorPhilipp** [comment]
As this only applies to larger 3+ lane roads (avenues, highways, etc) would it not be better to just have a mod option "inner lanes faster than outer lanes" and do the tweak automagically?

See also: #131

**Comment by aubergine10** [comment]
Duplicate of #84
