### ISSUE TITLE
Esc should exit TMPE tool without showing pause menu

### ISSUE THREAD

**Issue by aubergine10** [krzychu124/Cities-Skylines-Traffic-Manager-President-Edition#16]
Currently, if I press Esc while using a TMPE tool (such as lane connector) it not only exits the tool but also displays the CS pause menu which is constantly irritating.

Full details here: https://github.com/VictorPhilipp/Cities-Skylines-Traffic-Manager-President-Edition/issues/152

**Comment by krzychu124** [comment]
This will be the first new feature I want to add along with some minor fixes I've made yesterday(added missing changes from vanilla game code ). It's super annoying :D

**Comment by krzychu124** [comment]
Finally (I've managed to do it even without refactoring): 559b624c4ddb720ded7488ef7baba189e398e1d5
