### ISSUE TITLE
Cargoload of trains/trucks

### ISSUE THREAD

**Issue by VictorPhilipp** [krzychu124/Cities-Skylines-Traffic-Manager-President-Edition#161]
- Fix that cargo trains drive with around with really low loads of cargo. (1 - 30 %)
- Automatically select appropriate vehicle for load --> a van for a small load, a truck for a large load. (i've made difference in capacity in AVO, sadly i get trucks loaded for 50%, instead of a van, loaded for 100%), while vans would probably mean faster delivery.

https://github.com/VictorPhilipp/Cities-Skylines-Traffic-Manager-President-Edition/issues/123

**Comment by aubergine10** [comment]
Duplicate of #170

**Comment by aubergine10** [comment]
Closing this as duplicate of 170
