### ISSUE TITLE
Speed limit signs window too big

### ISSUE THREAD

**Issue by VictorPhilipp** [krzychu124/Cities-Skylines-Traffic-Manager-President-Edition#162]
I'm running on smaller screen res than usual (1344x756) to boost fps a little, and the window with all the speed signs (when using lane speed tool) is taking up a huge amount of space.

Would it be possible to get an option to reduce the icon size on that window by 50%?

https://github.com/VictorPhilipp/Cities-Skylines-Traffic-Manager-President-Edition/issues/128

**Comment by VictorPhilipp** [comment]
If small UI option is enabled for speeds window, the buttons/checkboxes/etc could be hidden to make it even smaller. (By time a user enables such a mod option, they already know about Shift and Ctrl modifier keys so no need for all that extra stuff in the condensed UI).

See also: #131 - default settings handled via Routes info view panel (so no need for that button on the main speed changer UI).

**Comment by aubergine10** [comment]
This will be made obsolete by transition to build bar menus - see #51 and #84 

Suggest closing this issue as duplicate.
