### ISSUE TITLE
Default lane speeds UI is bit naff

### ISSUE THREAD

**Issue by VictorPhilipp** [krzychu124/Cities-Skylines-Traffic-Manager-President-Edition#163]
### Usability issues:

1. Wading through road variants (raised, bridge, etc) is tedious
2. Some road variants (like slopes, bridge, etc) don't have icons
3. Many workshop roads only show asset id followed by generic road description (eg. 53745683765.Two lane One way) - of which road?!!

If you want to feel my pain, install all the UK Roads ([paved](https://steamcommunity.com/sharedfiles/filedetails/?id=1306733086) and [plain](https://steamcommunity.com/sharedfiles/filedetails/?id=1306951013)) and then have a go at setting default road speeds. Now imagine having roughly twice as many road assets installed (eg. BadPeanut roads, etc) for double the pain.

### Suggestions:

1. Show only ground version of road by default, and setting its speed causes all variants of that road to get same speed  (_maybe have an option could be provided to customise the variants individually to keep the masochists happy?_)
2. If icon for a road variant is missing, use the generic icon for the ground version of that road (but maybe faded or something to distinguish that I'm currently editing a variant?)
3. If possible, show the _name_ of the workshop asset in the UI

Furthermore, where applicable, showing a Steam Workshop icon would be useful so I know if it's vanilla or not. Sometimes road assets are very similar (in name and icon) to vanilla roads, so workshop icon would help disambiguate.

https://github.com/VictorPhilipp/Cities-Skylines-Traffic-Manager-President-Edition/issues/131

**Comment by VictorPhilipp** [comment]
Had an idea how the default speeds UI could be vastly improved....

In the 'routes' info view, player can select a road or rail, etc. Why not add default speed setting to that info view? It works for all networks (even quays - so make sure to disable the speed UI for those).

This way, I can open the info view, select a road (or just click a road name which has same effect), and then set it's default speed (for all variants of that road - slope, tunnel, etc). This would be very simple way to apply a default speed to a specific type of road.

## Basic UI

Hastily thrown-together mockup - this would be appended to the routes info view panel:

> ![region capture 24](https://user-images.githubusercontent.com/1386719/42747257-99812ab0-88d3-11e8-90d1-4eb9c1bffeb9.png)

That would handle >99% of most common 'default speeds' use cases.

Note: As per issue in #181, if the chosen network has multiple network types (eg. road with embedded monorail, tram, or bicycle lanes) then only the primary lane type (road vehicles) would have default speed applied (I don't want my "road with monorail" having it's monorail limited to 30km/h, for example).

## Advanced UI

If user clicks "Advanced settings..." button, they get a much more advanced UI (in it's own window) that let's them set default speed for each individual lane and for each variant (GEBST) of the road.

Another hastily thrown-together mockup:

> ![region capture 25](https://user-images.githubusercontent.com/1386719/42748397-fcd2f018-88d7-11e8-9aca-919223dadbf7.png)

The name of the network being edited is shown at the top so user can confirm they're editing correct network.

If the network is a Steam Workshop asset, a small Steam Workshop icon is shown (I just used a spanner in the mockup) followed by the asset ID. This will be useful for tracking down problematic networks (useful for bug reports).

Then there's the variant (GEBST). It defaults to "Apply to all variants" which would do exactly what you'd expect. However, if user wants to customise individual variants they can select the one they want (eg. to make tunnel slower they'd cycle through the options until they get "Tunnel").

Then there's two synchronise checkboxes:

1. The first will **sync symmetrically**. So if I edit lane 2 (bus lane) the second lane from the other side of the road (lane 6) would get the same value, but only if that lane is the same type as the one being edited (safeguard against mistakes).
2. The second will **sync all lanes of the same type**. So if I edit lane 3 (road vehicles) then any other road vehicle lanes (in the UI mockup above that would be lane 5) would get same speed. This would make life easier when editing some of those huge 12+ lane avenues that are in the workshop.

Finally, each of the lanes are listed, along with type (I have no idea what valid types exist but just guessed at some - eg. maybe "Bus lane" should actually be "Service lane"?) and speed.  The speed would be a text box allowing direct manual entry of a number. The arrows would be used to cycle through the familiar TM:PE speeds. It would be super-cool if, when a common TM:PE speed value is defined, a background image of the red circle with white background could appear - this would give clear indication to user that they've selected one of the widely used speeds.  I don't know what the "default" speed is for lanes (the white circle with black slashes and border) - is that valid in this context? If so, maybe no number (or cycling via arrows all the way to the right or left) could result in default speed?

Note: Where there's arrow buttons to cycle through values, it should 'wrap' to the other end of the list once one end is reached; if I keep clicking "next" button, I'll eventually end up back at the start of the list of available options again.

**Comment by VictorPhilipp** [comment]
Actually, basic view could be even simpler:

> ![region capture 27](https://user-images.githubusercontent.com/1386719/42748958-e9866038-88d9-11e8-85d1-7e54dd8ceed6.png)

Doesn't even need to be captioned, as it's obvious what it relates to.

This way it would indicate the current default speed limit for the network too :) That's useful to see on the routes info view even if I'm not planning to change the speed.

## Advanced customisations exist?

If there are advanced customisations, the simple view would show average speed for most common lane type on the ground variant of the road, and the next/prev buttons would show a warning if used: "There are advanced customisations for this network, are you sure you want to overwrite them? Yes / Cancel"

**Comment by VictorPhilipp** [comment]
In case of tracked lanes (monorail, train, tram), I don't see any need for being able to customise each direction (ie. each track lane):

* If routes info is shown for a track-only network, there's no point displaying advanced button.
* For road networks that contain tracked lanes, collapse adjacent track lanes in to single lane.

**Comment by VictorPhilipp** [comment]
Setting default speed of tracks (monorail, train, tram) could update the speeds of that type of track in all roads that contain the track? The routes view for track networks could get additional "Update roads which contain this track" checkbox.

That way I could, for example, routes view the vanilla monorail, set it's speed with the checkbox enabled, and all my monorail-containing roads get their monorail speed updated.

**Comment by aubergine10** [comment]
There is a major redux version of this feature here: #84 (speeds tool)
