### ISSUE TITLE
Change title of LABS version of the mod

### ISSUE THREAD

**Issue by aubergine10** [krzychu124/Cities-Skylines-Traffic-Manager-President-Edition#164]
To help differentiate which version of the mod a user has active, could we append "LABS" to the mod name for the upcoming `labs` branch?

I've no idea how to make that work consistently, other than perhaps a conditional based on workshop id?

Also, what are we going to do about milestone names in github?

**Comment by Xyrhenix** [comment]
I think perhaps a new versioning system should be adopted as well, to reflect which version of TMPE the experimental/beta version is based from (or to indicate the latest prior stable release).

Currently, TMPE is 1.10.14, while this experimental version is 1.10.16. I'd propose 1.10.14.X or 1.10.14.Xb with the lowercase b standing for beta.

**Comment by aubergine10** [comment]
That would work for milestone names in github as well @krzychu124 ?

**Comment by VictorPhilipp** [comment]
IMO we could remove the "1." prefix entirely.

Just increment major build number for every new feature version, and increment minor build number for every fix (11.0, 11.1, ... , 12.0, 12.1, 12.2, ...).
If we plan to implement a strict migration scheme such that each labs version will eventually become stable then we don't need the "b" suffix.

Proposed process: New features are rolled out first on labs (say v12.0) while stable remains on the previous version (v11.0) for some time. If a bug is found and fixed, both versions are updated, such that stable becomes v11.1 and labs becomes v12.1. When a feature is ready for stable, the current labs version (v12.1) becomes the new stable and the new labs version is incremented (v13.0).

**Comment by krzychu124** [comment]
I like this idea and I think that it is possible to create one more project in Appveyor for easier version managing. 
I'll check that later.

**Comment by aubergine10** [comment]
Can we also ensure auto-build numbering in the AssemblyInfo.cs? (if it's not already there - would check but I currently have about 40 browser tabs and 30+ VS2017 tb open and my brain is thinking of herding mountain goats again)

**Comment by VictorPhilipp** [comment]
Auto-build numbering is already active
