### ISSUE TITLE
Test "Old Town" Policy

### ISSUE THREAD

**Issue by VictorPhilipp** [krzychu124/Cities-Skylines-Traffic-Manager-President-Edition#167]
Just spotted this in Park Life release notes:

> Fixed: All traffic use Bus & Taxi lane when Old Town policy is active

I've never used that policy myself, but just flagging it up as something to test as vanilla code change will need carrying across to TM:PE.

https://github.com/VictorPhilipp/Cities-Skylines-Traffic-Manager-President-Edition/issues/134

**Comment by VictorPhilipp** [comment]
I believe the "Old Town" policy should work as expected but I have not tested it yet in the most recent version.

**Comment by aubergine10** [comment]
Tested, seems to work fine regardless of the "Ban private cars and trucks on bus lanes" setting.

**Comment by aubergine10** [comment]
There will still issues, tracked in: https://github.com/krzychu124/Cities-Skylines-Traffic-Manager-President-Edition/issues/371
