### ISSUE TITLE
Revise mod compatibility checker code so Labs doesn't unsub Stable

### ISSUE THREAD

**Issue by aubergine10** [krzychu124/Cities-Skylines-Traffic-Manager-President-Edition#168]
Currently the recently added mod compatibility checker code will try and unsub the 'stable' LinuxFan workshop version of the mod (as we thought it was dead).

That code will need updating ASAP otherwise if it gets in to stable branch the stable version will decide it's not compatible with itself, which will be quite amusing actually lol.

The PR where code was added: https://github.com/krzychu124/Cities-Skylines-Traffic-Manager-President-Edition/pull/106

**Comment by krzychu124** [comment]
@VictorPhilipp disabled compatibility checker in stable branch 😉

**Comment by FireController1847** [comment]
Since this appears to have been solved, should we unpin the issue?
