### ISSUE TITLE
Setting up traffic lights is cumbersome and confusing

### ISSUE THREAD

**Issue by VictorPhilipp** [krzychu124/Cities-Skylines-Traffic-Manager-President-Edition#173]
I'm finding the traffic light tools to be very difficult to work with for following reasons:

* Current setup is from perspective of driver looking at the lights
    * When setting up roads, I'm looking from above as a road planner, not a driver on the street
    * So I want to see lane connectors and other visual feedback on the road from above (in addition to existing traffic light overlays)
* There is no indication of which lane connections have been "given their turn":
    * Did I miss any connections?
    * Are the connections set up the way I expect them to be?
* Separation of manual and timed traffic lights is weird; the manual option seems to be more of a training tool to prepare users for the complexity of the timed traffic lights?

**Suggestion:**

Improve UX and as a result merge manual and timed traffic lights features in to a single, easier to use, feature.

Prerequisite: Make lane connection lines follow proper path (that vehicles would take when following the connection) - maybe grabbing code from vehicle AI (or whatever it is that moves vehicle meshes through junctions)? This would also greatly enhance the lane connector tool.

For a given junction:

> * When initially editing traffic lights, all lane connections are shown as thin (1px? dotted?) white lines indicating they do not yet have any "green time" assigned.
> * Hover over a traffic light overlay, or a road segment, and all associated connections increase width = quick visual indication of applicable connections to help with context awareness/orientation
> * When a light overlay is turned green, the associated connections turn green = visual confirmation from above (I'm in no doubt as to which lanes will be affected)
> * When I save and move to next step in the sequence, connections with assigned "green time" turn red (or amber if next step in sequence would turn them green) = I can see which connections (white ones) are not yet handled by the sequence
> 
> For pedestrian connections, they could be shown as line across the segment a few millimeters away from junction? NB: Also take in to consideration node restrictions.
> 
> At some point all connections will be red, amber or green = I know I've completed the sequence.

Connection colour recap:

> * Green = that connection is green for current step
> * Amber = it will be green in the next step
> * Red = it's green at some point, just not in the current or next step
> * White = it does not have any "green time" assigned in the currently existing steps

Timings and ratios:

> I don't really want to be thinking about timings whilst setting up the lights - especially if the sequence involves multiple junctions (see below for info on that). Ideally I want to get the light states set up first, then fiddle with timings and ratios separately.

Multi-junction sequences:

> At any time whilst editing a sequence, I should be able to click additional junctions to include/exclude them from the sequence (ie. no need to click a button in the Mod UI, just click the junctions I want to include in the sequence).
> 
> Traffic lights at each junction are configured just like the single junction example given above.

Highlight lanes affected by the sequence:

> In the old Traffic++, when setting speeds and vehicle restrictions, the lanes were highlighted with "sausage" shaped overlays as seen here on one of the screenies I did for the mod:
> 
> ![steamuserimages-a akamaihd](https://user-images.githubusercontent.com/1386719/40622547-14f5cb3e-629a-11e8-96ff-454a7e83c562.jpg)
> 
> Could something like that be used to indicate the traffic light states at both ends of a route between junctions? Specifically: When I set a light green, the affected outgoing lanes get solid green lines, and the affected incoming lanes get dashed green line (solid = outgoing, dashed = incoming). The other states would apply too: Red lines for red lights, amber lines for "green next step", white lines for "not configured yet"...
> 
> This effect would always apply, not just when I'm working with multi-junction sequences. The lines would extend from the junction(s) in a sequence along the roads to the next junction, regardless of whether that junction is part of the sequence or not.
> * If I have a single junction in my sequence, I'll see a bunch of dashed lines on the incoming lanes, and solid lines along the outgoing lanes.
> * When there are multiple junctions in the sequence, it's possible to end up with a lane having both dashed and solid lines (side by side, like the two sides of the sausage overlay from above, but without the ends of the sausage rendered and much less space between its sides) because it's affected by lights at both ends.
> * As an added bonus, if I'm working on a multi-junction route and I miss a junction, it will be really obvious where the missed junction is. It will also make it really obvious which adjacent junctions are being affected by my sequence.

https://github.com/VictorPhilipp/Cities-Skylines-Traffic-Manager-President-Edition/issues/143

**Comment by VictorPhilipp** [comment]
For vehicle-specific lanes, I found the icons being separate from the traffic light to be confusing. Are they something I can click? Toggle buttons? Without RTFM, I had no real clue what they meant.

Suggestion: Put icon of vehicle on the traffic light itself (rather as separated to the side). The icon could appear attached to the top of the light.

Also, as per ideas in OP, hovering over the light would highlight the associated lane connections to aid user context awareness and orientation.

**Comment by aubergine10** [comment]
There's a redux version of this here: #8 (lights tool)
