### ISSUE TITLE
Disable pedestrian traffic light for disabled pedestrian crossing

### ISSUE THREAD

**Issue by VictorPhilipp** [krzychu124/Cities-Skylines-Traffic-Manager-President-Edition#178]
First, thanks for maintaining this wonderful mod. The game is so much more fun with it.

Feature request:
Is it possible to disable the pedestrian traffic light for crossings that have pedestrian crossing disabled? Currently vehicles are waiting for pedestrian light to go red before they can move, but there will be no peds crossing because it is disabled.

https://github.com/VictorPhilipp/Cities-Skylines-Traffic-Manager-President-Edition/issues/156

**Comment by VictorPhilipp** [comment]
Could you clarify your request? Vehicles never wait for pedestrian lights to become red, they rather wait for pedestrians crossing the road.

**Comment by VictorPhilipp** [comment]
Makes sense, let me take a closer look. I'll get back to you later.

**Comment by VictorPhilipp** [comment]
Yup, the problem is actually the need of a right turn light, because no peds are crossing. It makes no sense to wait for right turn.

**Comment by VictorPhilipp** [comment]
Nevertheless, the pedestrian traffic light overlay could be hidden if the crosswalk is disabled.

**Comment by VictorPhilipp** [comment]
Would it be possible to hide the striped crossing decal (or whatever it is) if the crossing is disabled? That would be fantastic for visual feedback on the map as to which crossings are enabled/disabled.

EDIT: The [Road Options mod](https://steamcommunity.com/sharedfiles/filedetails/?id=932192868&searchtext=road+color+changer) ([github - code not yet uploaded](https://github.com/TPBCS/RoadOptions)) has an option to hide all stripy crossings - could that code be adapted to only hide those which are disabled?

**Comment by VictorPhilipp** [comment]
I think crosswalks cannot be removed for individual road segments (same as lane arrows).

**Comment by aubergine10** [comment]
This would be part of #8 and #6

**Comment by kianzarrin** [comment]
@krzychu124 can we close this issue since its already resolved?

**Comment by aubergine10** [comment]
Just tested in-game, if ped crossing is disabled the timed traffic light does not show icon for it when editing steps, so this issue is be resolved.

Crossing decal issue handled in #27
