### ISSUE TITLE
Hide lane arrow

### ISSUE THREAD

**Issue by VictorPhilipp** [krzychu124/Cities-Skylines-Traffic-Manager-President-Edition#182]
I've realised I can hide lane arrows, but only if there's no custom lane connections at the node. Also, if I'm not mistaken, hiding the arrow also means no connections from that lane at the junction/node?

For detailing and general beautification of roads (particularly at transitions between ground, elevated, bridge, etc.) it would be really useful if I could simply "hide" individual lane arrows without affecting connections. And (nice to have) a keyboard modifier (Alt+Click?) on the "hide" button to toggle visibility of all lane arrows for selected segment(s).

There could perhaps be an extra button to toggle visibility of the lane arrow, which would work even if there are custom lane connections for that lane?

Possible icon for button: [eye](https://thenounproject.com/term/eye/190164/)

https://github.com/VictorPhilipp/Cities-Skylines-Traffic-Manager-President-Edition/issues/169

**Comment by VictorPhilipp** [comment]
There are mods that purpose:
https://steamcommunity.com/workshop/browse/?appid=255710&searchtext=remove+arrow&childpublishedfileid=0&browsesort=textsearch&section=home

(Yes those will remove all lines/arrows)

**Comment by VictorPhilipp** [comment]
Yes, I am aware of these mods that remove all arrows.

For example, if I want to close a single lane of a motorway between two junctions (exit and entry), I only want the single arrow removing. I don't want to remove all arrows across all roads and then spend ages manually recreating them just to remove the arrows from that single lane of motorway between the two junctions.

And even with things such as ploppable asphalt, which afford a more granular approach, I am often not able to remove the existing arrows without creating floating patches of tarmac.

So far, the only mod I've seen that allows me to remove individual lane arrows is TM:PE. And it's just a single "hide button" away from being able to scratch that arrow itch.

**Comment by VictorPhilipp** [comment]
I believe it's technically impossible to prevent individual lane arrows from being rendered at specific road segments.

**Comment by VictorPhilipp** [comment]
On the lane arrow changer tool in TM:PE, you get three buttons for each arrow. If I "unselect" each button the associated arrow is removed from the lane. I was just wondering if it was possible to have a "hide" button that has the same effect, but while leaving the lane connections in place?

**Comment by VictorPhilipp** [comment]
Ok, that's possible of course. I would have to create a new data structure that holds the lane arrows and decouple routing decisions from the base game's arrows

**Comment by aubergine10** [comment]
This is one of the things we'll be covering in lane routing/arrows overhaul: #41
