### ISSUE TITLE
Parking AI seems unreliable

### ISSUE THREAD

**Issue by VictorPhilipp** [krzychu124/Cities-Skylines-Traffic-Manager-President-Edition#194]
My city is filled with parking spaces, many of which are empty, yet I see vehicles travelling to many destinations roaming around looking for parking.

Context:
* Left side driving
* Lots of cul-de-sacs around areas where cims are trying to get to

If you need a save or any other infos, let me know.

https://github.com/VictorPhilipp/Cities-Skylines-Traffic-Manager-President-Edition/issues/204

**Comment by VictorPhilipp** [comment]
Since the recent update I've noticed a big improvement, in that there is far less 'stray traffic' (eg. my industrial areas are no longer filled with 'looking for parking' traffic from distant leisure and tourist districts).

However, cims still aren't finding parking spaces near their destinations. #184, #150 and #209 would greatly alleviate this issue.

**Comment by aubergine10** [comment]
Closing as `obsolete`.

Updated links to issues mentioned above: #189, #176, #196
