### ISSUE TITLE
Russian translation update

### ISSUE THREAD

**Issue by aubergine10** [krzychu124/Cities-Skylines-Traffic-Manager-President-Edition#207]
> vitalii201 (steam user): Still a little translation fix
> https://pastebin.com/bjRxGkgg

It's possible he also sent PR to old repo? I've not had any notifications (and am contrib on that repo) so possibly not. Anyway, the patebin seems to contain the full locale file.

**Comment by VictorPhilipp** [comment]
Side note: Can we have multiple milestones for the same issue? We have to synchronize versions...

**Comment by aubergine10** [comment]
> Side note...

Not that I'm aware of - github only allows one milestone :/

Looks like we'll need multiple issues for things like this which is a bit of a PITA.

**Comment by VictorPhilipp** [comment]
(off-topic)
1. We could represent milestones with labels.
2. We could enforce a strict transition scheme from labs to stable where each labs version must become stable at some time (though this would limit our abilities (which is not always bad))

**Comment by VictorPhilipp** [comment]
Fixed in 1.10.15-stable.
Update for 1.10.17-labs pending.

**Comment by aubergine10** [comment]
(off-topic)

After stable reaches parity with labs, we can then do the strict labs -> stable thing.

I'm not sure using labels for milestones will work out well. We'd just end up with loads of crufty labels, and the milestones view would get confusing too.

Ultimately I think we'll end up doing work against a labs milestone, and then once it's tested in  labs we update the issue to use a stable milestone. So issue stays open to remind us that there's something that  needs porting to stable.

This is probably best discussed in the developer discord chat or a separate issue ticket.
