### ISSUE TITLE
Stable 1.10.14 may have borked traffic lights & vehicle restrictions

### ISSUE THREAD

**Issue by aubergine10** [krzychu124/Cities-Skylines-Traffic-Manager-President-Edition#208]
So far only one report but just flagging this up now in case anyone can spot potential issues with the 1.10.14 release pushed to Stable workshop page.

> Kut2Keep 9 minutes ago 
> This update removed all my timed lights and restrictions. Is there a way to get them back?

Sounds like he hadn't used the Labs version at all.

**Comment by pcfantasy** [comment]
@aubergine10 

I also lost all save data when switch back to VictorPhilipp`s TMPE

**Comment by krzychu124** [comment]
Yeah, there is no TurnOnRed there yet :/

**Comment by VictorPhilipp** [comment]
Oh yes, switching to labs, saving and returning to stable causes this issue. I inserted a preprocessor condition, TURNONRED. It needs to be removed in the Configuration class

**Comment by aubergine10** [comment]
@shinzon76 We've determined that your issue #209 is a duplicate of this issue #208. To keep things tidy, we're going to close #209 but you can follow progress here in #208.

**Comment by VictorPhilipp** [comment]
Fixed in the pre-stable version 1.10.15-stable.
