### ISSUE TITLE
Field 'TrafficManager.State.Options.turnOnRed' not found.

### ISSUE THREAD

**Issue by aubergine10** [krzychu124/Cities-Skylines-Traffic-Manager-President-Edition#210]
Reported on the Stable workshop page:

> Klapaerl 2 hours ago 
> Field 'TrafficManager.State.Options.turnOnRed' not found. [System.MissingFieldException]

I can ask for log file but I suspect this is likely side-effect of moving from Labs (1.10.16) to Stable (1.10.14)?

**Comment by pcfantasy** [comment]
@aubergine10 
This guy may use my mod, and my mod is based on lab version currently.
But I will show a window to warning incompatiable, you can ask him to give AdvancedJunctionRule.txt to me for debug if he use my mod.

**Comment by aubergine10** [comment]
Will do!

**Comment by aubergine10** [comment]
Tagging #208

**Comment by VictorPhilipp** [comment]
Cannot be fixed on our side.

**Comment by VictorPhilipp** [comment]
We should convert any kind of static stuff into instance variables/methods

**Comment by pcfantasy** [comment]
@VictorPhilipp 
Yes, AdvancedJunctionRules is detour MayChangeSegment method in TMPE. And now two TMPE is different in this method now.

Actually I have fixed this issue by check which TMPE is in loadextention, and then detour different MayChangeSegment codes. I have not update it on steam yet.
