### ISSUE TITLE
Add 'realistic vehicle speeds' mod to incompatibility checker

### ISSUE THREAD

**Issue by aubergine10** [krzychu124/Cities-Skylines-Traffic-Manager-President-Edition#213]
Just a reminder for me to do this...

https://steamcommunity.com/sharedfiles/filedetails/?id=631930385

**Comment by VictorPhilipp** [comment]
The mod compatibility check is currently not active in the pre-stable version. Skipping for now.

**Comment by VictorPhilipp** [comment]
@aubergine10 The pull request has been merged - can this issue be closed?
