### ISSUE TITLE
Lane changes happen at toll boothes

### ISSUE THREAD

**Issue by VictorPhilipp** [krzychu124/Cities-Skylines-Traffic-Manager-President-Edition#225]
> # Temporary Workaround
> Use the lane connector tool, click the toll booth road node(s) and then press Shift+S to set them all "ahead only"

----

They should not.

**Comment by aubergine10** [comment]
@VictorPhilipp Was this still happening recently (likely due to DLS)? If so should this be reopened?

**Comment by aubergine10** [comment]
This seems to be most recent change to toll booth lane swapping: https://github.com/krzychu124/Cities-Skylines-Traffic-Manager-President-Edition/pull/121/commits/63a653c35c1e856f2be2bb9fcce20376f26ac42e

**Comment by aubergine10** [comment]
Video of issue still happening on v10.18, via @FireController1847 

https://www.youtube.com/watch?v=MYdVGrpmJCQ&feature=youtu.be

**Comment by aubergine10** [comment]
Still happening in 10.20

![Screenshot_3](https://user-images.githubusercontent.com/1386719/58240997-fe0c2380-7d43-11e9-87c2-3f53fb0b858c.png)

**Comment by SubaruSVX** [comment]
I was the one who had that picture.

My savegame:
https://steamcommunity.com/sharedfiles/filedetails/?id=1736078702

Where this picture was taken - if you spot the three-way interchange that leads into a city area (not the Bork and Heck University one), you should see that cars are piling up and in some cases, changing lanes in the toll booth.

**Comment by SubaruSVX** [comment]
Temporary workaround:

This doesn't quite apply to emergency vehicles, but if you were go into the lane connector nodes and press Shift + S where the cars stop in the toll booth, you can get the cars to stay in their lane when they pass the toll booth.

**Comment by VictorPhilipp** [comment]
The code that determine whether the node represents a toll booth or not is erroneous.
https://github.com/FireController1847/Cities-Skylines-Traffic-Manager-President-Edition/blob/589be86a2a7272622ba22247c5c1b2b5c5f5b4b2/TLM/TLM/Manager/Impl/RoutingManager.cs#L313

The correct way would be to
1. find the building that is associated with the transit node
2. check whether the building is a toll booth
3. If yes: prohibit lane changes

**Comment by VictorPhilipp** [comment]
The method I described above would imply to run a grid search for every road node on every geometry update.

**Comment by VictorPhilipp** [comment]
Luckily the draw on performance is not significant. Regular vehicles should now stay in their respective lane. Yet emergency vehicles on duty still change lanes at toll boothes. Actually, I think this is something CO has to fix. Their code does not check whether lane changes are allowed/possible in the (see `VehicleAI.FindBestLane`). I will ask them on Monday if they are aware of this problem.

**Comment by aubergine10** [comment]
So, toll booths are just buildings (with a sub building), for example `Twoway Toll Booth Medium 01` which is in category `Road`:

![Twoway Toll Booth Medium 01](https://user-images.githubusercontent.com/1386719/58742177-5b763380-841a-11e9-89f9-1b16f32ad6b5.jpg)

and its sub building, `Twoway Toll Booth Medium 01 Sub` in same category:

![Twoway Toll Booth Medium 01 Sub](https://user-images.githubusercontent.com/1386719/58742180-692bb900-841a-11e9-85ce-844ca74e2202.jpg)

Can we have a lookup list of nodes, the size of list being whatever the game limit is for nodes, and store the details about nodes in there? One of the details being "is this a toll booth" another detail being "is this straight ahead only" and so on? (or is that what already happens?)

Each time a toll booth building (identified by its AI) is placed, moved or removed, the lookup list gets updated accordingly.

It would be useful to have a consistent 'single source of truth' that the pathfinder can use, to remove as much branching as possible from the decision making code in the pathfinder (and vehicle AIs too if applicable).

**Comment by VictorPhilipp** [comment]
Routing decisions are already precalculated by `RoutingManager`. It operates at simulation time (not during path-finding) and updates routing data only if a change in the traffic network is detected.

**Comment by VictorPhilipp** [comment]
Ok, so CO is aware of the issue with the emergency vehicles. But on the other hand, since TMPE does routing a bit differently we should fix that too.
