### ISSUE TITLE
Emergency vehicles flying off sharp junctions

### ISSUE THREAD

**Issue by aubergine10** [krzychu124/Cities-Skylines-Traffic-Manager-President-Edition#23]
Does 'realistic speeds' and/or 'reckless drivers' option affect emergency vehicles (particularly police/ambulance/fire)?

The 'realistic speeds' docs state:

> Heavy vehicles choose their target speed within the interval -10 % .. ± 0%.
> Reckless drivers drive +30 % .. + 200 % faster than allowed.
> Remaining vehicles randomize their target speed within the interval -20 % .. +30 %.

When responding to emergencies, these vehicles hit top speeds and can sometimes literally fly off the road if going too fast.

I don't know if this is due to TMPE changing their speeds, or if it's just crazy default speed defined by the asset (I have loads of custom vehicle assets for emergency vehicles).

Also, reckless drivers getting up to 200% speed increase might be overkill (while I've only noticed emergency vehicles flying off a junction, I assume a reckless sports car driver might experience the same fate).

IMO, service vehicles in general should be excluded from 'realistic speeds' and 'reckless driver' features if TMPE doesn't already do that?

**Comment by krzychu124** [comment]
If you look closely what happen if e.g. police car is going on lights you will see that he will try to overtake every possible car ahead even at junctions with traffic lights and sometimes ignore lane arrows. It's fun to watch 😃 Here is function calculating that 'realistic speed'
https://github.com/krzychu124/Cities-Skylines-Traffic-Manager-President-Edition/blob/fae45d3306ee0ba17053d355838797b4236c5e88/TLM/TLM/Manager/Impl/VehicleBehaviorManager.cs#L676:L690

**Comment by krzychu124** [comment]
And here we have these LargeVehicles 
`(VehicleInfo.VehicleType.Ship | VehicleInfo.VehicleType.Plane | VehicleInfo.VehicleType.Helicopter | VehicleInfo.VehicleType.Meteor | VehicleInfo.VehicleType.Vortex | VehicleInfo.VehicleType.Ferry | VehicleInfo.VehicleType.Blimp | VehicleInfo.VehicleType.Balloon | VehicleInfo.VehicleType.Rocket)`

**Comment by aubergine10** [comment]
Yup, so this would affect emergency vehicles which can already move pretty fast and make them go crazy fast.

Would it be worth having an separate range (maybe 0.9% .. 1.1%) for emergency (police, ambulance, fire) road vehicles?

**Comment by krzychu124** [comment]
Ok, I've tweaked that speed multiplier for reckless drivers (including police, ambulance, fire) from 1.3...3 to 1.1...1.6

**Comment by aubergine10** [comment]
So that's +10% .. +60% ? (I'm updating the docs)

**Comment by krzychu124** [comment]
Yup, if I understand correctly what this part of code is doing 😉

**Comment by aubergine10** [comment]
This seems to be working much nicer now.
