### ISSUE TITLE
Trains Maintain Their Lanes (hey that rhymes)

### ISSUE THREAD

**Issue by andreharv** [krzychu124/Cities-Skylines-Traffic-Manager-President-Edition#230]
The code may already be in here (just needs to be reorganized) but as quad tracks are soon to become a thing, it would be nice to have vehicles (trains in this case) favor the lane they are on rather than switching lanes for a slight distance difference in curves.  The exception to this, of course, would be if the placed stops mandated a lane change which would mainly be an issue for quad tracks with central bypass lanes.  Otherwise there would be no reason for a lane change as all junctions naturally connect all compatible lanes.  I don't remember if the pathfinding is a weighted system but basically this would all be fixed if more 'weight' was added to changing lanes.  That way trains would not do it unless there was no other way to reach their endpoint or the speed difference between the lanes outweighed the lane change (which I would imagine would be rare).

**Comment by andreharv** [comment]
Ok giving this 2 seconds of thought, it is very similar to #89 Medians. It will operate the same as a road that has medians separating each lane, except at 3+ network junctions.

**Comment by aubergine10** [comment]
The issue of vehicles changing lanes for a slightly shorter distance at curves also affects highways in a most annoying manner: #112

**Comment by VictorPhilipp** [comment]
Path-finding uses average segment length for cost calculation, not lane length. Your issue must be caused by something else.

**Comment by VictorPhilipp** [comment]
@andreharv Could you please post a screenshot or a savegame that shows this behavior? I would like to investigate this issue.

**Comment by VictorPhilipp** [comment]
@andreharv This only occurs for one-way tracks, correct?
![grafik](https://user-images.githubusercontent.com/4333935/54372969-bfd7f100-467c-11e9-857b-68105c29bcaa.png)

**Comment by andreharv** [comment]
Yes.  This is only an issue on one way tracks and quad tracks (MOM).  If you send me your email, I can give you a copy of the MOM build (it's near complete).  It will be a lot easier to see when putting down quad tracks and stations.  All the lanes are the same speed except for the bypass station tracks (outer tracks are stations and inner tracks are bypass).
