### ISSUE TITLE
Undo deletion of timed light step

### ISSUE THREAD

**Issue by VictorPhilipp** [krzychu124/Cities-Skylines-Traffic-Manager-President-Edition#234]
Domaldel:
"Hum, moving the delete stage button from the timed traffic light editor in order to make it less likely to accidentally delete stages when you're adding new ones to a new junction would be fine.
Making 15 stage timed traffic lights for 12 different junctions including train tracks in half of those junctions and trying to add another one only for a stage to be deleted is not... fun..."

**Comment by aubergine10** [comment]
IMO it would be better to wait for overhaul of traffic lights UI before doing stuff like this

Tagging #8

**Comment by aubergine10** [comment]
This was fixed in release 10.19 - specifically, issues: #283, #285
