### ISSUE TITLE
Low amount of cars in service

### ISSUE THREAD

**Issue by krzychu124** [krzychu124/Cities-Skylines-Traffic-Manager-President-Edition#24]
__clemenclm2001:__

>The first of all sorry for my engish, it's not my mother languaje and it,s very possible that I make a lot of mistakes.
>
>I think that my problem is very common, I don't know if is possible to solve.
When I put (for example) a taxi depot at the beginig the number of taxis rise very fast but inmediatly the number is lower ... not 0 but very lower... it rises 2, it rises 4 and after that it goes down to 1-2 and always is 1-2... not more than 5-6.
It happens also with the others vehicles (trash, and deathcare)
I have to put a lot of depots if I want to receive a normal service.
If I unsuscribe this mod everythink is ok
Any idea?
[https://steamcommunity.com/workshop/filedetails/discussion/1637663252/1739980540129984264/#c1777135944136297014](url)

**Comment by aubergine10** [comment]
I had this exact same problem until I realised an auto-budget mod had reduced budget for taxi service, thus limiting the number of vehicles available to the taxi building.

Otherwise I've not noticed any particular issues with taxis. Will do some testing when I'm next in game.

**Comment by Mirrrie** [comment]
Hello, I have the same issue.  Not more then 2 hearses and barly garbagetrucks. When I disabled the mod slowly they returned. I checked the  Incompatibile modlist and I don't have any conflicts.

**Comment by krzychu124** [comment]
Hi @Mirrrie could you post your savegame (dropbox, googledrive or any other file sharing service)?

**Comment by Mirrrie** [comment]
Yes! Do I need to disable all my mods first or do you want my modlist ?

**Comment by aubergine10** [comment]
It's probably better if you keep your mods enabled so we can see what mods are in use and create your game setup as closely as possible to maximise the chance off recreating the problem.

**Comment by krzychu124** [comment]
[Just follow instructions](https://github.com/krzychu124/Cities-Skylines-Traffic-Manager-President-Edition/wiki/Share-your-Savegame-on-Steam) 😉

**Comment by Mirrrie** [comment]
Sorry I had a surgery last wday and my brains dont function very well yet . Ill read the instructions tomorrow and upload my safegame.. Thanks for all the efford and bringing the mod back

**Comment by aubergine10** [comment]
@Mirrrie do you have lots of roads with bus lanes?

If so, can you try following the steps in this [Troubleshooting Guide](https://github.com/krzychu124/Cities-Skylines-Traffic-Manager-President-Edition/wiki/Industry-resources-collection-and-delivery-issues) and see if it solves the problem?

I think it's same problem that's affecting industry vehicles (#85 - car/truck ban in bus lanes is preventing vehicles spawning or reaching destination).

**Comment by Mirrrie** [comment]
Im sorry for taking such long time. Ill do it right now :)

**Comment by aubergine10** [comment]
Closing as no response.

If issue persists, please see our [troubleshooting guide](https://github.com/krzychu124/Cities-Skylines-Traffic-Manager-President-Edition/wiki/Troubleshooting) which now lists all known causes of vehicle spawning issues and how to fix them.
