### ISSUE TITLE
Advanced Parking AI prevents new traffic spawning on highways

### ISSUE THREAD

**Issue by aubergine10** [krzychu124/Cities-Skylines-Traffic-Manager-President-Edition#245]
Multiple reports on Steam and elsewhere that, when Parking AI is enabled, new traffic stops spawning on highways.

Specifically, this seems to relate to new citizens entering the city (ie. new residents moving in to housing).

The result is that city growth stalls and economy goes pyriform as a result.

## Temporary Workaround

Disable **Advanced Parking AI** in mod settings.

**Comment by aubergine10** [comment]
Some additional infos (I think you already got this covered looking at the PR, but just in case...):

* Even with Parking AI turned off , some users still seeing same problems
* It's also affecting, to a somewhat lesser extent, the industry traffic that spawns from outside connections

**Comment by VictorPhilipp** [comment]
Fix implemented

**Comment by aubergine10** [comment]
Awesome, will test this evening.
