### ISSUE TITLE
Field 'TrafficManager.State.Options.turnOnRed' not found. [System.MissingFieldException]

### ISSUE THREAD

**Issue by pocketpanties** [krzychu124/Cities-Skylines-Traffic-Manager-President-Edition#246]
Since the update I'm getting the following error every time I open a saved file:

Field 'TrafficManager.State.Options.turnOnRed' not found. [System.MissingFieldException]

Details:
No details

Savegame: https://steamcommunity.com/sharedfiles/filedetails/?id=1693833059

[output_log.txt](https://github.com/krzychu124/Cities-Skylines-Traffic-Manager-President-Edition/files/3004100/output_log.txt)

**Comment by pcfantasy** [comment]
@pocketpanties 

I will update advancedjuctionrule to fix this issue.
