### ISSUE TITLE
Trams make a turn-on-red into a protected movement of blocking traffic

### ISSUE THREAD

**Issue by brazenest** [krzychu124/Cities-Skylines-Traffic-Manager-President-Edition#248]
I've been seeing [this issue](https://steamcommunity.com/profiles/76561198843494213/screenshot/1009276993142160603) in the 10.17 release when turn-on-red is enabled.

For now I'm manually disabling the feature where a tram has the opportunity to make a right turn.

I assume we now need ability to differentiate the turn-on-red policy for different vehicle types and/or lane types.

**Comment by aubergine10** [comment]
This might be related to https://github.com/krzychu124/Cities-Skylines-Traffic-Manager-President-Edition/issues/53
