### ISSUE TITLE
Left Turn on Red

### ISSUE THREAD

**Issue by jgman20** [krzychu124/Cities-Skylines-Traffic-Manager-President-Edition#249]
In my state as well as 4 other states in the United States, you can turn left on red from a two-way onto a one-way (across traffic) on red.  Is there any chance of adding support for this to the mod?

**Comment by aubergine10** [comment]
Yes, we've been discussing features like this recently so this feature will likely make it in at some point.

Related issues:

* #63 - unprotected turns
* #46 - junction turn filters
* #8 - lights tool

I think #63 in particular covers the desired behaviour?

**Comment by jgman20** [comment]
It sounds like #63 mentions it, and #46 includes it.  I'll keep an eye on these.
Will these also mean in theory, you would be able to have a straight on red (strange as that would be)?

**Comment by aubergine10** [comment]
Unlikely to have straight on red.

Currently we have 'near-side turn on red' (eg. right turn if traffic is driving on right) and plan to at some point implement 'far-side turn on red' (eg. left turn if the traffic is driving on right).

**Comment by jgman20** [comment]
Alright, that makes sense now.  I've never actually seen straight on red, so I wasn't suggesting that, unless someone else wants it, but that'll be for them to discuss.

**Comment by aubergine10** [comment]
Is it OK to close this issue as the other listed issues seem to cover the requirement of left on red?

**Comment by jgman20** [comment]
Yes, I think so.
