### ISSUE TITLE
Industries: Extractor buildings not spawning freight trucks

### ISSUE THREAD

**Issue by aubergine10** [krzychu124/Cities-Skylines-Traffic-Manager-President-Edition#256]
Issue report from TheCyborg (Steam; via Stable workshop page):

> Hey I got a problem, I'm playing with this and Industries DLC installed, and on all of my extractor buildings whenever this mod is active the extractors stop spawning freight trucks. In the extractor it displays the number of active freight trucks as flickering between 0/1 but nothing gets delivered, as soon as I disable Traffic Manager trucks start spawning again.

* [log file](https://drive.google.com/drive/folders/1H6wVXzvmRJKq3wKIZ84hh85sDPdgnMX9?usp=sharing) 
* [savegame](https://steamcommunity.com/sharedfiles/filedetails/?id=1695943896)

> Hopefully these are the Savegame and Log Files for the game with the bug, the Mining Industry at the Extractors is where the issue is they just seem to be unable to spawn trucks, the issue resolves itself when turning off TMPE. 
>  
> I have a few smaller mods adding building variants but nothing affecting industries, the only mod of note would be Network Extentions 2 but the extractors have vanilla roads connected to them so ?
>  
> Anyway thanks for being willing to look at this, it could just be mod conflict issue on my part but Im stumped so thanks anyway

**Comment by VictorPhilipp** [comment]
![grafik](https://user-images.githubusercontent.com/4333935/55268085-10f40180-5287-11e9-837b-31f9d888505b.png)

Target lanes (orange) are unreachable due to these lane connections (red circles).
