### ISSUE TITLE
Disable incompatible mod warning option

### ISSUE THREAD

**Issue by aubergine10** [krzychu124/Cities-Skylines-Traffic-Manager-President-Edition#264]
There's an checkbox to disable incompatible mod warnings in the TMPE mod options. As far as I can tell this seems mainly related to detection of methods overwritten by other mods (ie. the error will appear after starting/loading a game).

Since the recently added #91 incompatible mod checker (which displays warning at start up), the option is confusing some users - they are expecting it to hide the warning screen at start up, and are probably not aware of the one in-game.

Would it be worth changing it so that it toggles the start-up mod checker, and not the in-game method override checker?

Also, would the in-game override checker be affected by the huge refactor taking place as part of #119 harmony migration?

**Comment by VictorPhilipp** [comment]
> Would it be worth changing it so that it toggles the start-up mod checker, and not the in-game method override checker?

IMHO the start-up mod checker should be a separate mod that is required by TMPE. It should also allow the user to unsubscribe from either of the two conflicting mods. ("Unsubscribe TM:PE" / "Unsubscribe FooBar Mod")

> Also, would the in-game override checker be affected by the huge refactor taking place as part of #119 harmony migration?
The in-game checker has already been migrated to Harmony. It can detect both harmony patches and legacy detours.

**Comment by aubergine10** [comment]
I'm working on a mod that would be ideal for that, but it's kinda stalled at the moment but hopefully resume it soon.

**Comment by aubergine10** [comment]
Seems there is also a buglet when unsubscribing the Toggle Traffic Lights mod (possibly error with that mod not disabling properly) - so the new mod that does incompatibility checks will need to suggest restarting game after any unsubscribing.

Steam user Stifflersmumx1:

>I also figured, havin TTL in the Modlist, loading the game and hitting "unsubscribe" on TMPE Error Report wasnt enough, my Game kept crashing. Had to restart without any Incompatible Mods to have the Game loading 
> https://i.imgur.com/DvRHHeL.jpg

**Comment by aubergine10** [comment]
Implemented in PR #286
