### ISSUE TITLE
Trucks not spawning (on v10.18)

### ISSUE THREAD

**Issue by aubergine10** [krzychu124/Cities-Skylines-Traffic-Manager-President-Edition#267]
Two saves (same city, just different dates) available. v1 had some additional errors (now resolved) and v2 is purely the truck spawn issue.

* Save v1: https://steamcommunity.com/sharedfiles/filedetails/?id=1697579452
* Save v2: https://steamcommunity.com/sharedfiles/filedetails/?id=1699534254

Steam user 'Detail':

(note: this is mid-conversation after solving some other issues; we're on TMPE v10.18, and save v1 at this point)

> Well this is certaintly disappointing, I restarted the game and saw the same behavior. I watched areas on both the highway and the city for several minutes, except for garbage trucks I did not see one truck. My city imports are at 5 and my exports are at 4. All this work on this map and I will probably have to leave it as something has happened obviously.

(some discussion skipped)

> Hi auber, I probably had the game on for about 15 minutes. I will go back and let it run longer. On a hunch I started the same map as a new game and no issues with traffic the roads are full of trucks. So that seems to point to something in this map. I also got some index errors this morning which I need to investigate for whatever reason. I think they have to do with metro work from yesterday. I'll restart now.

Detail started a new game - same map, assets, mods, etc and the trucks were working on the new game, so issue seems save specific (maybe a common road customisation issue?)...

> Update: I watched it for 20 minutes, did not spawn a single truck. Since the new load does have trucks on it with the same map, I'd agree that to at least at that level the fixes work, they just don't on my existing map. The trucks went away and they haven't returned.

Advised to check the troubleshooting guide: https://github.com/krzychu124/Cities-Skylines-Traffic-Manager-President-Edition/wiki/Vehicles-not-spawning (note - it's been updated since that point)

> Auber, I did some additional work over the last hour. I started a new game using the same map and same mods and assets, I took 3 screenshots which show an over abundance of traffic and trucks. Then I restarted the old game (the one that is broke) again with the same assets, map and Mods. As can be seen there is sparce traffic in the last 2 screenshots, and no trucks to be seen anywhere. 
> 
> https://steamcommunity.com/sharedfiles/filedetails/?id=1699536372 
> https://steamcommunity.com/sharedfiles/filedetails/?id=1699537378 
> https://steamcommunity.com/sharedfiles/filedetails/?id=1699537904 
> https://steamcommunity.com/sharedfiles/filedetails/?id=1699538467 
> https://steamcommunity.com/sharedfiles/filedetails/?id=1699539020 

> Based on that exercise, I don't conclude that there is a mod issue, but rather something in the update broke the traffic and it has not comeback. I've been in this holding pattern now for days, I'd like to get back to gameplay on the map. Here is a fresh game save **(see save v2)**

> I tried a couple more things this morning, using the lab version vs the stable version, no change. Then I dismantled outside connections, with the hope of getting back to a Vanilla traffic on the highways situation or at least finding a connection that might be an issue, no change. I also went down through the broken mods list again to see if there was a issue there, couldn't find any.

**Comment by RayPov** [comment]
[output_log.txt](https://github.com/krzychu124/Cities-Skylines-Traffic-Manager-President-Edition/files/3045829/output_log.txt)

**Comment by aubergine10** [comment]
Thanks for the log.

Mods subscribed:

```
The following mods were used when this asset was created: 
UnlimitedMoney
UnlimitedOilAndOre
UnlimitedSoil
UnlockAll
922939393
515489008
412146081
588691634
409776678
895061550
420500168
793176674
552324460
724382534
774449380
1349895184
1274199764
928128676
898480258
881291183
837734529
812713438
812107110
802066100
793346248
791221322
787611845
785528371
769744928
694512541
689937287
672248733
666425898
651322972
625608461
593588108
586012417
547533304
530871278
530771650
523824395
523818382
518456166
502750307
463845891
445589127
954067599
458519223
650436109
407270433
405791507
411164732
714056356
820157360
795514116
572888650
650805785
1209581656
1388613752
816260433
1567569285
1586027591
833779378
812125426
767233815
763684437
576327847
543722850
505480567
466158459
667342976
924884948
1530376523
1597198847
417965096
639486063
1680642819
1591417160
1645781000
1619685021
556784825
583429740
  [Modding]
```

No idea what outputs this but glad it's there:
```
Enabled Plugins:
# Unlimited Money
# Unlimited Oil And Ore
# Unlimited Soil
# Unlock All
# Transparency LOD Fix + Cloud Assets Enabler
# Extra Train Station Tracks
# PostProcessFX
# Mods Listing
# Theme Decals
# One-Way Street Arrows
# Sharp Textures
# No Fires
# One-Way Train Tracks
# Catenary Replacer
# Tree LOD Fix
# Network Tiling
# Camera Positions Utility
# Ploppable Asphalt
# Find It! 1.5.4
# Dynamic Resolution
# Less Steam
# Fine Road Anarchy 1.3.5
# Decal Hover Area
# Prop Precision 1.0.1
# Prop Snapping
# Cinematic Camera Extended 0.5.1
# PollutionRemoverMod
# Prop Line Tool
# Surface Painter
# Ultimate Eyecandy 1.5.2
# Fine Road Tool 1.3.7
# Adaptive Prop Visibility Distance
# Prop & Tree Anarchy
# Ploppable RICO
# Remove Decoration Sprites
# Daylight Classic
# Prefab Hook
# Prop Remover
# Extra Landscaping Tools
# No Pillars
# Precision Engineering
# PropRotating Params
# Unlock All + Wonders & Landmarks
# Quay Anarchy
# Chirpy Exterminator
# Extended Public Transport UI
# Transport Line Rendering Fix
# Spawn Points Fix
# Train Converter
# Remove Need For Power Lines
# First Person Camera
# Relight
# Tree Movement Control
# Metro Overhaul
# Achieve It!
# Tiny Segments 2.0
# Loading Screen Mod [Test]
# Network Extensions 2
# Decal Prop Fix
# Roads United: North America PLUS
# 81 Tiles (Fixed for C:S 1.2+)
# Network Skins
# Building Themes
# Loading Screen Mod
# Plop The Growables
# Railway Replacer
# Segment Slope Smoother
# Better bulldoze Tool
# Automatic Bulldoze v2
# Ultimate Level Of Detail
# Hide It!
# Elektrix's Road Tools
# Move It 2.4.0
# Random Tree Rotation

Loaded Themes:
# I-Agriculture District Style by Luurt
# American 1900 Low Density Commercial
# Detached 3 X 3
# Barbados
# Smuglers
# shacks
# Orangeberg
# NEW YORK
# Jersey Heights
# Cranston
# Rail
# INDUSTRY
# Sutter
# Finnish
# forest
# test
# chalet
# European
# International
```

Exceptions / Errors:

```
PollutionRemoverMod: XLoad error #0: Could not find file "C:\Users\RPovi\AppData\LocalLow\Colossal Order\Cities_ Skylines\PollutionRemoverMod.xml".:    at KUDr.PollutionRemoverMod.misc.Log.Warning(System.String s, Boolean close)
   at KUDr.PollutionRemoverMod.settings.ModSettings.XLoad()
   at KUDr.PollutionRemoverMod.settings.ModSettings.LoadFromFile()
   at KUDr.PollutionRemoverMod.Mod.OnSettingsUI(UIHelperBase root)
   at System.Reflection.MonoMethod.InternalInvoke(System.Object , System.Object[] , System.Exception ByRef )
   at System.Reflection.MonoMethod.Invoke(System.Object obj, BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture)
   at System.Reflection.MethodBase.Invoke(System.Object obj, System.Object[] parameters)
   at OptionsMainPanel.AddUserMods()
   at OptionsMainPanel.CreateCategories()
   at OptionsMainPanel.Awake()
   at UnityEngine.Object.Internal_CloneSingle(UnityEngine.Object )
   at UnityEngine.Object.Instantiate(UnityEngine.GameObject original)
   at ColossalFramework.UI.UIDynamicPanels.Init(ColossalFramework.UI.UIView view)
   at ColossalFramework.UI.UIView.Awake()
```

x 2:
```
NullReferenceException: Object reference not set to an instance of an object
  at PrefabCollection`1[PropInfo].InitializePrefabs (System.String collection, .PropInfo[] prefabs, System.String[] replaces) [0x00000] in <filename unknown>:0 
  at PropCollection+<InitializePrefabs>c__Iterator0.MoveNext () [0x00000] in <filename unknown>:0 
  at LoadingManager.Update () [0x00000] in <filename unknown>:0 
```

Some assets missing from clus LRT networks:
```
[LSM] Asset missing: 1558488647.LRT Traffic Light_Data
[LSM] Asset missing: 1558488647.Pedestrian Traffic Light LRT_Data
[LSM] Asset missing: 1558488647.Slope Light LRT_Data
[LSM] Asset missing: 1558488647.Catenary Mast Single LRT_Data
[LSM] Asset missing: 1558488647.Warning Signal LRT_Data
[LSM] Asset missing: 1558488647.LRT Swell_Data
```

```
PollutionRemoverMod: XLoad error #0: Could not find file "C:\Users\RPovi\AppData\LocalLow\Colossal Order\Cities_ Skylines\PollutionRemoverMod.xml".:    at KUDr.PollutionRemoverMod.misc.Log.Warning(System.String s, Boolean close)
   at KUDr.PollutionRemoverMod.settings.ModSettings.XLoad()
   at KUDr.PollutionRemoverMod.settings.ModSettings.LoadFromFile()
   at KUDr.PollutionRemoverMod.Mod.OnSettingsUI(UIHelperBase root)
   at System.Reflection.MonoMethod.InternalInvoke(System.Object , System.Object[] , System.Exception ByRef )
   at System.Reflection.MonoMethod.Invoke(System.Object obj, BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture)
   at System.Reflection.MethodBase.Invoke(System.Object obj, System.Object[] parameters)
   at OptionsMainPanel.AddUserMods()
   at OptionsMainPanel.CreateCategories()
   at OptionsMainPanel.Awake()
   at UnityEngine.Object.Internal_CloneSingle(UnityEngine.Object )
   at UnityEngine.Object.Instantiate(UnityEngine.GameObject original)
   at ColossalFramework.UI.UIDynamicPanels.Init(ColossalFramework.UI.UIView view)
   at ColossalFramework.UI.UIView.Awake()
```

```
System.TypeInitializationException: An exception was thrown by the type initializer for Mono.CSharp.CSharpCodeCompiler ---> System.IO.FileNotFoundException: Windows mono path not found: C:\Program Files (x86)\Steam\steamapps\mono\mono\mini\mono.exe
  at Mono.CSharp.CSharpCodeCompiler..cctor () [0x00000] in <filename unknown>:0 
  --- End of inner exception stack trace ---
  at Microsoft.CSharp.CSharpCodeProvider.CreateCompiler () [0x00000] in <filename unknown>:0 
  at System.Xml.Serialization.XmlSerializer.GenerateSerializers (System.Xml.Serialization.GenerationBatch batch, System.CodeDom.Compiler.CompilerParameters cp) [0x00000] in <filename unknown>:0 
  at System.Xml.Serialization.XmlSerializer.RunSerializerGeneration (System.Object obj) [0x00000] in <filename unknown>:0 
```

From vague memory this next error can be caused if a RICO asset contains props from a DLC that isn't installed:
```
NullReferenceException: Object reference not set to an instance of an object
  at ToolBase.OnEnable () [0x00000] in <filename unknown>:0 
UnityEngine.GameObject:Internal_AddComponentWithType(Type)
UnityEngine.GameObject:AddComponent(Type)
UnityEngine.GameObject:AddComponent()
PloppableRICO.PloppableTool:Initialize()
PloppableRICO.Loading:OnLevelLoaded(LoadMode)
LoadingWrapper:OnLevelLoaded(UpdateMode)
<LoadLevelComplete>c__Iterator9:MoveNext()
LoadingManager:Update()
```

```
System.TypeInitializationException: An exception was thrown by the type initializer for Mono.CSharp.CSharpCodeCompiler ---> System.IO.FileNotFoundException: Windows mono path not found: C:\Program Files (x86)\Steam\steamapps\mono\mono\mini\mono.exe
  at Mono.CSharp.CSharpCodeCompiler..cctor () [0x00000] in <filename unknown>:0 
  --- End of inner exception stack trace ---
  at Microsoft.CSharp.CSharpCodeProvider.CreateCompiler () [0x00000] in <filename unknown>:0 
  at System.Xml.Serialization.XmlSerializer.GenerateSerializers (System.Xml.Serialization.GenerationBatch batch, System.CodeDom.Compiler.CompilerParameters cp) [0x00000] in <filename unknown>:0 
  at System.Xml.Serialization.XmlSerializer.RunSerializerGeneration (System.Object obj) [0x00000] in <filename unknown>:0 
GENERATEGROUPPANEL FindItPanel
```

Lots of "Hide It!" exceptions - normal, doesn't break anything. Not listing them here.

```
NullReferenceException: Object reference not set to an instance of an object
  at ToolBase.OnDisable () [0x00000] in <filename unknown>:0 
```

```
PollutionRemoverMod: XLoad error #0: Could not find file "C:\Users\RPovi\AppData\LocalLow\Colossal Order\Cities_ Skylines\PollutionRemoverMod.xml".:    at KUDr.PollutionRemoverMod.misc.Log.Warning(System.String s, Boolean close)
   at KUDr.PollutionRemoverMod.settings.ModSettings.XLoad()
   at KUDr.PollutionRemoverMod.settings.ModSettings.LoadFromFile()
   at KUDr.PollutionRemoverMod.Mod.OnSettingsUI(UIHelperBase root)
   at System.Reflection.MonoMethod.InternalInvoke(System.Object , System.Object[] , System.Exception ByRef )
   at System.Reflection.MonoMethod.Invoke(System.Object obj, BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture)
   at System.Reflection.MethodBase.Invoke(System.Object obj, System.Object[] parameters)
   at OptionsMainPanel.AddUserMods()
   at OptionsMainPanel.CreateCategories()
   at OptionsMainPanel.Awake()
   at UnityEngine.Object.Internal_CloneSingle(UnityEngine.Object )
   at UnityEngine.Object.Instantiate(UnityEngine.GameObject original)
   at ColossalFramework.UI.UIDynamicPanels.Init(ColossalFramework.UI.UIView view)
   at ColossalFramework.UI.UIView.Awake()
```

**Comment by aubergine10** [comment]
Mod 411164732 - Extended Public Transport UI is obsolete.

If using "Hide It" mod, the "Chirpy Exterminator" mod is not required (as Hide It can hide Chirpy).

**Comment by RayPov** [comment]
I was able to cleanup several of the issues in the output log,  might be able to fix a couple more.   Moist likely the Rico issue stems from Industries DLC being turned off.

I guess at this point were you able to see the no trucks spawn issue?   If so is there a fix?

TY for all the work on this

Ray

**Comment by aubergine10** [comment]
I was trying to get the save up and running last night but the game kept crashing to desktop, with nothing in the log file or even the usual "application crashed" dialog in Windows. Now I've had some sleep on it, I think it might be because I was running a dev build of TMPE so going to try with the normal workshop version.

**Comment by RayPov** [comment]
Ok,  no issue loading any of those maps,   Wondering if it can be fixed will I need back to that map,  or will the map save I currently am on will automatically be fixed

**Comment by aubergine10** [comment]
Managed to get the save loading but still not operable (missing assets or something) but at least making progress.

**Comment by RayPov** [comment]
well that is good news,   something just sounds buggy here,   my load is usually about 6 mins or less and no notifications when it opens.

**Comment by RayPov** [comment]
I'm in the game now,  if you want to just go to watch mode let me know

**Comment by aubergine10** [comment]
@FireController1847 this is the savegame I was mentioning in dev chat

**Comment by RayPov** [comment]
Were you able to get in and see the issue?

**Comment by FireController1847** [comment]
@RayPov Apologies for my late response. I'm currently downloading your assets and I'll be seeing if I can get the savegame to load soon.

**Comment by FireController1847** [comment]
@RayPov Ok, just for fun, let's start from the basics. If you disable TM:PE and then do your repduction steps, is the issue still apparent?

**Comment by RayPov** [comment]
Hi Fire Controller,  on several occasions I have disabled via turning off or subscribe the TM mod.  Even given ample time for the spawn to restart it does not.   The behavior of no trucks and light traffic persists as with the Mod turned on.


I will try it again though now.

**Comment by RayPov** [comment]
I did go back and remove TM and then reinstall and saw the same behavior, no trucks and light traffic of cars

I went back to an old save on this map, perhaps something around 3/20/2019 and that save does have truck traffic and imports and exports. My recollection is this save predated the TM update.

**Comment by FireController1847** [comment]
@RayPov Okay, that's very odd. Can I ask you to disable ALL assets and mods except TM:PE, and then do your reproducibility instructions? I'm curious to see if this is caused by TM:PE itself, or if it's cause by a conflict with an asset or a mod. Also, if the issue persists on this map, can you please send it here? Thanks in advance.

**Comment by RayPov** [comment]
Hi, Firecontroller, respectfully I'm going to decline Mods and asset removal as I've already done that in the past. I used to lead Platform development and Delivery at a major US corporation. My background is Mechanical Engineering, but I had to also manage Software and Firmware to deliver platform and individual products. My person opinion in trying to half split this problem is that your not looking at the facts and data in the right system orientation.

Lets start with what we know:

The Map had no issues with the set of Mods and Options pre update, that is conformed by the pre update save not showing any issue with Truck Spawn, things are working as intended.

Immediately when the update came out it broke my Map (no truck traffic) and the workarounds suggested did not correct the issue. Despite numerous this and thats it remains broke almost 2 weeks later.

Subsequent new game loads of both the current map and another map show no issues with Truck Spawn and the proper delivery of the supply chain. This has been validated 3 times.

I'm left at this point with the following conclusion that the map was corrupted in some way or changed based on the update, and this fishing expedition with Mods or Assets isn't the real root cause. The problem lies in the map itself. I'll be polite, but you could probably understand what my reaction would have been back in the workplace. The rollout doesn't meet any expectation that I would have set forth as part of our software release validation and quality process. Putting out broken upgrades and patches that aren't sufficiently validated, and tested under operating conditions negates the positive effect of adding entertainment and capability to the game. Additionally it destroys credibility. I've found in various games and game companies this happens far too much, this game has had far to many of these types of situations.

Is there a quick fix or any fix to this at all, I'm tired of waiting. This has gone on far too long?

**Comment by RayPov** [comment]
Here are a couple saves:

A quick test I did this morning plopping roads and zoning to see if Truck traffic would be normal, it was

https://steamcommunity.com/sharedfiles/filedetails/?id=1705418677&searchtext=corktest

The current map, no notifications or issues, but no truck traffic

https://steamcommunity.com/sharedfiles/filedetails/?id=1705446752&searchtext=cranston6

A couple SS's of the cork test map showing truck traffic

https://steamcommunity.com/sharedfiles/filedetails/?id=1705461008

https://steamcommunity.com/sharedfiles/filedetails/?id=1705461915

**Comment by FireController1847** [comment]
@RayPov My apologies for your frustrations. You must understand that we must resolve issues under the impression the user knows nothing about debugging and/or the internal workings of Cities: Skylines.

I seem to be misunderstanding something, as I have not seen the conversations between you and aubergine10. What is this "update" you're talking about? A Cities: Skylines update (1.11 or something), a TM:PE update (10.18), or a different mod's update?

**Comment by aubergine10** [comment]
It was the 10.17 or 10.18 update.

There is something broken in the specific savegame.

Other users who had problems with industry traffic reported that the 10.17 or 10.18 update fixed their problems, but on this one specific save game the problems persist.

I'd directed RayPov to the standard [troubleshooting guide](https://github.com/krzychu124/Cities-Skylines-Traffic-Manager-President-Edition/wiki/Vehicles-not-spawning) for these sorts of issues, so assume things like vehicle restrictions, lane connections, speed limits, known problem mod, etc., were all reviewed.

Hence me asking for a fresh set of eyes to look at the save because I'm somewhat stumped.

----

@RayPov Respectfully, we are all volunteers, not a corporation. We are doing this in our spare time, with reverse-engineered code from a game we did not create and a mod that has been through multiple developers and contributors over 5 years. The recent updates were tested prior to release, by myself and others (usually Krzuchu and Victor aka LinuxFan) but it is near impossible to test every feature of the mod for the huge array of transport network situations that our >800k users have created in often highly modded games.

Since recently forming an ad-hoc team to work on the mod (both developers and support) we have done a lot to improve code quality, build process, CI, pull reviews, etc., and that work is still ongoing. We are actually currently refactoring the entire codebase ( see https://github.com/krzychu124/Cities-Skylines-Traffic-Manager-President-Edition/pull/260/files ) to make it faster, more maintainable, more reliable and also facilitate addition of a formal unit test framework to further enhance our CI system for pull requests. This all takes staggering amounts of time. So, please be a little patient with us :)

Currently you are the _only person_ who has reported this specific bug to us; all other users (about 80 or so via Steam, Dischord, IM, reddit, GitHub, etc) who had the earlier issues with industry traffic have reported the bug fixed for them.

I've still been chipping away at getting your save running on my PC, and now the roads are appearing properly, etc., however it's "stuck" when loaded (almost like it's paused, but no way to unpause it) so I'm still trying to work out what that problem is.

I have also been thinking of possible ways to recover the content of your save should we fail to revive it. For example, the Move It mod has a "save / load" feature - you can drag-select a bunch of stuff on the map and then save it to disk, then load it in to an earlier savegame. This way you could potentially recover any roads or detailing that took ages to do (I personally can spend days working on a highway junction or farming village or whatever so I know how bad it is to lose such work).

**Comment by RayPov** [comment]
Please excuse my frustration and lack of a usual profession response, the volunteers that contribute so much time deserve only prase, as is anybody working to improve the base code and the release process.

Part of my frustration arises from the fact that this now the third occasion where a map has been corrupted in some way causing a substantial loss of work.

The fact that the map loads without issue on my device, and doesn't on others gives me great pause, as it indicates another level of inconsistency which is beyond the problem I have been reported with the spawn. I don't see an obvious connection between that issue, and the loading issue, and doesn't bolster any confidence that the game stability needed to undertake a major project isn't being impacted by something else. While I have checked validity of game files many times, they always pass. I'm now curious if the save game I did this morning on the cork test map will even load. Something just seems terribly amiss with the over behaviors being seen.

Ray

**Comment by FireController1847** [comment]
@RayPov @krzychu124 appears to have been able to load your save -- albeit with a 50 GB swap file. I'll pass this issue over to him and when he gets the time/chance he'll respond back to you :)

**Comment by aubergine10** [comment]
Images from dev chat.

![limit](https://user-images.githubusercontent.com/1386719/55678951-75a00380-58fa-11e9-81b2-efeb16593a41.jpg)

![industry](https://user-images.githubusercontent.com/1386719/55678959-9a947680-58fa-11e9-9ea7-d2ec0a0d66a9.jpg)

**Comment by aubergine10** [comment]
@RayPov Can you try the "Despawn all vehicles" button - see if if flushes out the broken vehicle instances. (Vehicles should gradually respawn afterwards)

**Comment by krzychu124** [comment]
I am surprised that I managed to load your save 2.5k mods which is about 5k assets. It took me around 20 minutes to load that savegame and ate 50GB of swap space + ~5GB RAM(game itself). I've seen maps with more than 100k population (even 400k) an there were no issue with trucks... 
Little explanation: game itself has an unmodifiable limit of available vehicle instances to spawn, which is 16384. It's impossible to increase that limit because whole codebase of game is made around that value (all operations, loops on vehicles are using this value as max) As you can see on screenshot m_vehicleCount represents your actual number of spawned vehicles (constantly jumping from that value up to the max) I didn't tried clearing all traffic but it should help for some time. 
Second screenshot shows zones you've set up. I am curious, are those blank spots are intentionally there or something didn't load properly? 
Do you have any mod that favour private cars over walking/using public transport because mod tools shows only 5k active citizen instances in use of 64k max available to spawn?

**Comment by RayPov** [comment]
GM, sorry there will be a couple of responses, thank you all for your efforts on educating and helping to resolve this issue.


I haven't really focused on Asset total,I don't really have a loading issue and performance issue (Loading MOD report shows a load time of 6.3 minutes),  I have no lag etc.   I haven't really made a big effort to reduce the total number. In the last two weeks I have spent considerable time with collections and such to be able to reduce the total number of assets, but haven't done anything given wanting to keep this current map at the state it has been at with the issue. Given the loading report do you see a big need to reduce the asset total?


I don't follow the blank spaces part, If you refer to the blank spots in the cities a couple of reasons possible. Map is work in process, and have removed as many commercial assets as possible due to spawn and supply issues. I play with abandonment allowed and auto bulldozer. So if they abandon and don't respawn they remain blank until they do.


I have nothing that influences a policy of favoring this or that,  in your case walking vs driving


I see the vehicle count of 16380,  but I think that is very high for a city of this size.   I'm not doing anything I could guess at as to why there are so many vehicle count.   As referenced I know of cities that have many times this population and don't have this issue?   What do I need to do to get that under control?

**Comment by RayPov** [comment]
I just hit the clear traffic button, and by some magic traffic has flooded the highways, and trucks have appeared.  As can be seen by the imports they are around 1400 and the supply chain is again working.

https://steamcommunity.com/sharedfiles/filedetails/?id=1705962830
https://steamcommunity.com/sharedfiles/filedetails/?id=1705945890
https://steamcommunity.com/sharedfiles/filedetails/?id=1705965526

While I'm very happy and thankful that the traffic has reappeared I'm kind of not getting the whole thing?   It was this simple to restore traffic and I wonder if this is a just a temporary thing?

**Comment by aubergine10** [comment]
It's going to take some time, but it seems something (possibly TMPE or some other mod) has caused a load of phantom vehicles to get 'stuck' in that savegame, eating up the vehicle limit. We currently have no idea what could cause such a thing; I personally haven't seen anything like that in the 5+ years since the game was launched, even back in the Traffic++ days. There were some 'stuck traffic' issues in the past, but usually only affected like 1 or 2 vehicles. In your case it seems to have affected 16380 vehicles, which is unheard of.

In respect to why it was only affecting trucks, there's a somewhat dynamic priority in what categories of vehicles get spawned at any given time; services were higher than trucks in the pecking order, and with only 4 vehicle spots available trucks didn't get a chance to spawn.

There are a few additional despawn features in the TMPE mod options on the maintenance tab. Use those to ensure there's no other 'stuck stuff' on the map, and then see how things go for the next few weeks. With the blockage cleared it should be fine from now on.

As we've not seen this issue reported by anyone else, it's likely just a one-off - however, if you notice the problem recurring please let us know. It would be appreciated if you could keep those save games in the workshop - they will be vital for investigations should the problem arise again.

Right, I'm off to add "Try the despawn tool" to all our troubleshooting guides :)

**Comment by RayPov** [comment]
Having done a lot of this type is stuff,  there are many issues with the overall game architecture.   To fix those would require a rewrite and it’s not clear if Paragon is of a mindset to take on that investment,  or just mine the end of life of the game.

Commend you guys for working on improvements.

Ray

**Comment by aubergine10** [comment]
Hi,

A while ago we were looking at one of your C:SL save games in a TM:PE support ticket. We noticed that there was an issue with vehicle limit and have since identified some broken vehicle assets that cause that problem.

A list of the broken vehicles can be found in TM:PE wiki here: https://github.com/krzychu124/Cities-Skylines-Traffic-Manager-President-Edition/wiki/Broken-Vehicle-Assets#breaks-vehicle-spawning

If you encounter vehicle limit issues on small/medium cities, unsubscribe those vehicles if you have them, or use the TM:PE 'despawn' features to clear all vehicles as a quick fix whenever required.

**Comment by RayPov** [comment]
Thank you for the info,   BTW I sent you a friend invite awhile back.    I think we could share conversations about aspects of the game we both are interested in.


Regarding another post you made to me regarding custom screen shots I have watched the video several times.   The situation I ma trying to do I think is different, so let me explain.


I export my screen shots to Adobe Lightroom, where I post process them and then save them back into my screen shot file.   This is the Pathway where they endup:


C: > User > RPovio > App Data > Local > Colossal Order > Screenshots


They endup in that folder, and as you can see in the attachments Screenshots 280, 275, 274,279 are examples of Photoshopped images.  From there I can upload into Artwork.


What I want to do is get them into my screenshot Library and you can see for the Folder attachment they aren't there, only the PNG files saved from the game.   I'd like to get the post proccesed files into my screen shot library.


I'm wondering if my save from Lightroom isn't going to the proper destination file, so they will mere into my game screenshot file?


Thanks for any advise


Ray

**Comment by aubergine10** [comment]
I'm not sure what needs to be done to get them in to screenshot library; a few years ago when I was using Mac I had to ensure that the file naming between thumbnails and images was consistent, and also from vague memory the file format and dimensions of the thumbnails and images were important (I have vague recollection of major nightmares caused by cropping images for example). You'll have to do some googling as I've not tried doing custom screenshots for ages so don't know if anything is different now.
