### ISSUE TITLE
Toll Booth Issue - cars drive slowly through and don't pay

### ISSUE THREAD

**Issue by SirKroitz** [krzychu124/Cities-Skylines-Traffic-Manager-President-Edition#269]
Here is my output log: https://drive.google.com/open?id=1TudSzXD9I3m6Hm7B-jkasO0IBvXfXFFE

Here's my savegame: https://steamcommunity.com/sharedfiles/filedetails/?id=1703895466

in cas0e you need something else, please contact me - since i have no idea what you probably need :)

**Comment by FireController1847** [comment]
Okay, this is good and all, but what is the actual issue? Can you describe it for us?

**Comment by aubergine10** [comment]
> Hy :) Will there be a fix for the toll booth issue? (cars are going through them slowly but noone pays)

**Comment by FireController1847** [comment]
I haven't experienced this issue; people are paying at my toll booths. What is the reproducibility of this issue?

**Comment by SirKroitz** [comment]
@FireController1847 I'm building a system of cities and small villages on an island map, completely with Ploppable RICO and stuff. And for reasons of cashflow and authenticity i wanted to put some toll booths along my small highway. I placed them and connected them to electricity and water and did a bit for traffic flow (like going from 90km/h to 20km/h is a bit crazy) and realized that the cars dont actually hold and pay the toll, so I asked google about it and found a lot of more or less actual threads saying TM:PE is crashing the toll system - so I asked on the TM:PE workshop site about it

**Comment by aubergine10** [comment]
TMPE did have a bug that caused cars not to pay, however that was fixed in v1.10.14

@FireController1847 Can you test the savegame to check? I'm busy with # 267 at the moment.

**Comment by SirKroitz** [comment]
In that case I hope you guys dont need all the stuff that is used inside my savegame - there is literally nothing vanilla :S

**Comment by FireController1847** [comment]
@SirKroitz That's very odd and definitely shouldn't be happening.

@aubergine10 I'll take a look at it about an hour from now and report back here :)

**Comment by FireController1847** [comment]
@SirKroitz Do you mind listing all the mods you have? Assets shouldn't matter afaik, it's just the mods that would prevent it from loading.

**Comment by SirKroitz** [comment]
@FireController1847 this might take a second, hang on, i'll list it here

**Comment by SirKroitz** [comment]
81 Tiles
Adaptive Prop Visibility Distance
Additive Shader
Advanced Buildings Editor
Advanced Stop Selection
Advanced Toolbar
Advanced Vehicle Options 1.8.5
Ambient Sounds Tuner
American Roadsigns 2.2.0
American Traffic Lights
AnimUV Params
AST: KRA Sound Pack
Bee's North American Sound Pack
Better Cemetery AI
Building Themes
Cargo Info
Catenary Replacer
Clouds & Fog Toggler
Control Building Level Up
CrossTheLine
Cubemap Replacer
Daylight Classic
Decal Prop Fix
Elektix's Road Tools
Elevated Stops Enabler
Emergency Lights Changer Plus
EuropeanBuildingsUnlocker
Extra Landscaping Tools
Extra Train Station Tracks
Extra Vehicle Effects
Find it! 1.5.4
Fine Road Anarchy 1.3.5
Fine Road Tool 1.3.7
Forest Brush
Klyte Commons 1.1.6
Loading Screen Mod
Metro Overhaul Mod
More Beautification
More Diverse Crowd
More Train Tracks
Move it 2.4.0
Network Extensions 2
Network Skins
Network Tiling
New American Traffic Lights
No Pillars
NotSoUniqueBuildings
One-Way Train Tracks
Painter
Pedestrian Crossings
Plop The Growables
Ploppable Asphalt
Ploppable RICO
PostProcessFX
Precision Engineering
Prefab Hook
Procedural Objects 1.5.5
Prop & Tree Anarchy
Prop Line Tool
Prop Precision 1.0.1
Quay Anarchy
Random Train Trailers 2.1.0
Random Tree Rotation
Real Time
Realistic Walking Speed
Rebalanced Industries
Road Colors Changer ++
Roads United Core +
Roads United: US Edition
Rotors FlipXZ
Services Vehicles Manager 2
Sharp Junction ANgles
Sharp Textures
Show It!
SingleTrainTrackAI
Spawn Points Fix
Speed Slider
Sub-Buildings Enabler
Surface Painter
Terraform Tool
Ticket Price Costumizer
TM:PE 10.18
ToggleableWhiteness
Trailer Variation Loader
Tram Station Track
Transport Lines Manager 11.1.2
Tree Fire Control 
Unlimited Trees Mod
Vehicle Effects 1.8.1a
Vehicle Unbuncher
Vehicle Wealthizer 1

Ready to melt down your PC? :D
i activated all of the "vanilla" mods too except for the Hard-mode

**Comment by SirKroitz** [comment]
oh, by the way, maybe there is no placed toll booth in the savegame, i think i deleted them since they didnt work, i hope thats no issue

**Comment by FireController1847** [comment]
@SirKroitz If possible, while I try and get this savegame to work, can you try something for me?

Can you go through every vehicle, transport, and road-related mod (excluding NeXT and other assets) and disable them, then see if that fixes the issue?

**Comment by SirKroitz** [comment]
i'll try my very best :)

**Comment by SirKroitz** [comment]
![20190405210101_1](https://user-images.githubusercontent.com/49315744/55650504-2f598000-57e6-11e9-9f26-e52cbc8a36cd.jpg)
after a few tries, still shows this. ("Außer Betrieb" = "Out of Order" although its connected to electricity and water / sewage)

**Comment by FireController1847** [comment]
Just to go back to the basics, if you disable TM:PE the toll both works find?

**Comment by SirKroitz** [comment]
SO. After disabling TM:PE nothing changed.
BUT i deleted the Roads Colour Changer ++ and the Roads United Core + with the US Roads. After placing a toll both, connecting it, waiting some in-game minutes - it finally works :) So its not an issue with TM:PE

**Comment by FireController1847** [comment]
Awesome! I'm glad we were able to figure it out.

**Comment by aubergine10** [comment]
Excellent! I'll make a note of that in our Troubleshooting guide!

**Comment by aubergine10** [comment]
Is this the Road Color Changer mod you refer to? 

https://steamcommunity.com/sharedfiles/filedetails/?id=932192868

**Comment by aubergine10** [comment]
Also, do you have link to the specific US Roads mod - there's several of them in the workshop and not sure which one you were using.

**Comment by SirKroitz** [comment]
@aubergine10 Yes it is and i mean this US Edition: https://steamcommunity.com/sharedfiles/filedetails/?id=726004927&searchtext=Roads+United+US+Edition

I want to thank you for helping me find the issue and I hope you can do something with the new information about this :)

**Comment by aubergine10** [comment]
Awesome, thanks!

Here's the troubleshooting guide for anyone else who has this problem:

https://github.com/krzychu124/Cities-Skylines-Traffic-Manager-President-Edition/wiki/Toll-Booths-not-working
