### ISSUE TITLE
ParkingAI tanks FPS

### ISSUE THREAD

**Issue by docssy** [krzychu124/Cities-Skylines-Traffic-Manager-President-Edition#280]
Situation - parking lots fill up (commercial), maybe 30K pop.

Appears to be a situation where once parking in an area fills ups - instead of quitting and resorting to a fail-safe such as teleportation, cars will endlessly continue to attempt to park. Also probably related to abandoned cars

Second - when adjusting roads near full parking lots, IT TAKES FOREVER to reallocate parked cars affected by the change

Its so bad that I've had to turn off Parking AI and stare at my barren parking lots.  /sadface

**Comment by FireController1847** [comment]
I'll test this as soon as I get the chance.

In the meantime, do you happen to know how _much_ of an FPS tank it causes? Does it go from 60fps to 30fps? 60fps to 5fps? 1fps? This might help me understand the severity of the situation.

Also, if I can't get the issue to reproduce, can you please let me know the specs of your computer? In particular, your RAM amount, your CPU, and your GPU (if you have one). Thanks!

**Comment by FireController1847** [comment]
I'm unable to reproduce the issue. One parking lot in my entire city, almost all buildings are full and no framerate drops with it enabled or disabled.

**Comment by aubergine10** [comment]
Related to #259 ?

**Comment by docssy** [comment]
I had maybe 6 or 7 (different sized) parking lots, designed in the general sense of serving a larger store (not RICO therefore it was a tourist building) alongside a heavy commercial/office district. Like absolutely not enough parking.

Maybe.... the code is bouncing between the lots....?

When it occurs, it will macro stutter. Not a few ms, but more like 1...2 seconds between frames, maybe a second of normal and again stutter..... repeat.

24GB, i73930, gtx970.

Honest, it might be the extreme memory load as well. I just had a crash running out of page file so.... /shrug

**Comment by docssy** [comment]
![20190411225111_1](https://user-images.githubusercontent.com/49499406/56009375-9a56fb00-5cad-11e9-855e-d0d34768ff37.jpg)

This was the problem area

**Comment by FireController1847** [comment]
Since this may be related to issue 259, would you please upload your output log? If you don't know how, you can find [instructions on how to here.](https://github.com/krzychu124/Cities-Skylines-Traffic-Manager-President-Edition/wiki/Share-your-Cities-Skylines-log-file)

Also, as related to that issue, when you click on any of the cars near the parking lot, does it have a similar behavior?

**Comment by docssy** [comment]
Sorry I may have... overwritten it with another city.
I'll turn ParkingAI back on and try again.

**Comment by FireController1847** [comment]
@docssy Do you have any status on whether or not the bug is still apparent?

**Comment by aubergine10** [comment]
I'm closing this issue as no response. 

TM:PE LABS 10.21.1, based on feedback from users, largely resolves the performance issues with Parking AI.

If you have any future problems please comment here or open new ticket.
