### ISSUE TITLE
Dialog to confirm delete of timed traffic light step

### ISSUE THREAD

**Issue by aubergine10** [krzychu124/Cities-Skylines-Traffic-Manager-President-Edition#283]
From user Domaldel in Discord chat:

> I'd love for a pop up window asking for confirmation before deleting steps in a timed traffic light that involves multiple junctions.
> Trying to coordinate 18 steps across 13 junctions involving trains (going through the city), cars and pedestrians is proving a bit of a pain when all of a sudden delete a step involving all 13 junctions...
> The third time that has happened in that one city alone by the way...
> In a single day...

> Deleting a step for a single junction is just fine.
> You can just recreate it.
> But when you have multiple that all involves several steps the numbers of junction states that you have to juggle just becomes too high to easily recreate.
> And I don't remember the details, but basically there's a situation where you click on one button and the delete button ends up in the same exact spot a moment afterwards, so you end up clicking on it without intending to.
> That's both issues that should be fixed asap in my view.
> What I assume is a relatively easy fix would be to simply add a extra step the process of deleting a steps for timed traffic lights.
> When there's more then one junction involved.
> A simple "Are you sure that you want to delete step (number) for this and all connected junctions?" "Yes" or "No".
> Move the "delete" code over to the "yes" button instead of the "delete" button itself, possibly adding something to transfer variables over, etc.

**Comment by krzychu124** [comment]
I will check tomorrow how its made and what can be done 😉 

BTW I think we have to think how to improve current or future UI/UX when it comes to managing connected traffic lights.

**Comment by aubergine10** [comment]
Yes, I find the whole UI for traffic lights to be difficult to ue. It's the only TMPE feature I don't use due to the UI (no offence to Victor for doing such a remarkable job on so many varied features). I already set out some vague ideas in #8, but it needs a lot more thought. Also related: #278.
