### ISSUE TITLE
Restricting Service Vehicles Causes Them Not To Dispatch

### ISSUE THREAD

**Issue by blaines** [krzychu124/Cities-Skylines-Traffic-Manager-President-Edition#296]
I've restricted service vehicles from crossing my city's bridges and entering highways. I've placed sufficient services in areas so dispatching vehicles shouldn't cause a problem. In reality though blocking service and emergency vehicles causes services to do nothing at all. No garbage collection, no firetrucks, etc...

Is this a known issue? In the past I've used other district service restriction mods which have worked well. I figured I'd give TM:PE a try at this as well.

Below I included a couple screenshots so you can see the vehicle restrictions I made, and also the failing services. Can contribute more information if needed.

<img width="1680" alt="Screen Shot 2019-04-26 at 8 36 15 PM" src="https://user-images.githubusercontent.com/47128/56844315-5f36f900-6863-11e9-97f2-4cc367052b22.png">
<img width="1680" alt="Screen Shot 2019-04-26 at 8 35 22 PM" src="https://user-images.githubusercontent.com/47128/56844316-5f36f900-6863-11e9-8a27-c4149d1a5497.png">

**Comment by aubergine10** [comment]
TM:PE uses the vanilla AI for services (some tweaks, but nothing too much), which just randomly grab an available vehicle and send it on its travels. When you add service restrictions as shown in your first screenshot, you add a massive penalty for any service vehicles wanting to travel those routes - in most cases the cumulative penalty will be too high and the pathfinder will reject the route. It's unlikely that we'll change that as there are plenty of other mods for controlling service coverage.

I use [Customize It!](https://steamcommunity.com/sharedfiles/filedetails/?id=1369729955) to tweak the service radius & vehicle count, and [District Service Limit 3.0](https://steamcommunity.com/sharedfiles/filedetails/?id=1181352643) to limit where on the map the building supports. That way I don't need to add many service vehicle restrictions on the roads.

> Note: For DSL 3.0, I only enable the first option in its mod options; the others tend to cause problems with the game mechanics or conflict with mods like Real Time.

**Comment by aubergine10** [comment]
**Addendum:**

The vehicle restrictions in TM:PE are designed more for keeping certain vehicles out of a specific lane (example: no heavy vehicles in inner lanes on highways) or a few specific segments (example: no trucks driving through residential areas). It's not designed for limiting service coverage to specific areas of the map.

I'll update the docs to make note of this.

**Comment by blaines** [comment]
Thanks for the clarification! It definitely helps understand the purpose of the feature and what it can/can't be used for.

**Comment by aubergine10** [comment]
Documentation updated, closing ticket.
