### ISSUE TITLE
Cars driving through timed traffic lights

### ISSUE THREAD

**Issue by aubergine10** [krzychu124/Cities-Skylines-Traffic-Manager-President-Edition#297]
> # Solution
>  
> If road segments are too short, it breaks the traffic lights. So make the road segments longer (either use Move It mod or just rebuild with longer roads) to fix the problem of cars ignoring traffic lights.

Summary: Vehicles driving through timed traffic lights

Screenshot: https://i.imgur.com/rwNqSwz.jpg 

Savegame: https://steamcommunity.com/sharedfiles/filedetails/?id=1726503145

> _Shadertheboi 19 hours ago_
> I just realized after the recent update, there is a minor bug in regards to the timed traffic lights. Not sure if any one of you out there also has this bug. 
>  
> https://i.imgur.com/rwNqSwz.jpg 
>  
> I have set the timed traffic light as so. However except for vehicles heading eastwards, the rest of the vehicles heading north, south and west, they do not follow the timed traffic script as I set. So if the lights are red and not in their favor, cims would still drive forward as if the lights are green in their favor.
>  
> This only happens to the roads heading north, south and west in this intersection, roads heading to the east works just fine.
>  
> Did I did something wrong or did I accidentally adjust some settings unknowingly?
Please advise. TIA!

> _aubergine18  [author] 12 hours ago_
> Is it just that one specific junction that's causing the problem? If so, could you share your save game [github.com] and we'll see if we can reproduce and fix the bug.
>  
> As an interim solution, try rebuilding the roads at the junction.

> _Shadertheboi 4 hours ago_
> https://steamcommunity.com/sharedfiles/filedetails/?id=1726503145 
>  
> yup i did rebuilt the roads, even removing roads from the intersection and combining them witjh the 2-way 4-lane avenues... however, still to no avail...

**Comment by krzychu124** [comment]
Regards to traffic lights I think that there is too short segment to properly detect traffic lights.

![Zrzut ekranu (173)](https://user-images.githubusercontent.com/19638970/56926034-0a001f00-6ad1-11e9-8411-1e5f03b0064d.png)
That little change, using `Move It` resolves the problem with ignoring traffic lights on this particular intersection 😃 

Additionally, incompatibles checker found one incompatible mod: Network Nodes Editor [Experimental] but I didn't checked what it does.


_Other unrelated things below 😄 :_

- much more interesting is the number of active citizen units  on screenshot below.

![strange](https://user-images.githubusercontent.com/19638970/56925999-f3f25e80-6ad0-11e9-8c87-774664e73fbb.gif)
 
How and why there are 114k units while there is only 35k population??

- other but not mentioned issue are floating/flying cars. I've seen that before when I've been trying to find why lane connections not working in savegame from #99

**Comment by aubergine10** [comment]
> Additionally, incompatibles checker found one incompatible mod: Network Nodes Editor [Experimental] but I didn't checked what it does.

It was an early attempt at something like Move It, but it NNE causes phantom nodes, segments, etc. (that screw up the pathfinder) which is why it's on the incompatible mods list.

> much more interesting is the number of active citizen units on screenshot below.

Lots of users have been reporting issues with this sort of thing in the main C:SL discussions section on Steam recently. I've followed a few discussions about the issue and it doesn't seem specific to TM:PE, so maybe it's some other mod causing it? Some users mentioned that a recent Steam update to C:SL seems to have caused it, I'm not sure if that is the vanilla game that got updated or a mod.

There is a possibility that it's stuck tourists, a bug recently discovered in vanilla game by @chronofanz - see #273. Try his [CrazyTouristsFix](https://steamcommunity.com/sharedfiles/filedetails/?id=1706337219) mod from Workshop to see if that reduces the citizen unit count.

> other but not mentioned issue are floating/flying cars

I think it was @DaEgi01 who was having a flying cars problem in the Discord chat (#issues room, complete with screenshots). He tested with and without TM:PE and found he had the same issue. So again, doesn't seem TM:PE related

**Comment by Shadertheboi** [comment]
thank you so much for your help!

**Comment by aubergine10** [comment]
Hi,

A while ago we were looking at one of your C:SL save games in a TM:PE support ticket. We noticed that there was an issue with vehicle limit and have since identified some broken vehicle assets that cause that problem.

A list of the broken vehicles can be found in TM:PE wiki here: https://github.com/krzychu124/Cities-Skylines-Traffic-Manager-President-Edition/wiki/Broken-Vehicle-Assets#breaks-vehicle-spawning

If you encounter vehicle limit issues on small/medium cities, unsubscribe those vehicles if you have them, or use the TM:PE 'despawn' features to clear all vehicles as a quick fix whenever required.

**Comment by Shadertheboi** [comment]
Alright! I will take a look at it. Thanks so much!

**Comment by s2500111** [comment]
Would definitely appreciate if this issue would be fixed, maybe by checking the next 2 nodes for traffic lights, so that 1 short segment isn't that big of a problem?

they do it in my city here, and I can't simply make the segments longer without fundamentally changing the looks of this intersection ...
https://youtu.be/rwXoJDRcZko

**Comment by s2500111** [comment]
Also has anyone an idea, why this is happening? Are cars simply ignoring the light? Or are they detecting the light only when they enter the segment and are not able to come to a stop at the light, so they overshoot it and enter the junction?

**Comment by krzychu124** [comment]
Yes, if vehicle will fail to stop before entering intersection then its flag is changed to 'leave junction'

**Comment by benrr101** [comment]
Just ran into this issue with my city and [Employee 432's diverging diamond interchange](https://steamcommunity.com/sharedfiles/filedetails/?id=853863115). I also noticed that if the traffic lights don't render because the segment is too short, the cars will ignore the signal as set up in TMPE.
