### ISSUE TITLE
Timed traffic lights pop-up panel empty

### ISSUE THREAD

**Issue by aubergine10** [krzychu124/Cities-Skylines-Traffic-Manager-President-Edition#301]
As [reported on Reddit](https://www.reddit.com/r/CitiesSkylines/comments/bjstvm/tmpe_overlay_blank/):

> TM:PE shows a blank overlay, but only with timed traffic lights. I tried reinstalling the mod, but no success.
>  
> CS runs on a Linux box if that's important.

![tmpe](https://user-images.githubusercontent.com/1386719/57107934-4332cc00-6d29-11e9-8c9f-12fcbdb261fa.png)

I've asked for log file and save game.

**Comment by aubergine10** [comment]
> **bogdan2011** 6 hours ago  
> Turns out I was missing some fonts. I'm not sure which because I simply switched the distro and now I can see the text. Any idea which fonts are used?

I'll add a troubleshooting guide.

**Comment by aubergine10** [comment]
From Krzychu: Fonts - mostly Open Sans

![fonts](https://user-images.githubusercontent.com/1386719/57154425-bd6a5b80-6dd0-11e9-8a1f-2519b58dc8e0.jpg)

**Comment by Endersirio** [comment]
Hello!

I have the same issue here, but unfortunately I'm on epic and I cannot find a working version of either of the mods.

**Comment by krzychu124** [comment]
> Hello!
> 
> I have the same issue here, but unfortunately I'm on epic and I cannot find a working version of either of the mods.

The issue was reported from Linux user. If you are on Windows or Mac it's not possible to happen unless you manually uninstalled the most basic fonts from the system. I doubt that was the case so make sure you are running the latest version of the game as well as the mod (11.8.0.0). If you don't know how to install it see [The Guide](https://github.com/CitiesSkylinesMods/TMPE/wiki/Installing-on-Epic-Games). It contains links are files you will need.

**Comment by Endersirio** [comment]
I'm on linux too, I managed to make it work without steam

**Comment by krzychu124** [comment]
Traffic lights UI, but also Vehicle restrictions panel is using default Unity engine font, which is **_Arial_**. Try installing it.
I haven't experienced any issues when I was testing in on Ubuntu or Manjaro some time ago, so you probably use a bit more custom distribution that is not shipped with that font.

**Comment by Endersirio** [comment]
It did not work, I installed all types of arial but none of them made a
difference
