### ISSUE TITLE
Traffic customisations lost (temporarily)

### ISSUE THREAD

**Issue by aubergine10** [krzychu124/Cities-Skylines-Traffic-Manager-President-Edition#306]
> # Solution
>  
> This is caused when you have multiple TM:PE mods subscribed. Ensure only one TM:PE is subscribed at a time, and fully unsubscribe the others then exit to desktop and relaunch the game.
>  
> For more info and related issues, see: [Customisations or settings lost](https://github.com/krzychu124/Cities-Skylines-Traffic-Manager-President-Edition/wiki/Customisations-or-settings-lost] in the troubleshooting guide

----

> Draithen 17 hours ago  
> Dear Admins, I've been experiencing a strange issue lately. Every time I load up a save, the mod forgets all the custom traffic rules I've set, eg. parking restrictions, vehicle restrictions, lane knitting.
> I did not have time to play for a month and I have left the game completely untouched for that time period. Now, coming back, I see this, without any apparent reason I can think of. I don't have an idea how to start troubleshooting, may I kindly ask for your assistance? Thanks in advance!

I asked for details of city:

> Draithen 7 hours ago 
> aubergine18 Thank you for your quick reply! The city I was playing is relatively small, 26,000 people. And I didn't have too much custom rules set up. However, the problem seems to be solved after an unsubscribe-resubscribe maneuver. Thanks for your support! :)

Asked for saves:

> aubergine18: I am keeping every save. I managed to locate the last good save file, and the next where everything was erased. See them here:
> https://steamcommunity.com/sharedfiles/filedetails/?id=1734277121 
> https://steamcommunity.com/sharedfiles/filedetails/?id=1734278224 
> After re-subscribing it works again:
> https://steamcommunity.com/sharedfiles/filedetails/?id=1734278876 
> (There is still a lot to be done, and I'm not a pro yet :)

So apparently resubscribing the mod (I assume) fixed it. Possibly a workshop issue, mod not enabled, or something?

**Comment by Xyrhenix** [comment]
This reminds me of issues I had. I had built my city with one version of TM:PE, and had kept it installed and subscribed (but not enabled) while I used another for unofficial bugfixes. As a result of having both installed, the save would constantly forget any TM:PE data until I unsubbed or removed one of the two.

**Comment by aubergine10** [comment]
Yup, I think that's what happened here; I've added a link to related troubleshooting guide to OP.

In any case the user fixed the issue they were having so closing issue.
