### ISSUE TITLE
Mail trucks ignoring lane arrows

### ISSUE THREAD

**Issue by aubergine10** [krzychu124/Cities-Skylines-Traffic-Manager-President-Edition#307]
From discord:

> Subaru Altraffioyne SVXYesterday at 23:35
> Are mail trucks also supposed to...
> Not follow the road signs at all?

later....

> Subaru Altraffioyne SVXToday at 05:33
> Well, it's more to do with the fact that when making roads that go straight when joining from highway to road, for some reason, the mail trucks (even when the lane arrows are set to all straight) turn around.

Log files:

* [TMPE.log](https://github.com/krzychu124/Cities-Skylines-Traffic-Manager-President-Edition/files/3151166/TMPE.1.log)
* [Player.log](https://github.com/krzychu124/Cities-Skylines-Traffic-Manager-President-Edition/files/3151167/Player.1.log)

Config:

* [TMPE_GlobalConfig.xml](https://pastebin.com/6q4USjq5)

Asked for save game.

I know that we added mail vans to the vehicle categories, which should cover everything? I still wonder if there are different vehicle classes for mail vans vs. mail lorries? Or maybe the lane arrows code isn't using the centralised vehicle category stuff?

**Comment by aubergine10** [comment]
Noticed this in the logs:

> Network Skins: Incorrect usedCount detected, should be 30 ([SegmentData] features: StreetLight, treeLeftPrefab: null, treeMiddlePrefab: null, treeRightPrefab: null, streetLightPrefab: StreetLamp01 1, usedCount: 28)

There are some other errors in the log but nothing notable.

**Comment by aubergine10** [comment]
Possible problem mods:

* [Vehicle Wealthalizer](https://steamcommunity.com/sharedfiles/filedetails/?id=1633580257) - just a random guess, never used this mod or encountered it before. Suggest disable and restart Cities.exe to see if anything changes.
* [Tiny Segments](https://steamcommunity.com/sharedfiles/filedetails/?id=1586027591) allows very short road segments to be created which is know to cause issues with traffic lights - might also cause issues with lane arrows/connectors?
* [Roundabout Builder](https://steamcommunity.com/sharedfiles/filedetails/?id=1625704117) - possible that roads created by this mod cause issues? For example, does it check min segment length, does it trigger any events that TMPE uses to update its internal caches?

Other mod issues (not related to issue in OP):

* [FPS Display](https://steamcommunity.com/sharedfiles/filedetails/?id=407683828) - this is throwing an error in to the log file, suggest using alternatives listed at top of [this guide](https://steamcommunity.com/sharedfiles/filedetails/?id=465790009).
* [Automatic Bulldoze v2](https://steamcommunity.com/sharedfiles/filedetails/?id=639486063) - glitchy, suggest use keallu's "Bulldoze It!" mod instead
* Old version of [Advanced Vehicle Options](https://steamcommunity.com/sharedfiles/filedetails/?id=442167376) - suggest use the Industries compatible version
* Old [Mod Achievement Enabler](https://steamcommunity.com/sharedfiles/filedetails/?id=407055819) - suggest more recent keallu's "Achieve It!" mod?
* [More Beautification](https://steamcommunity.com/sharedfiles/filedetails/?id=505480567) - resource hog and causes lag; suggest using "Find It!" mod instead

Random pondering: Would mods that hide lane arrows (Hide It, Road Options, etc) cause any problems? (I doubt it as they are just visual, but just in case....)

**Comment by aubergine10** [comment]
Save game: https://steamcommunity.com/sharedfiles/filedetails/?id=1692336050

**Comment by aubergine10** [comment]
Another report of this issue via Steam:

> Penguin 3 hours ago  
> Is it only me that experiences that post trucks aren't following the lane arrows? They use the left turning lane to turn right for example. Normal vehicles seem to follow them as they should.

It seems specific to post trucks and lane arrows. I've asked for save/log just in case it helps track down the issue.

**Comment by eudyptula** [comment]
Hey, here's my log file and save game. Playing with a lot of mods/assets, so attached the loading screen report also (had to rename it to .txt to keep GitHub happy).

The two trucks waiting for green light in the middle of the screenshot will turn right not long after the game is loaded. If you need more trucks, they usually come with the freight train.

Btw. they do respect the lane connector tool, I been using that as a quick fix for the worst of it. Just removed the lane connections for the show intersection and the trucks started to misbehave again shortly therafter. Also, might have seen this issue with garbage trucks too, but it's awhile ago so not entirely certain. That might just have been due to recent changes of the road layout.

Oh, and don't mind the city - was just fooling around with a one-tile city :P

[GridCity - TM:PE Post Truck Bug](https://steamcommunity.com/sharedfiles/filedetails/?id=1738392200)
[output_log.txt](https://github.com/krzychu124/Cities-Skylines-Traffic-Manager-President-Edition/files/3169182/output_log.txt)
[Gridcity - Post Bug - Assets Report-2019-05-11_16-48-05.txt](https://github.com/krzychu124/Cities-Skylines-Traffic-Manager-President-Edition/files/3169193/Gridcity.-.Post.Bug.-.Assets.Report-2019-05-11_16-48-05.txt)

Best Regards, Penguin

**Comment by eudyptula** [comment]
Here's a much better save game for you. Copied the TM:PE DLLs from the steam workshop folder to `steamapps\common\Cities_Skylines\Files\Mods\TLM` and started the game with `--noWorkshop`. As you see on the screenshot, blue post truck still makes a right turn, even though the arrow shows left only.

[https://steamcommunity.com/sharedfiles/filedetails/?id=1738473042](https://steamcommunity.com/sharedfiles/filedetails/?id=1738473042)

Btw. using the stable version of the mod.

**Comment by krzychu124** [comment]
Great, I will check what is going on there 😉

**Comment by krzychu124** [comment]
Ok. I can confirm that post trucks going right 😕

**Comment by RenaKunisaki** [comment]
The Roundabout Builder definitely has some glitches and doesn't enforce restrictions; it will happily plop a roundabout right through buildings and over water. Especially when making them very small I've seen it sometimes not connect the roads properly. Not sure if that's going on here?

**Comment by aubergine10** [comment]
Another report of this issue on Steam:

>ralfaltmann 10 minutes ago  
> One question: it seems that post transporters are ignoring the lane arrows. Is there anything special about post transporters?

**Comment by aubergine10** [comment]
Savegame for above:

> yes, the savegame can be found here:
> https://steamcommunity.com/sharedfiles/filedetails/?id=1749002396 
>  
> And here's a screenshot where you can see the issue: the truck comes from a lane with left-only arrow, but it's heading straight forward (the location is near the commercial area):
> https://steamcommunity.com/profiles/76561198059796181/screenshot/793109568944666567 
>  
> Please notify me when you've downloaded the savegame, I want to delete it afterwards.

I've mentioned it may be a while before we get chance to review the save game.

**Comment by VictorPhilipp** [comment]
Reason: PostVanAI implements its own `StartPathFind` method which is not overriden by TMPE.
