### ISSUE TITLE
Default maxWalking distance

### ISSUE THREAD

**Issue by Sipke82** [krzychu124/Cities-Skylines-Traffic-Manager-President-Edition#310]
I noticed that the default maximum walking distance is upped to 2500. (from 1000 according to eh wiki ( https://tmpe.viathinksoft.com/wiki/index.php?title=Global_configuration ))
Not sure if that is intentional....

**Comment by krzychu124** [comment]
That line was changed almost year ago 😉 https://github.com/krzychu124/Cities-Skylines-Traffic-Manager-President-Edition/commit/c1b43baa8266c78652a8c9496595de393241351a

**Comment by aubergine10** [comment]
When I get round to porting the docs over from old wiki I'll edit that.

**Comment by Sipke82** [comment]
This was changed so that cims walk in nature reserve parks i guess.... but would this also mean that cims are less inclined to use other forms of transportation and that they will just walk...

**Comment by aubergine10** [comment]
Walking tours is another reason it was increased I believe.

As for transport types, I think cims have preferences (and those preferences are sent to pathfinder) and in addition they factor in things like ticket prices and duration of journey.

**Comment by RenaKunisaki** [comment]
Is the max walking distance one global value for everyone? Would make more sense if eg seniors aren't willing to walk as far.

**Comment by aubergine10** [comment]
What units is the distance in? Meters or something else?

Someone was just asking on Steam and I was pointing to earlier research done by another user that was using "zoning units" (ie. size of zoning square), but that is likely wrong.

According to old wiki, the base game is using a value of 1000 (probably bigger with park life update to accommodate walking tours).

**Comment by aubergine10** [comment]
Docs updated (still WIP) https://github.com/krzychu124/Cities-Skylines-Traffic-Manager-President-Edition/wiki/Global-Configuration

**Comment by kvakvs** [comment]
Makes park scams possible where people are forced to walk through the park to get to work/from work. And where people are forced to leave metro via a park :) Not a problem, just seems to be related remotely.

**Comment by aubergine10** [comment]
@kvakvs Any idea what the units are for the setting? It's 2500, but 2500 _what_?

**Comment by kvakvs** [comment]
My very first guess is the world units, 1.0f = 1m.
