### ISSUE TITLE
Lane connector points disappear

### ISSUE THREAD

**Issue by 0livander** [krzychu124/Cities-Skylines-Traffic-Manager-President-Edition#313]
Hey everyone, 

first of all thx for keeping this mod allive!

I played arround 30 hours with it and then the bug appeared. 
Basicly the counterpoints (see in pics) of the lane connectors only appear when I klick on a vissible point. I can set the p up, the lane will be fixe but after let it go the point dissapears once again so I can't set it. 
**I think** the first time I encountered the bug there were no textures on two of the the "Three-lane roundabout road" mod  segments (one pictured as blue, the other was invisible; have no screenshots) so chances are thats the fault.  

As I said, for about 30h everthing went nice and easy but out of nowhere both of my safegames are hit with it. 

The Mods I had installed:
- pre installed "cheats" 
- Tree brush 
https://steamcommunity.com/sharedfiles/filedetails/?id=406723376&searchtext=tree+brush
- Three-lane roundabout road 
https://steamcommunity.com/sharedfiles/filedetails/?id=1719918737&searchtext=three-lane+roundabout
- Small three Lane Roundabout 
https://steamcommunity.com/sharedfiles/filedetails/?id=427484223&searchtext=three-lane+roundabout
- Three lane one way 
https://steamcommunity.com/sharedfiles/filedetails/?id=1265034299&searchtext=three+lanes+one+way
- Improved Public Transport 2 
https://steamcommunity.com/sharedfiles/filedetails/?id=928128676&searchtext=Improved+Public+transport+2
- Automatic Bulldoze v2 
https://steamcommunity.com/sharedfiles/filedetails/?id=639486063&searchtext=automatic+bulldoze

The steps I took since:
- Tested with other savegames at different locations, road types
- Reinstalled the game without unsubscribing mods
- Reinstalled the game with un- and resubscribing all mods
- Reinstalled the game with only TM:PE 10.18 (tried .19, too) subscribed, the pre installed ones  inactive and a new savegame.

The system runs with Win10 pro 64 on a Z270 i5 7600k, a gtx1080ti, 16Gb ramm and with the latest drivers (if that plays a role).

![Kreuzung 1   1](https://user-images.githubusercontent.com/50545902/57583469-39e7f300-74d1-11e9-90cf-212f9dda40eb.jpg)
![Kreuzung 1   2](https://user-images.githubusercontent.com/50545902/57583470-39e7f300-74d1-11e9-84ca-f0a4656b51a3.jpg)
![Kreuzung 1   3](https://user-images.githubusercontent.com/50545902/57583472-39e7f300-74d1-11e9-81c9-21b6df965c51.jpg)
![Kreuzung 1   4](https://user-images.githubusercontent.com/50545902/57583473-39e7f300-74d1-11e9-8a8a-25ba7bf40dd6.jpg)
![Kreuzung 2   1](https://user-images.githubusercontent.com/50545902/57583494-3fddd400-74d1-11e9-8e37-b3482dd1331f.jpg)
![Kreuzung 2   2](https://user-images.githubusercontent.com/50545902/57583495-40766a80-74d1-11e9-9bcd-c0c25c2a14ef.jpg)

I'll hope to answer any upcoming questions,
greets

**Comment by krzychu124** [comment]
I am not sure if I understand everything but I don't see any bug on your screenshots.

When you want to connect two lanes you have to click on available `source` connector then select `target` connector, but just after selecting source connector you should see only valid available targets to which you can connect selected lane and nothing more. 

It's feature, not a bug if you meant that. 😉

**Comment by aubergine10** [comment]
@krzychu124 The lane connector lines are missing for customised routes. For example in the last screenshot you can see a partial line from the orange circle. The route is set up, but the line is not showing.

@0livander Are you using a multiplayer mod (what's the user names appearing top-left corner of the screen)? Also, can you [share your savegame and log file](https://github.com/krzychu124/Cities-Skylines-Traffic-Manager-President-Edition/wiki/Report-a-Bug) so we can investigate further.

**Comment by krzychu124** [comment]
ooh, I thought he just clicked source connector and then made screenshot (in state when he has to choose target)
In this can, as you said we need a savegame

The usernames - isn't it in-game discord overlay?

**Comment by 0livander** [comment]
@krzychu124 Sorry it was a bit unprecise, @aubergine10 is right.
To better show it i'd have made this pics right away. 
Where can I get the savegame from?

And yes the Icon in the top corner is just discord.


![T1](https://user-images.githubusercontent.com/50545902/57586327-b213e000-74f4-11e9-8710-5fffc1d10f20.jpg)
![T2](https://user-images.githubusercontent.com/50545902/57586329-b3dda380-74f4-11e9-92f6-6ef863505f26.jpg)
![T3](https://user-images.githubusercontent.com/50545902/57586331-b5a76700-74f4-11e9-9364-c7cad687c1f4.jpg)

**Comment by aubergine10** [comment]
Details of how to get save game and log file are linked from this page: https://github.com/krzychu124/Cities-Skylines-Traffic-Manager-President-Edition/wiki/Report-a-Bug

**Comment by 0livander** [comment]
Here is the safegame: https://steamcommunity.com/sharedfiles/filedetails/?id=1739780961

The Log: 
[output_log.txt](https://github.com/krzychu124/Cities-Skylines-Traffic-Manager-President-Edition/files/3170436/output_log.txt)

**Comment by aubergine10** [comment]
Looking at the additional screenshots you posted, it looks like it's working properly.

1. When you have no lane selected, all the input lanes have circles (no output lane circles).
2. When you select an input lane, other input lane circles are hidden, and the output lane circles appear.
3. When you deselect an input lane, it returns to the state 1 above.

**Comment by 0livander** [comment]
@aubergine10 Yeay I see why I thought its a bug ... the circles weren't disappearing in my game in the first place. Now they do so it works propperly but looks different. 

Thanks guys!!
