### ISSUE TITLE
Differentiate Stable vs. Labs in content manager

### ISSUE THREAD

**Issue by aubergine10** [krzychu124/Cities-Skylines-Traffic-Manager-President-Edition#326]
_As a user, I want to be able to differentiate between Labs and Stable versions in the Content Manager, and the mod options screen_

This is particularly important should users transitioning between versions find themselves with both subscribed at the same time, eg:

> **Biffa** 1 hour ago :
> QOL - both STABLE and LABS have the same name in the games Content ~~Workshop~~ _Manager_, maybe suffix STABLE and LABS onto the names to differentiate :-)

**Assumptions/Preconditions**

* We can determine the workshop ID when C:SL invokes getter `TrafficManagerMod.name`

or

* We can somehow build in the suffix at compile time

**Tasks**

* Suffix `LABS` or `STABLE`, as applicable, in Content Manager (and also log entries?)
* It could be that only LABS version gets the suffix; the primary goal is that end user can discern between the two within `Content Manager > Mods` and `Options > TM:PE`

**Acceptance Criteria**

* Users can discern between Labs and Stable versions in Content Manager and Options screens.

**Comment by aubergine10** [comment]
Note: If we achieve #211, which will facilitate hot swappale versions, this #326 will be even more pertinent.

**Comment by krzychu124** [comment]
I am going to create PR with `LABS` suffix. 
To build mod as LABS we will have to select different release build profile, let's say `Release LABS` which would be clone of `Release` profile but with additional preprocessor flag `LABS` to choose appropriate `Version` field  value in TrafficManagerMod.cs.
`LABS` suffix will be visible in `Content Manager` and in MainMenu label also. 

Determinate version from workshop ID won't work when you build from sources or running in Steam offline mode.
