### ISSUE TITLE
Can't find version 10.20

### ISSUE THREAD

**Issue by stirlmc** [krzychu124/Cities-Skylines-Traffic-Manager-President-Edition#329]
Can someone please upload the latest version (10.20). All I can find is 10.19. 

Thank you very much!

**Comment by aubergine10** [comment]
Ah, yes, good catch - we forgot the github release! doh!

https://github.com/krzychu124/Cities-Skylines-Traffic-Manager-President-Edition/releases

**Comment by YuseinST** [comment]
l cannot find it too yes please update the latest version 10.20 l hope it gonna come soon.

**Comment by aubergine10** [comment]
https://github.com/krzychu124/Cities-Skylines-Traffic-Manager-President-Edition/releases/tag/10.20
