### ISSUE TITLE
Penalize buses ignoring lane arrows

### ISSUE THREAD

**Issue by s2500111** [krzychu124/Cities-Skylines-Traffic-Manager-President-Edition#343]
### Description
When buses are allowed to ignore lane arrows, they are often preferring to keep their lane rather then switching to the correct one, even if there is a node where they could move over.

I think this behavior is achieved by penalizing lane changes but not penalizing the ignoring of lane arrows. Adding a penalty for ignoring lane arrows could be helpful.

**Comment by aubergine10** [comment]
Could you attach some annotated screenshots to illustrate the problem?

**Comment by s2500111** [comment]
I've tried to reproduce the behavior I criticized and they behaved like I would expect them to. I think I'm opening this again if I'm able to reproduce a situation, where this happens :)
