### ISSUE TITLE
Which traffic does "clear traffic" clear?

### ISSUE THREAD

**Issue by aubergine10** [krzychu124/Cities-Skylines-Traffic-Manager-President-Edition#35]
Doing new docs for "clear traffic" tool and it's not clear from old docs what traffic is cleared.

I assume all road traffic, but does that include cims, busses, trams, bicycles? What about other forms of traffic, such as cargo ships, ferries, trains, balloons, etc?

Is it possible to determine from the code what it clears?

**Comment by krzychu124** [comment]
Yup is is possible, look _(easy stuff, I think )_ 😉
https://github.com/krzychu124/Cities-Skylines-Traffic-Manager-President-Edition/blob/f574f0dc24ece8a5abe08769561008aacbbdba2b/TLM/TLM/Manager/Impl/UtilityManager.cs#L22-L33

It simply releases(despawn) every spawned vehicle (car, bus, tram, train etc.) and resets traffic data from all road segment(traffic flow, relative speed per lane etc.)

**Comment by aubergine10** [comment]
Does vehicle manager include pedestrians, dogs, seagulls, etc?

My assumption is that cims and animals are handled by CitizenManager and other things?

**Comment by krzychu124** [comment]
Yes they are. 
Vehicle manager is managing following types of vehicles:
`Rocket | Balloon | Blimp | CableCar | Monorail | Ferry | Vortex | Meteor | Helicopter | Tram | Bicycle | Plane | Ship | Train | Metro | Car`

Animals have separate AI based on AnimalAI which is managed by CitizenManager, I think:
 `BirdAI(Seagull) | LivestockAI(Cow, Pig) | PerAI(Dog) | RescueAnimalAI | WildlifeAI`

**Comment by aubergine10** [comment]
Are vans, trucks, emergency services, etc, grouped as ```CAR```?

**Comment by krzychu124** [comment]
Yup, 'Car' is general type, I will check that 😉

**Comment by aubergine10** [comment]
That's missing cargo planes?

Also, what about things like postal vans/trucks?

**Comment by aubergine10** [comment]
I notice Pedestrian is in there too..

**Comment by krzychu124** [comment]
Ooops, wrong branch 😅 
https://github.com/krzychu124/Cities-Skylines-Traffic-Manager-President-Edition/blob/559b624c4ddb720ded7488ef7baba189e398e1d5/TLM/TLM/Traffic/ExtVehicleType.cs#L7-L38

In addition I have no idea why there is Pedestrian. Interesting that my code editor points that it is never used

**Comment by aubergine10** [comment]
Added a list of affected traffic to the FAQ in docs: https://github.com/krzychu124/Cities-Skylines-Traffic-Manager-President-Edition/wiki/Clear-Traffic
