### ISSUE TITLE
Remove `RushHour` code

### ISSUE THREAD

**Issue by aubergine10** [krzychu124/Cities-Skylines-Traffic-Manager-President-Edition#350]
There's a bunch of code relating to a mod, `RushHour` that no longer exists (and Rush Hour 2 is obsolete too).

For example, in `GlobalConfig.cs`:

https://github.com/krzychu124/Cities-Skylines-Traffic-Manager-President-Edition/blob/master/TLM/TLM/State/GlobalConfig.cs#L253-L280

That stuff can be ripped out as it's no longer relevant.

@dymanoid Is any of that relevant to Real Time?

**Comment by dymanoid** [comment]
@aubergine10, **Rush Hour** still exists and can be subscribed to in the Workshop. This code seems to ensure the integration between **Rush Hour**'s parking features and **TM:PE**'s parking features.

**Real Time** doesn't manage the vehicles at all, so this code has absolutely no effect on **Real Time**.

**Comment by Sipke82** [comment]
That rush hour parking feature is what i ment in #298

**Comment by aubergine10** [comment]
Did Rush Hour II have those features? I thought it was only the older one which is kaput?

**Comment by dymanoid** [comment]
Yes, you're right. Rush Hour II has no car parking logic anymore. Just checked it.

**Comment by aubergine10** [comment]
Considering #298 we could convert it in to an option user interface or the global xml.

Will pause this until after the harmony update is complete.

**Comment by VictorPhilipp** [comment]
As far as I remember I removed the Rush Hour compatibility code in the harmony branch

**Comment by aubergine10** [comment]
Confirmed the obsolete code was removed as part of migration to harmony.
