### ISSUE TITLE
Separate binaries for STABLE and LABS on github releases

### ISSUE THREAD

**Issue by aubergine10** [krzychu124/Cities-Skylines-Traffic-Manager-President-Edition#360]
Due to #326, we will now have separate builds for Stable and Labs branches.

This should also be reflected on the [github releases](https://github.com/krzychu124/Cities-Skylines-Traffic-Manager-President-Edition/releases) entries for v10.21 and above.

Is that feasible? Also, what is the process for creating those releases entries (I assume just standard github stuff, but just wanted to check). I intend to document release process at some point and would need to include any relevant details.

**Comment by krzychu124** [comment]
Yeah, I thought about that.

We can attach both binaries to the same release if both contains the same content (changes), 

If not, we could create separate github release for Labs and for example mark it as `pre-release` using that checkbox at the bottom. What do you think?

**Comment by aubergine10** [comment]
Yup, that would work.

**Comment by aubergine10** [comment]
Docs: https://github.com/krzychu124/Cities-Skylines-Traffic-Manager-President-Edition/wiki/Release-Binaries

**Comment by aubergine10** [comment]
oops, forgot to close this
