### ISSUE TITLE
Can't place bus stops after upgrading road

### ISSUE THREAD

**Issue by aubergine10** [krzychu124/Cities-Skylines-Traffic-Manager-President-Edition#369]
Had a few Steam users report this issue and one of them has now posted save game and some extra details.

Steam topic: https://steamcommunity.com/workshop/filedetails/discussion/583429740/1812044473333143083/

It's possibly related to #277 ?

### Description

> When I upgrade roads, I cannot set bus stops on the new roads until I save and re-load the game. Then I can set bus stops on the upgraded road. When I build new subway lines, I cannot set stops at the new stations until I save and re-load the game. Then I can set up subway stops.
>  
> When I disable TM:PE, the problem disappears but so do all the features I love in TM:PE. 

I just installed TM:PE and have the exact same issue. Once I upgrade a street, its completely unable to interact with any other street connected. Even cars do U-Turns right where the upgraded street is connected to a normal one. When I upgrade every street in the game, it works, otherwise I have to disable the mod and reload the game.

It still is bugged when I upgrade a street with a bus station next to it. Downgrading and upgrading the street works to recreate the bug.

The mods I use are:
TM:PE Stable
Recycling Center
Difficulty Tuning
All Spaces Unlockable

### Save game

https://steamcommunity.com/sharedfiles/filedetails/?id=1764772151

### Log file

output_log.txt after recreating the bug: https://pastebin.com/FnqUVp70

### Screenshot

Screenshot of the bus stations I have to connect manually again:
https://gyazo.com/ce05b0b4179664e1c6860c9659670ac8

**Comment by krzychu124** [comment]
Yup #277 , again pedestrian path node...

![ped-paths](https://user-images.githubusercontent.com/19638970/59153863-da93e900-8a64-11e9-85e5-64e0f123897d.jpg)

__Remove them and never re-build again...__

Some thoughts:
- no mods were used while placing these pedestrian paths (Move It, Fine Road Anarchy..)
- every time I built ped/bicycle/gravel path there, one of nodes caused infinite loop.
- I think that something is wrong with those path segments (ped, bicycle, gravel).

_To be honest... I think it's the time to create bug report on the Paradox/Cities Skylines forum... They know that game better than me_ 😄

**Comment by aubergine10** [comment]
User confirms that removing the path fixed the issue.

Agreed we should report this to Paradox, we certainly have enough replications of the issue for them to investigate.

**Comment by aubergine10** [comment]
I'll report to Paradox and link them to the issues here.

**Comment by aubergine10** [comment]
Duplicate of #277 - closing
