### ISSUE TITLE
Transparent logo for docs pages

### ISSUE THREAD

**Issue by aubergine10** [krzychu124/Cities-Skylines-Traffic-Manager-President-Edition#373]
@FireController1847 could you do a horizontal version of the logo with transparent backrgound for use on documentation pages (README, CHANGELOG, and I'll be using it in the wiki too, and probably also a HTML tool I'm making for editing translations)?

Something like:

```
icon Traffic Manager: President Edition
```

It will almost always appear on white background, but sometimes shades of grey depending where it's used.

**Comment by FireController1847** [comment]
Since the icon is so tall, it'd be difficult to make a fully horizontal image. I took the preview image and cropped it down a bit, will this work?

![Preview TRANSPARENT](https://user-images.githubusercontent.com/16494272/59242504-092ad480-8bc9-11e9-8afd-8a8e90be83d5.png)

**Comment by aubergine10** [comment]
Second one looks better; text colours could do with flipping though due to white background

**Comment by FireController1847** [comment]
Personally I disagree, I think the blue contrast works well with the white background. However what colors would you like me to do? Inverting won't work here.

I could try making the text all black?

**Comment by aubergine10** [comment]
No, I meant invert the two blue colors, so Traffic Manager uses the darker blue and President Edition uses the lighter blue.

**Comment by FireController1847** [comment]
I'm not sure I understand the purpose of that, but I'll try it when I get the chance :)

**Comment by aubergine10** [comment]
Edited comment above; mean to say _swap_ the existing colors.

**Comment by FireController1847** [comment]
![Preview TRANSPARENT SMALL](https://user-images.githubusercontent.com/16494272/59316295-ee189d00-8c7a-11e9-93a2-266292b6f3e9.png)
