### ISSUE TITLE
Grep all uses of `Translation.GetString()` 

### ISSUE THREAD

**Issue by aubergine10** [krzychu124/Cities-Skylines-Traffic-Manager-President-Edition#376]
As part of #336 (transitioning to an xml file for locations) I'm adding `<Where>` tags to translation keys to state where a translation is used, making it easier for translators (and us) to test updates to translations or quickly filter the translations to a specific feature of the mod.

To do that more quickly I need some way to find out where all the translations are used, something in a text file that lists the `Translation.GetString(whatever)` along with the .cs file it's used in. In particular, such a file would allow me to sort the lines, so that translation keys which are used more than once will get grouped together.

Example of file format:

```
Translation.GetString(whatever) /path/to/some.cs
...
```

If someone has time, and knows how to grep the source, it would be a huge help :)

**Comment by krzychu124** [comment]
[translation_getString.txt](https://github.com/krzychu124/Cities-Skylines-Traffic-Manager-President-Edition/files/3282454/grep_translation_getString.txt)

Here you go 😉

**Comment by aubergine10** [comment]
Awesome! thank you!
