### ISSUE TITLE
Create somewhere to store logo assets

### ISSUE THREAD

**Issue by aubergine10** [krzychu124/Cities-Skylines-Traffic-Manager-President-Edition#393]
We've got logo assets strewn over a few github issues currently, would probably be worth finding a better place to store them.

Issues I'm aware of that contain logos: #71 , #373

**Comment by FireController1847** [comment]
Why not just upload them to the Discord or GitHub wiki?

**Comment by aubergine10** [comment]
GitHub wiki has some issues with file attachments currently (specifically it borks when using Git Desktop, see https://github.com/desktop/desktop/issues/3839 ) And Discord is a terrible place to store files. 

I've created a PR for a new `/docs` folder - see #394 - with eventual aim that the files could go in there.

**Comment by dymanoid** [comment]
Please don't store binary files in a GitHub repository.

If you still want to use GitHub as your image storage, consider [Git LFS (large file storage)](https://git-lfs.github.com/).

**Comment by aubergine10** [comment]
Is there a reason why? There's 8 logo images and it seems best to keep those associated with the source.

**Comment by aubergine10** [comment]
Images for user guide could be hosted elsewhere. It's mainly the logo images I want to keep in the repo.

**Comment by krzychu124** [comment]
I think they still will be associated because LFS is extension to github, AFAIK

**Comment by dymanoid** [comment]
Since Git is DVCS (distributed version control system), everyone has a copy of the entire repo.
When you check in a file, you have it forever and ever. Your grandchildren's grandchildren's grandchildren will download your cat gif every time they clone your repo, even if you "delete" that file later. It won't be deleted.

Furthermore, there is usually no point in versioning of binary files. You cannot merge them.

You can use LFS if you still want to have a possibility to get your images **with** the code repo.

LFS is an extension for Git in general, not only for GitHub.

**Comment by aubergine10** [comment]
LFS seems like a lot of hassle for 8 image files. As the images exist in the git issue tickets mentioned in OP, I've just created a `Logo.md` file and linked to the existing images in the issues so they don't need to go in main repo.

**Comment by FireController1847** [comment]
I strongly disagree with both of you! Are we seriously fighting over the fact that some kilobytes of logo images are not going to be stored in the GitHub repo? There is absolutely no reason why we can't just have them in a folder called "logos" or such and put them in there. It's not like we're talking about 40 GB of data here, it's a couple kilobytes guys!

**Comment by aubergine10** [comment]
I think we can leave them lurking in issues tab for now, especially seeing as the URLs to the image files are static and don't expire in there, it's easy to reference them from markdown files for time being. I certainly don't want something as minor as images getting in the way of having the `/docs` folder added.

I have much bigger plans for the `/docs` folder, namely to use github pages (with a completely custom theme as all the inbuilt themes are grim as toast) to host docs and a browser-based localisation tool.

**Comment by aubergine10** [comment]
Nothing logo related, but need the image for the wiki so dumping here for now:

![Origin-auto-update](https://user-images.githubusercontent.com/1386719/60513570-811f8280-9ccf-11e9-8f34-845aa09e0d56.png)

**Comment by aubergine10** [comment]
Closing this issue as we'll just keep the images in their existing github issues for now. Easy to find them by searching 'logo' from issues tab.
