### ISSUE TITLE
Road customisations not getting saved

### ISSUE THREAD

**Issue by aubergine10** [krzychu124/Cities-Skylines-Traffic-Manager-President-Edition#397]
From LABS workshop page:

> **Fiamma Volta:** So, got public transport sorted, except now the mod doesn't remember any settings. Like, I manage roundabouts and add road restrictions, I re-log and lo and behold all of my road management is gone. help?

> **aubergine18:** Do you have more than one version of TMPE subscribed? If so, completely unsubscribe the other versions - only one version should be subscribed at a time

> **Fiamma Volta:** I only have 1 version of TM:PE. I've never used the [stable] version.

I've asked for log file to see if there are any errors or conflicting mods.

**Comment by aubergine10** [comment]
Note: Might be fixed in 10.21 by:

> * Fixed: Minor issues regarding saving/loading junction restrictions (#358)

**Comment by krzychu124** [comment]
Fix from #358 applies only to `Turn on Red` settings.

**Comment by FireController1847** [comment]
Closing due to being fixed in 10.21, will re-open if it continues to be an issue after 10.21

**Comment by aubergine10** [comment]
There's no guarantee that #358 fixed the problem the user was having, however the user has not responded to requests for more info so probably safe to close for that reason.
