### ISSUE TITLE
(off-topic, but worth checking) Mixing Metro Stations with Vanilla Stations causes Metro use to flatline (at that particular station)

### ISSUE THREAD

**Issue by SubaruSVX** [krzychu124/Cities-Skylines-Traffic-Manager-President-Edition#399]
### Description
This is something untoward, but since @aubergine10 told me to post this here, I might as well.

I've got a problem in my city at which when mixing vanilla and just one Workshop station causes the use to completely flatline. I mean, there are people using all the other stations to get to places, but the one Workshop station resting on a major interchange created zero or very little use.
### Reproduction Steps
Add more steps as necessary.
1. Build a metro line (combining Workshop and the vanilla station)
2. Connect everything
3. Wait

### Mod List
Please list the mods enabled when you noticed the bug.
[config SubaruSVX.docx](https://github.com/krzychu124/Cities-Skylines-Traffic-Manager-President-Edition/files/3344573/config.SubaruSVX.docx)

### Output Log
[Player.log](https://github.com/krzychu124/Cities-Skylines-Traffic-Manager-President-Edition/files/3344567/Player.log)

### Savegame (Optional)
https://steamcommunity.com/sharedfiles/filedetails/?id=1773716256

### Screenshots (Optional)
Not sure if this is relevant, but this screengrab caused this error. Could this have anything to do with it?

<img width="1280" alt="Screen Shot 2019-06-20 at 8 13 18 AM" src="https://user-images.githubusercontent.com/50699460/60421636-d64e8c00-9c1c-11e9-950c-094f1d792020.png">

### Additional Info
I'm told MOM has an update coming along soon, so if this should be removed...

Edit: [Here](steamcommunity.com/sharedfiles/filedetails/?id=1589329044) is the metro station I used. You're welcome to have a go.

**Comment by aubergine10** [comment]
Hey, did new MOM release fix this?

**Comment by SubaruSVX** [comment]
I replaced the problematic one with a different station from the Workshop, but it's working so far.
