### ISSUE TITLE
Speed limit UI performance drop when train tracks on screen

### ISSUE THREAD

**Issue by aubergine10** [krzychu124/Cities-Skylines-Traffic-Manager-President-Edition#411]
Had a user saying the speed limits UI was grinding fps:

> **rlas:** When i try to change the speed in lanes and click on the Speed Change icon in TMPE the game slows down to about 1fps. This happens only in that one feature. Hope this can be fixed :D

Later they updated with this:

> **rlas:** i found out that only happens while Railway Replacer Train Tracks are in the visual appearence. in other areas the FPS is stable and normal. It somehow conflicts with the Railway Tracks from R69 and Revo :/ Got a GTX 1060 6GB, AMD FX(tn) 6300 Six Core Processor 3.50 GHz, 40GB RAM, 64 Bit System. Hope this helps. Also if i scroll out so the Speed UI Symbols on tracks or roads disappear the FPS goes also back to normal. So smth is there going on with Railway Replacer. Good luck for ths :)

The assets in question are these:

https://steamcommunity.com/workshop/filedetails/?id=1569088356

Note in particular the "Railway Replacer" mod is part of that colleciton:

https://steamcommunity.com/sharedfiles/filedetails/?id=1530376523

Is it possible that mod is causing some sort of refresh or update per frame, and that could be causing speed limits UI to refresh every frame = fps drop?

**Comment by DaEgi01** [comment]
checked with only TM:PE labs edition from 2019-07-02 and with + without the railway replacer mod.
I experience is a big reduction in fps (~30 -> ~25) with speed limits on if there are only streets on the screen, but a huge reduction in fps (~30 -> ~6) if there are rail tracks. tested only with vanilla tracks, not with ronyx but don't expect it to make any difference.
subbing or unsubbing to RRM does not seem to have any affect.
I guess what rlas meant is: 
> i found out that only happens while Train Tracks are in the visual appearence.

>

**Comment by kvakvs** [comment]
Just note the rail tracks mod is a huge 1GB+ asset with very high detalization. So in general this mod does not care about performance, but about looks.

Speed limits rendering was not changed when MPH speed limits were added, i.e. it should be the same in TM:PE 10.20. How did this mod behave in 10.20?

**Comment by DaEgi01** [comment]
has nothing to do with neither the RRM mod, nor with ronyx 1GB+ assets since the issue happens without the assets and without the mod. I tried to debug it myself and found the root cause of the issue.
check commit 467956.
its the change made to TextureResources.cs
where Log.Info is triggered if index > SpeedLimit.UPPER_KMPH which is pretty often since its called in a OnToolGUI method.
since I m not sure what kind of information you actually want to spam into the log and what not I can't provide a pull request, but you know now what to do :)

**Comment by DaEgi01** [comment]
oh an btw, this bug made it into the official cities skylines youtube channel ;)
see https://www.youtube.com/watch?v=6Iyw4Kqy-FM 56:50
hehe, she admits though that she should not be using labs ^^

**Comment by aubergine10** [comment]
@DaEgi01 Thanks for tracking down the issue, we'll get it fixed in next release!

@kvakvs A good way to avoid this sort of thing in future is to use `Log._Debug()` method as that gets completely removed in the `RELEASE` builds.
