### ISSUE TITLE
Crash on load (not enough RAM / pagefile)

### ISSUE THREAD

**Issue by arttrax** [krzychu124/Cities-Skylines-Traffic-Manager-President-Edition#416]
https://steamcommunity.com/app/255710/discussions/0/1647665620927517811/?tscn=1559544975 

[output_log.txt](https://github.com/krzychu124/Cities-Skylines-Traffic-Manager-President-Edition/files/3365041/output_log.txt)
When I try to play the game crashes while loading. I turned off all mods. Tried to load games, start new games. There was a message about a crash file to send that it was next to the executable but I can not find where cities is stored on my hard drive so I can not find the file.

aubergine18  has Cities: Skylines Jun 3 @ 4:12am 
share log file so we can see what's going on

https://github.com/krzychu124/Cities-Skylines-Traffic-Manager-President-Edition/wiki/Share-your-Cities-Skylines-log-file

**Comment by aubergine10** [comment]
Hi @arttrax - it looks like the crash didn't occur in the session where that log was created. Can you get the game to crash again and after doing so send us the updated log file?

**Comment by arttrax** [comment]
[output_log.txt](https://github.com/krzychu124/Cities-Skylines-Traffic-Manager-President-Edition/files/3365057/output_log.txt)

**Comment by krzychu124** [comment]
Increase page file size. If 'system managed' option set, check out if you have enough free disk space

**Comment by arttrax** [comment]
Free space 148 gig - How do I do what you are asking?

**Comment by krzychu124** [comment]
checkout [this tutorial](https://www.youtube.com/watch?v=DWCVhk5gTps)

**Comment by arttrax** [comment]
Wow - I do not know why but it was hard set to zero
Game loaded.
Thanks
