### ISSUE TITLE
Installation issue on Kubuntu

### ISSUE THREAD

**Issue by Sayanel01** [krzychu124/Cities-Skylines-Traffic-Manager-President-Edition#425]
### Description
I don't see the TM:PE icon in game.
I am using Kubuntu 18.04, playing on Steam. I have no problem with the (one) other mod I tried.

### Reproduction Steps
1. Subscribe to mod on steam workshop, restart CS

### Mod List
- TM:PE (I don't know. Looking at steam workshop, 10.20 I suppose)
- Mod listing
- Sunken Plaza

### Output Log
[Player.log](https://github.com/krzychu124/Cities-Skylines-Traffic-Manager-President-Edition/files/3383121/Player.log)

No TM:PE log

### Screenshots (Optional)
In game mod manager : https://imgur.com/LBRv3Nm

Thank you for your help

**Comment by krzychu124** [comment]
Hi, did you enabled it? (Mods tab - search for TM:PE)

**Comment by aubergine10** [comment]
If there's no TMPE.log it's likely the mod isn't enabled:

Main menu > Content manager > Mods > TM:PE > Enable

**Comment by Sayanel01** [comment]
That's it ! Sorry for the bothering... It saw it in the 'steam workshop' tab, didn't look for the mod tab.

**Comment by aubergine10** [comment]
Glad you got it working :)
