### ISSUE TITLE
Logo image for v11-alpha

### ISSUE THREAD

**Issue by aubergine10** [krzychu124/Cities-Skylines-Traffic-Manager-President-Edition#429]
I'm going to put an alpha in workshop so we can get a few more people on-board with testing the port to Harmony eg. to check game save/load works, and hopefully identify any regressions.

@FireController1847 could you do a logo thumbnail image for v11-alpha (similar to LABS image but instead of `LABS` the text would be `v11-alpha`). For the main image (that appears on detail page) maybe something with a disk icon and an exclamation mark as a warning that if something goes wrong it could break saves?

**Comment by FireController1847** [comment]
Yeah, I'll get on it later today when I get the chance.

**Comment by kvakvs** [comment]
For a more broken look if i may suggest, overlay some scaffolds on top of it making it like under construction.

http://ohsguide.ihsa.ca/en/topic/scaffold_1.png
https://thumbs.dreamstime.com/z/under-construction-bar-6116673.jpg

**Comment by aubergine10** [comment]
wait, what about....

![image](https://user-images.githubusercontent.com/1386719/61247995-15ff9280-a74a-11e9-98f8-d0ce96b15b08.png)

The construction chirper shown in asset editor...?

**Comment by kvakvs** [comment]
The chirper is adorable, so maybe just the construction chirper and TM:PE logo?

**Comment by krzychu124** [comment]
![ChirperHardHat](https://user-images.githubusercontent.com/19638970/61248246-f6b93300-a752-11e9-8c6e-e72160467cec.png)
transparent background 😉

**Comment by kvakvs** [comment]
The construction chirper is the logo of Skylines.Code discord

**Comment by krzychu124** [comment]
so maybe mix regular chirper with traffic cone?

**Comment by FireController1847** [comment]
(This is a draft, however if it's perfect then you can use it)

Are we thinking something like this?
![Preview V11-ALPHA](https://user-images.githubusercontent.com/16494272/61260141-4e977000-a73a-11e9-8cc0-4fd5000483d2.png)

**Comment by aubergine10** [comment]
Awesome! Could you do the smaller thumbnail one too? (that appears in sidebar)

**Comment by aubergine10** [comment]
Actually, for the square thumbnail image it might be worth just having chirper with the traffic cone hat? Dunno.

**Comment by FireController1847** [comment]
I had an idea, I don't know if you'll like it. Opinions?

![Thumbnail V11-ALPHA](https://user-images.githubusercontent.com/16494272/61347491-6d6d3380-a81a-11e9-97dc-69a72006011f.png)

**Comment by aubergine10** [comment]
perfect, love it!!

**Comment by aubergine10** [comment]
https://steamcommunity.com/sharedfiles/filedetails/?id=1806963141
