### ISSUE TITLE
LABS workshop description tweaks

### ISSUE THREAD

**Issue by krzychu124** [krzychu124/Cities-Skylines-Traffic-Manager-President-Edition#432]
[labs_workshop_description_markup](https://github.com/krzychu124/Cities-Skylines-Traffic-Manager-President-Edition/files/3403850/labs_workshop_description.txt)

**Comment by aubergine10** [comment]
be sure to open it in an editor that supports UTF8 (notepad seems to fubar the space chars)

[labs_workshop_description (1).txt](https://github.com/krzychu124/Cities-Skylines-Traffic-Manager-President-Edition/files/3404049/labs_workshop_description.1.txt)

**Comment by krzychu124** [comment]
Testing...

**Comment by aubergine10** [comment]
Here's what it should look like:

![image](https://user-images.githubusercontent.com/1386719/61416710-90681800-a8ec-11e9-8918-3a6cef273339.png)

**Comment by krzychu124** [comment]
Done.
