### ISSUE TITLE
Mod checker should always check for other TM:PE

### ISSUE THREAD

**Issue by aubergine10** [krzychu124/Cities-Skylines-Traffic-Manager-President-Edition#434]
Currently, if user turns off mod checker, it won't check for other TM:PE

That can cause the save/load issues we are all familiar with.

I'll update it to always check for TM:PE, but only check other mods (`incompatible_mods.txt`) if the user has enabled checks on startup.

**Comment by kvakvs** [comment]
I suggest that TM:PE should shut down if other TM:PEs are detected, and either the most stable would remain running, or all of the shut down.

**Comment by aubergine10** [comment]
If there are more than one TM:PE, regardless of whether enabled or not, it will still cause problems. See #211, particularly Dymanoid's comments.
