### ISSUE TITLE
Remove speed limit conversion from Configuration class

### ISSUE THREAD

**Issue by VictorPhilipp** [krzychu124/Cities-Skylines-Traffic-Manager-President-Edition#435]
Move the conversion
https://github.com/krzychu124/Cities-Skylines-Traffic-Manager-President-Edition/blob/ef4fc554016de26e7c468243dc6e3297cba58969/TLM/TLM/State/Configuration.cs#L18
to `SpeedLimitManager`.

**Comment by kvakvs** [comment]
Solved in #475
