### ISSUE TITLE
Change default traffic light behaviour

### ISSUE THREAD

**Issue by Sipke82** [krzychu124/Cities-Skylines-Traffic-Manager-President-Edition#44]
I think the main reason is why we need to setup timed traffic lights is because the default traffic light settings are a bit wack, as they allow multiple directions to enter intersection at the same time, causing collision points. It would be more logical if the default setting would not do that, and that way we can reserve the timed traffic lights for the more complex situations.

So for the default traffic lights it would be more logical to set up as:
Lanes can go straight, left and right from one direction, the lane to the left can also turn at the same time because traffic won't hit each other.
In addition add a step where pedestrian can pass, without being hit by cars.

This setup might be more logical as default traffic light setup.

Original, with some discussion:
https://github.com/VictorPhilipp/Cities-Skylines-Traffic-Manager-President-Edition/issues/200

**Comment by aubergine10** [comment]
See: https://github.com/krzychu124/Cities-Skylines-Traffic-Manager-President-Edition/issues/5
