### ISSUE TITLE
Warn/error if `in` keyword used

### ISSUE THREAD

**Issue by aubergine10** [krzychu124/Cities-Skylines-Traffic-Manager-President-Edition#440]
As per Dymanoid's comment - https://github.com/krzychu124/Cities-Skylines-Traffic-Manager-President-Edition/issues/349#issuecomment-513027564 - we should avoid using `in`.

> Rule of thumb: don't use `in`. If you still want to use it, see rule of thumb. Please read **[this SO question](https://stackoverflow.com/q/52820372/2846483)** and the two most upvoted answers.

Would be good if we could get Rosyln analyser (or whatever) to complain if `in` is used anywhere (if it doesn't already do this, not checked).

**Comment by dymanoid** [comment]
I could drop in a PR for this one.

**Comment by aubergine10** [comment]
👍
