### ISSUE TITLE
Path-Finding Abnormalities 

### ISSUE THREAD

**Issue by Shadertheboi** [krzychu124/Cities-Skylines-Traffic-Manager-President-Edition#444]
### Description
It seems the path-finding still needs a little more fine tuning. Cims will be taking routes that seem off or a longer route. You can refer to the screenshots for a clearer picture.

### Savegame (Optional)
https://steamcommunity.com/sharedfiles/filedetails/?id=1810062363

### Screenshots (Optional)
![Screenshot 49](https://user-images.githubusercontent.com/35039987/61577065-bd970f00-ab14-11e9-9448-6925201bba09.png)
![Screenshot 50](https://user-images.githubusercontent.com/35039987/61577066-be2fa580-ab14-11e9-920c-3502d5662212.png)
![Screenshot 51](https://user-images.githubusercontent.com/35039987/61577067-be2fa580-ab14-11e9-8fde-31c0cafda1b1.png)

**Comment by kvakvs** [comment]
Can you capture where the destination is relatively to the start or the current position of the car? At least approximate direction? I too have my ideas why pathfinder makes cars so stubborn on taking clogged roads and inoptimal turns, and have some ideas how to improve it.

**Comment by Shadertheboi** [comment]
[https://youtu.be/epYDpxCEocE](url)
I changed the road junction properties as shown in the video at 2:52. You can watch the self-explanatory video. This bug has been reported here before by me but I can't seem to find the issue; where vehicles seem to ignore the traffic commands of traffic lights because of 2 junctions being too close to each other. 

Do you think this traffic issue is caused by the same bug?

**Comment by kvakvs** [comment]
The link is not working. If i copy & paste it into the address bar, Youtube says the video is not available.

**Comment by Shadertheboi** [comment]
Oops... I changed the video from "private" to "unlisted". You try again.

**Comment by kvakvs** [comment]
The fact that buses use dead ends to turn around is not a bug, they have no shorter way around the block and they would not do it on the street.
The fact that some cars turn to that small street is definitely a routing bug.

**Comment by aubergine10** [comment]
@Shadertheboi Could you [share your save game](https://github.com/krzychu124/Cities-Skylines-Traffic-Manager-President-Edition/wiki/Share-your-Savegame-on-Steam) - it will make it much easier to replicate the issue.

There are issues if a road is too short, particularly with timed traffic lights as they need 1+ normal sized segments to work - see #302

**Comment by Shadertheboi** [comment]
https://steamcommunity.com/sharedfiles/filedetails/?id=1810062363

There you go

**Comment by Shadertheboi** [comment]
@aubergine10: Okay... I can confirm the path-finding of instances is also affected by roads that are too short between 2 junctions as mentioned in #302 and shown in my YouTube video at 0:28.  

I had to trigger this for the road junctions so that the path-finding mechanism won't be broken.
![image](https://user-images.githubusercontent.com/35039987/61682125-ef8db880-ad42-11e9-91bc-ebd7a729e2ff.png)

The path-finding seems to be normal right now:
![image](https://user-images.githubusercontent.com/35039987/61682614-de45ab80-ad44-11e9-9b11-90e9298453fe.png)

@aubergine10: If you have accessed my savegame, there is another interesting thing to note too. After activating the "Allow/disallow lane changing for vehicles going straight on" function city-wide, I don't have insane bottlenecks that are forever clogging my roads and not clearing.

**Comment by aubergine10** [comment]
@Shadertheboi Just noticed this closed - were there any remaining problems we need to investigate?

**Comment by Shadertheboi** [comment]
By activating the function that I mentioned above, it helps to mitigate the unnecessary eternal traffic jams in my city. But as I have also mentioned, I believe this issue is caused by the same bug mentioned in issue #302. 
So perhaps, if anything needs to be looked at, issue #302 will be the one. However, if you feel that this issue still has other parts that needs to be looked at, feel free to reopen this issue. :)
