### ISSUE TITLE
v11: Issue with parking restrictions

### ISSUE THREAD

**Issue by aubergine10** [krzychu124/Cities-Skylines-Traffic-Manager-President-Edition#445]
From Steam user on v11 alpha:

> **Dying** 19 Jul @ 11:47pm 
> Old parking restrictions (set with LABS) works fine after loading with V11A, but new ones seems to be ignored: https://steamcommunity.com/sharedfiles/filedetails/?id=1809224714

Apparently parking restrictions set via v11 are being ignored, but those set by LABS were still working fine.

**Comment by kvakvs** [comment]
I noticed that too. The signs are set, but the cars just stay where they are parked.

**Comment by aubergine10** [comment]
Just had this from another v11 user on Steam:

> **benzoll** 15 hours ago
> Parking prohibited in a street works: you have to wait for vehicles to go or eliminate them, nobody goes back to park.

I'm not sure what to do in this instance; if we just randomly moved them somewhere else, the parked cars might end up in a place that owners can not access (there is a longstanding nightmare issue with ditched/abandoned cars).

**Comment by aubergine10** [comment]
> **Bobbo662** 5 hours ago 
> Just noticed the No Parking isn't work - here's a screen shot. 
>  
> https://steamcommunity.com/profiles/76561198030920207/screenshot/789737583030397107

![image](https://user-images.githubusercontent.com/1386719/61914409-748df300-af38-11e9-84f4-3c92ee69ebd3.png)
