### ISSUE TITLE
Fast roads/tracks reported as 140 km/h

### ISSUE THREAD

**Issue by aubergine10** [krzychu124/Cities-Skylines-Traffic-Manager-President-Edition#446]
Due to the way speed signs work in 10.21 and above, anything between 138 and 950 km/h will be shown as 140 km/h.

This is confusing for users, as previously (10.20 and below) they'd see the 'unlimited' sign for anything _above_ ~130 km/h.

Example feedback from a Steam user:

> **Termite** 3 hours ago 
> Why is the highest default speed limit only 140km instead of unlimited as in the stable version? I asked the same question on the labs page.

**Comment by krzychu124** [comment]
I would say, it's not a bug but feature 😄 Now it shows a little bit more real speed of road/track

**Comment by kvakvs** [comment]
Current behaviour, speeds which cannot be represented by available speed signs are mapped to 140 (or 90 mph) all the way up to 950 km/h. Anything over 950 km/h becomes unlimited.
Old behaviour in 10.20: Speeds over 130 become unlimited.

Oneline fix https://github.com/krzychu124/Cities-Skylines-Traffic-Manager-President-Edition/blob/master/TLM/TLM/UI/TextureResources.cs#L261

**Comment by aubergine10** [comment]
Assuming we want to keep 140 speed as 140 sign, above what speed should we consider it unlimited? 143?

**Comment by dymanoid** [comment]
I would really miss the most beloved sign of the German Autobahn...

**Comment by kvakvs** [comment]
I'm OK to restore the previous behaviour, it is 1-line fix

**Comment by aubergine10** [comment]
Copied from the PR:

> Now clicking ⬅ on 5 mph (10 km) will show 🚫 and wrap over to 90 mph (140 km)  
> Now clicking ➡ on 90 mph (140 km) will show 🚫 and wrap over to 5 mph (10 km)

Where 🚫 = "no limit" speed sign (eg. white circle with black stripe for German/UK signs)
