### ISSUE TITLE
Settings from stable (10.20) not picked up by v11

### ISSUE THREAD

**Issue by aubergine10** [krzychu124/Cities-Skylines-Traffic-Manager-President-Edition#447]
Note: This could be duplicate mod issue, I've asked user to check.

> **Termite:**
> Also noticed another thing. Any per game settings or changes to junctions etc done in the stable do not seem to get picked up by alpha.

**Comment by aubergine10** [comment]
> **Termite** 32 minutes ago 
> No only one version subscribed. But I will try a restart to see if it works.

**Comment by aubergine10** [comment]
Had a user reporting same issue on LABS v10.21.1 so it could possibly be an issue that something from 10.20 or earlier is causing load error on 10.21 and later?

* [output_log.txt](https://drive.google.com/file/d/1RUO-HQAP0HZeLwTM2V6b3kqcf2k4UgAa/view)
* [TMPE.log](https://drive.google.com/file/d/1f5OfvfYibf3EaRl71fdYra6VIouuV_WT/view)

Did we add or change any settings in 10.21 and above?

**Comment by aubergine10** [comment]
From output log above:

```log
[Warning] @ 3694829667 SpeedLimitManager.OnBeforeLoadData: NetInfo @ 71 is null!
   at CSUtil.Commons.Log.LogToFile(System.String log, LogLevel level)
   at CSUtil.Commons.Log.Warning(System.String s)
   at TrafficManager.Manager.Impl.SpeedLimitManager.OnBeforeLoadData()
   at TrafficManager.State.SerializableDataExtension.OnLoadData()
   at SerializableDataWrapper.OnLoadData()
   at SimulationManager.LateUpdateData(UpdateMode mode, Single minProgress, Single maxProgress)
   at SimulationManager.Managers_LateUpdateData(UpdateMode mode, Single minProgress, Single maxProgress)
   at LoadingManager+<LoadSimulationData>c__IteratorB.MoveNext()
   at AsyncTask.Execute()
   at SimulationManager.SimulationStep()
   at SimulationManager.SimulationThread()

[Warning] @ 3694895597 SpeedLimitManager.OnBeforeLoadData: NetInfo @ 72 is null!
   at CSUtil.Commons.Log.LogToFile(System.String log, LogLevel level)
   at CSUtil.Commons.Log.Warning(System.String s)
   at TrafficManager.Manager.Impl.SpeedLimitManager.OnBeforeLoadData()
   at TrafficManager.State.SerializableDataExtension.OnLoadData()
   at SerializableDataWrapper.OnLoadData()
   at SimulationManager.LateUpdateData(UpdateMode mode, Single minProgress, Single maxProgress)
   at SimulationManager.Managers_LateUpdateData(UpdateMode mode, Single minProgress, Single maxProgress)
   at LoadingManager+<LoadSimulationData>c__IteratorB.MoveNext()
   at AsyncTask.Execute()
   at SimulationManager.SimulationStep()
   at SimulationManager.SimulationThread()
```

**Comment by krzychu124** [comment]
I don't see the problem, everything was loaded correctly, no errors...
```cs
Initialization done. Loading mod data now.
[Info] @ 3769125080 Loading Data from New Load Routine! Length=1437385
[Info] @ 3785316010 Loading State from Config
[Info] @ 3785375013 Loading 12339 extended citizens
[Info] @ 3785750708 Loading 22137 extended citizen instances
[Info] @ 3785880572 Priority segments data structure (old) undefined!
[Info] @ 3785941471 Loading 51 priority segments (new method)
[Info] @ 3786081451 Loading parking restrictions data. 2 elements
[Info] @ 3786144699 Loading lane vehicle restriction data. 28 elements
[Info] @ 3786247233 Loading 12 timed traffic lights (new method)
[Info] @ 3786993031 Loading junction traffic light data (old method)
[Info] @ 3787067079 Loading toggled traffic lights (new method)
[Info] @ 3787122885 Lane arrow data structure (old) undefined!
[Info] @ 3787188394 Loading lane arrow data (new method)
[Info] @ 3787422637 Loading 373 lane connections
[Info] @ 3787946911 Loading custom default speed limit data. 0 elements
[Info] @ 3788014412 Loading lane speed limit data. 0 elements
[Info] @ 3788072917 Loading junction restrictions. 108 elements
[Info] @ 3829657903 OnLoadData completed successfully.
```

**Comment by krzychu124** [comment]
`NetInfo @ 71 is null!` looks like invalid/missing road network asset

**Comment by aubergine10** [comment]
Possibly related - @kianzarrin mentioned this in discord:

> biffa says upgrading to TMPE Labs will remove all traffic rules:
> https://youtu.be/_TdEIarNXWk?t=271

**Comment by aubergine10** [comment]
Looks like the issue is due to the "zombie assemblies" bug: https://github.com/krzychu124/Cities-Skylines-Traffic-Manager-President-Edition/issues/211#issuecomment-507416088

Only way the reported issue has been reproduced so far is as follows:

> @kianzarrin :
> Regarding the loss of the data when migrating from TMPE stable to labs...  
> Short version: when migrating to TMPE labs, you must restart the game before loading the save again.
> Long version: I did some tests and manage to reproduce the problem - Steps to reproduce:
> 1. uninstall all mods.
> 2. install TMPE stable
> 3. create a new city with one junction.
> 4. setup some junction restrictions.
> 5. save the city
> 6. exit to main menu.
> 7. uninstall TMPE stable
> 8. install TMPE labs
> 9. load the saved game from main menu (do not exit to desktop)
> 10. all traffic rules that I had setup were gone!
> 11. Exit to desktop WITHOUT saving. (If you save here I suspect you will loose your data > permanently.)
> 12. run the game and load the same city again.
> 13. all traffic rules are there

**Comment by aubergine10** [comment]
Both LABS and ALPHA workshop pages have been updated to make it clearer that exit to desktop is required after changing between versions.
