### ISSUE TITLE
Cargoload of trains/trucks

### ISSUE THREAD

**Issue by Sipke82** [krzychu124/Cities-Skylines-Traffic-Manager-President-Edition#45]
* Fix that cargo trains drive with around with really low loads of cargo. (1 - 30 %)
* Automatically select appropriate vehicle for load --> a van for a small load, a truck for a large load. (i've made difference in capacity in AVO, sadly i get trucks loaded for 50%, instead of a van, loaded for 100%), while vans would probably mean faster delivery.

**Comment by aubergine10** [comment]
Related issues from original repo:

* https://github.com/VictorPhilipp/Cities-Skylines-Traffic-Manager-President-Edition/issues/136
* https://github.com/VictorPhilipp/Cities-Skylines-Traffic-Manager-President-Edition/issues/123

**Comment by aubergine10** [comment]
Is this is outside scope of TMPE? It's not anything to do with roads or rails, it's primarily about goods vehicles.

IMO a separate Cargo Vehicles Manager mod of some kind would be better place for such enhancements.

**Comment by krzychu124** [comment]
Yes, it is 👍
