### ISSUE TITLE
v11 - Possible issue with trains

### ISSUE THREAD

**Issue by aubergine10** [krzychu124/Cities-Skylines-Traffic-Manager-President-Edition#452]
> tenderloveheart 3 hours ago 
> Asking for bugs problems, added V11 to my current game, after unsubbing from labs. Parking AI works with Parking lots 90 degree by bad.... 
>  
> Problem with asset trains from https://steamcommunity.com/sharedfiles/filedetails/?id=684699512 
> and cargo hold fix... Before with labs, train network ran with a great mix of trains, and did not clog up... with alpha, train network quickly clogged up with almost empty trains. Unsubbed from all the AFT trains I was using, and the sub mod vehicle effects, and the plug in, let the game run, spawning vanilla trains, and the train network is back to running with almost full trains. 
> 
> Save game with the AFT trains...
> https://steamcommunity.com/sharedfiles/filedetails/?id=1813127324

I've asked for log files.

**Comment by TLHeart60** [comment]
Here are the log files you requested, from Tenderloveheart on Steam Here I am TLHeart60
[TMPE.log](https://github.com/krzychu124/Cities-Skylines-Traffic-Manager-President-Edition/files/3425387/TMPE.log)
[output_log.txt](https://github.com/krzychu124/Cities-Skylines-Traffic-Manager-President-Edition/files/3425389/output_log.txt)

**Comment by TLHeart60** [comment]
Tested alpha 4 with the same save file that had the train problems being jammed up, with low cargo.  Cargo train jam has cleared, and trains are back to running near full.

**Comment by aubergine10** [comment]
Great news! Thanks for the update! If the problem happens again, please let us know.

**Comment by krzychu124** [comment]
Yeah, I couldn't reproduce that issue yesterday :wink:
