### ISSUE TITLE
v11 - Trace in RELEASE build

### ISSUE THREAD

**Issue by aubergine10** [krzychu124/Cities-Skylines-Traffic-Manager-President-Edition#454]
Some Trace is being logged in `TMPE.log` in the v11 `RELEASE` build (built from `master` branch prior to #451 merge).

```
Trace 185.2295256: TrafficLightSimulation.Update(): called for node 2623
Trace 186.6951208: TrafficLightSimulation.Update(): called for node 4469
Trace 186.7477688: TrafficLightSimulation.Update(): called for node 5008
Trace 186.7613966: TrafficLightSimulation.Update(): called for node 9883
```

Full log, savegame, etc., can be found in #452

**Comment by kvakvs** [comment]
I'll pay Log class a visit in a couple hours

**Comment by TLHeart60** [comment]
Still have the trace showing up in my log file. Don't know if the V11 alpha 6 has been updated to remove those... and for information, all of those traces are for traffic lights that have more than one node to control.
[TMPE.log](https://github.com/krzychu124/Cities-Skylines-Traffic-Manager-President-Edition/files/3536220/TMPE.log)

**Comment by kvakvs** [comment]
Sub-project TMPE.API has TRACE defined for Release build.

**Comment by aubergine10** [comment]
I'll push another v11 alpha to workshop tonight with the trace removed. Thanks @kvakvs and thanks for the report @TLHeart60 👍
