### ISSUE TITLE
Error code when starting Campus DLC

### ISSUE THREAD

**Issue by shexx** [krzychu124/Cities-Skylines-Traffic-Manager-President-Edition#477]
### Description
Error: cannot cast from source type to destination type.
This shows up when I try to plop an administrative building for any of the campuses. Varsity does not have this problem. I use a lot of Mods and I have checked most of them one by one but the error still shows up and I have confirmed that vanilla game works so I can't seem to find the issue. Any help is appreciated plss!!

### Reproduction Steps
1. Load savegame
2. Paint campus area.
3. Put down Administrative building, error then pops up. See screenshot below

Note: I have done this with a new game and the error pops up.

### Mod List
file:///D:/New%20folder/SteamLibrary/steamapps/common/Cities_Skylines/Mods.html

### Output Log

[output_log.txt](https://github.com/krzychu124/Cities-Skylines-Traffic-Manager-President-Edition/files/3464779/output_log.txt)

### Screenshots (Optional)

https://steamcommunity.com/sharedfiles/filedetails/?id=1824707234

**Comment by shexx** [comment]
[output_log.txt](https://github.com/krzychu124/Cities-Skylines-Traffic-Manager-President-Edition/files/3464778/output_log.txt)
More up to date

**Comment by aubergine10** [comment]
You have 'Improved Public Transport 2' and 'Transport Lines Manager' - they are incompatible - use one, unsubscribe the other.

There are problems with your graphics card. Make sure the drivers are updated to latest versions from vendor website. Also add `-force-d3d9` [launch option](https://steamcommunity.com/sharedfiles/filedetails/?id=466981085).

You have 'Network Skins' and 'Road Color Changer' mods installed - they are incompatible - use one, unsubscribe the other.

Try disabling the 'Optimise thumbnails' option in Loading Screen Mod options.

**Comment by shexx** [comment]
Thank you for the suggestions, I have applied all of them. The problem still persists

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by aubergine10** [comment]
Upload your latest output_log.txt

**Comment by shexx** [comment]
[output_log.txt](https://github.com/krzychu124/Cities-Skylines-Traffic-Manager-President-Edition/files/3478724/output_log.txt)

**Comment by aubergine10** [comment]
Summary of remaining errors:

* Still a huge number of graphics card errors (the `-force-d3d9` helped a little, but did not fix).
    * Did you manually update graphics drivers to latest version direct from manufacturer website? If not, do, then try again. If you did, however, considering how many errors remain, it's time to invest in a new graphics card.
* Lots of Campus related errors in game
* Bunch of Harmony errors while exiting game

For the campus errors, I suspect one of the following mods:

* [Favorite Cims](https://steamcommunity.com/sharedfiles/filedetails/?id=426460372)
* [Employ Overeducated Workers](https://steamcommunity.com/sharedfiles/filedetails/?id=1674732053) - use vanilla game "Industry 4.0" city policy instead
* [More Outside Interaction](https://steamcommunity.com/sharedfiles/filedetails/?id=1706703944)
* [Real City](https://steamcommunity.com/sharedfiles/filedetails/?id=1192503086)

Try disabling the mods above, then exit to desktop, then relaunch game and see if it works better.

For the other errors, I suspect one of the following mods:

* [Electric Roads](https://steamcommunity.com/sharedfiles/filedetails/?id=1689984220)
* [Automatic Bulldoze v2](https://steamcommunity.com/sharedfiles/filedetails/?id=639486063) - use [Bulldoze It](https://steamcommunity.com/sharedfiles/filedetails/?id=1627986403) instead

Again, try disabling them, then exit to desktop, then relaunch game and see if it works better.

There's a bunch of other mods that could potentially cause issues - if game still not working, try disabling these, then exit to desktop, then relaunch game:

* [Improved Content Manager](https://steamcommunity.com/sharedfiles/filedetails/?id=814498849)
* [Minimap](https://steamcommunity.com/sharedfiles/filedetails/?id=439021806)
* [Advanced Junction Rule](https://steamcommunity.com/sharedfiles/filedetails/?id=1647686914)
* [Advanced Traffic Congestion Report](https://steamcommunity.com/sharedfiles/filedetails/?id=1651036644)
* [Power Balance](https://steamcommunity.com/sharedfiles/filedetails/?id=489636701)
* [Real Gas Station](https://steamcommunity.com/sharedfiles/filedetails/?id=1623509958)
* [Real Construction](https://steamcommunity.com/sharedfiles/filedetails/?id=1614061108)
* [Heavy Outside Traffic](https://steamcommunity.com/sharedfiles/filedetails/?id=1596838226)

**Comment by shexx** [comment]
Ok, I'll try the suggestions, the graphics is new so maybe my driver installation was faulty. I'll have a look at that, thank you

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by shexx** [comment]
I believe I found the mod causing the issue. It was the Real Construction Mod. Thank you for the help on finding the problem. Very much appreciated.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________
