### ISSUE TITLE
Lang_hu.txt

### ISSUE THREAD

**Issue by JozsefHUNGepiM** [krzychu124/Cities-Skylines-Traffic-Manager-President-Edition#491]
[lang.hu.txt](https://github.com/krzychu124/Cities-Skylines-Traffic-Manager-President-Edition/files/3505571/lang.hu.txt)

**Comment by JozsefHUNGepiM** [comment]
lang_hu.txt
AVAILABLE_LANGUAGE_CODES.Add("hu");
LANGUAGE_LABELS["hu"] = "Hungarian";

**Comment by aubergine10** [comment]
I'll send a PR shortly

**Comment by aubergine10** [comment]
@JozsefHUNGepiM I've set the display language (in the Language drop-down list in TM:PE mod options) to `Magyar` is that correct?

**Comment by JozsefHUNGepiM** [comment]
Yes, Hungarian = Magyar

**Comment by JozsefHUNGepiM** [comment]
Sorry.
line break was bad
I corrected.
New txt
[lang.hu.txt](https://github.com/krzychu124/Cities-Skylines-Traffic-Manager-President-Edition/files/3505835/lang.hu.txt)

**Comment by aubergine10** [comment]
Ah, it's ok just fixed them :)

**Comment by JozsefHUNGepiM** [comment]
Thanks

**Comment by aubergine10** [comment]
Thanks for the contribution - it will be published in the next update to TM:PE :)
