### ISSUE TITLE
Auto-config traffic lights (single junction)

### ISSUE THREAD

**Issue by aubergine10** [krzychu124/Cities-Skylines-Traffic-Manager-President-Edition#5]
> Note: Would require #4 to be implemented

A quick way to auto-configure traffic light sequence at a single junction would factor in the following:

1. Road priority, determined as a function of:
    * Priority flag set on a named road (road info panel in vanilla game)
    * Number of lanes (more = higher priority)
    * Speed of road and/or lane (faster = higher priority)
    * Width of road and/or lane (wider = higher priority)
2. Conflict point minimisation (see #4)
3. Amount of traffic per lane or segment? (TM:PE already includes some metrics on this stuff?)

This would be hugely beneficial to casual players, and also useful starting point for advanced players who want a decent starting point for their traffic light sequence.

Obviously, easier said than done, but  would be a good coding challenge (:

**Comment by aubergine10** [comment]
The calculations would be triggered whenever a traffic light is added to a junction, for example:

* user connects small road to large road causing lights to appear
* user manually enables traffic lights ('info views > traffic routes > junctions tab')
* user toggles lights via TM:PE panel (somewhat redundant feature of TM:PE imo)

**Comment by aubergine10** [comment]
Would solve: https://github.com/VictorPhilipp/Cities-Skylines-Traffic-Manager-President-Edition/issues/28

**Comment by aubergine10** [comment]
Related discussion from original mod: https://github.com/VictorPhilipp/Cities-Skylines-Traffic-Manager-President-Edition/issues/200

**Comment by aubergine10** [comment]
Github user @brazenest posted following in old issue tracker https://github.com/VictorPhilipp/Cities-Skylines-Traffic-Manager-President-Edition/issues/200#issuecomment-475967281 :

> I really want to see this feature. It'll be a game-changer for C:S and TMPE, because it would formalize a component of real-world engineering that is most conspicuously absent from vanilla imho. (This game is literally all about traffic management and paying attention to locations of things with respect to each other. How does C:S consciously overlook realistic traffic signal phasing?)
>  
> The key is to codify the NEMA ring-and-barrier phase diagrams (https://ops.fhwa.dot.gov/publications/fhwahop08024/chapter4.htm#4.2).
>  
> Those would address the majority of cases. Sure, the game prefers against dedicated turn lanes... so for now we exclude phases meant for dedicated turns. From that point, I want to see what the users report are the next common and/or exceptionally troublesome cases we should solve next.
>  
> I'm rusty on C(#) but I'm super willing to work on this feature. My cities need more traffic intelligence :)

and...

> NEMA phases (https://ops.fhwa.dot.gov/publications/fhwahop08024/chapter4.htm#4.2) are a formal expression of how to address conflict points and merge points in traffic signaling. We do need the deeper algorithmic solution for non-trivial cases, though.
>  
> One example: Dead reds. They occur notably when there's at least one direction of travel that is denied to all traffic moving through the intersection. If you technically could make a protected turn but your lane has no signal yet to permit it, you're at a dead red light.
>  
> To smartly eliminate that dead time, we could allocate greens in a way that looks like magic. The default could aim to achieve a balance of equal green time to every direction. Or we could run a greedy version in cases where we want to prioritize the apportionment.
>  
> > Ultimately, the player should be designing their roads so as to reduce crossing and merging points wherever possible.
>  
> ... which is why TMPE is there to help them along their journey of knowledge :)

**Comment by brazenest** [comment]
I'll work on this feature when time permits.

**Comment by aubergine10** [comment]
While it doesn't include conflict point detection, #540 will improve traffic lights to a point where we could consider #5 complete.
