### ISSUE TITLE
Unable to push images to wiki

### ISSUE THREAD

**Issue by aubergine10** [krzychu124/Cities-Skylines-Traffic-Manager-President-Edition#50]
I can edit pages in the wiki tab, but can't push updates to it via git command line  or desktop. The only way to put images in the wiki (rather than kludges that require hosting elsewhere) is via git push.

Can I get additional access privs (collaborator)?

**Comment by krzychu124** [comment]
Yup, I've just sent an invite :smiley:

**Comment by aubergine10** [comment]
Looks like github's new API is bit fubar since the launch of the Atom-based github desktop, and I can't find a working link to the classic app (again, api changes).

Basically in the new API they forgot about github wikis :/`

For time being the wiki will likely be image-less. I'll update this ticket when the api / desktop issues are resolved.

**Comment by krzychu124** [comment]
Ok, thanks for information

**Comment by aubergine10** [comment]
Some progress: The issue has been confirmed and lots of other users reporting it (see issue linked in opening post at link below): https://github.com/desktop/desktop/issues/6811

There are some workarounds, but I'll probably wait for API update for now, and instead focus on getting the bulk of the text finished.
