### ISSUE TITLE
[Task] Low hanging UI performance fruits

### ISSUE THREAD

**Issue by kvakvs** [krzychu124/Cities-Skylines-Traffic-Manager-President-Edition#520]
### Describe your idea

For tools which edit nodes and segments, add code to cache the visible nodes and segments and not recalculate them until the camera moves.

For speed limit tool apply similar improvement
[17:32] aubergine18: when the main speed limit tool is active, it iterates all segments, and for each one does a big bunch of checks to see if it's visible, if it can handle speed limits, etc
[17:32] aubergine18: well, if cached, yes, it would be one time only
[17:32] aubergine18: but it's not currently cached from what I can see

**Comment by aubergine10** [comment]
Actually, looking at code again, there is some degree of caching I think - `currentlyVisibleSegmentIds` @ https://github.com/krzychu124/Cities-Skylines-Traffic-Manager-President-Edition/blob/master/TLM/TLM/UI/SubTools/SpeedLimits/SpeedLimitsTool.cs#L146

**Comment by Strdate** [comment]
I was copying some TMPE code for my own mod and yes, the signs were cached (in particular parking signs)

**Comment by kvakvs** [comment]
First experiment:
Caching node ids while the camera is not moving, for Lane Connectors tool.
Master build will re-filter the nodes every time and lose 12-17ms per frame.
With cache changes nodes only re-filter when camera is moved, and that just takes 1-2 ms per frame.

**Comment by aubergine10** [comment]
Here's another low fruit: https://github.com/krzychu124/Cities-Skylines-Traffic-Manager-President-Edition/blob/master/TLM/TLM/UI/MainMenu/StatsLabel.cs

When the path find stats display is not active, it should not do anything. Even when it is active, it should avoid using `Update()` on a UI component. Ideally the UI should be disabled and not visible when not in use.

For compatibility with the FPS Booster mod, we should avoid any `Update()` on UI components (except panels which still retain the base method).
