### ISSUE TITLE
Cannot normally get using game language in 11.0 Third-party local translation.

### ISSUE THREAD

**Issue by TianQiBuTian** [krzychu124/Cities-Skylines-Traffic-Manager-President-Edition#533]
### In 11.0 alpha version, TM:PE Cannot normally get using game language in using Third-party local translation mods.
(e.g.: https://steamcommunity.com/sharedfiles/filedetails/?id=812789818)

**But can normally in STABLE(10.20) and LABS(10.21.1).**

### Screenshots:

In STABLE(10.20):
![20191019162623_1](https://user-images.githubusercontent.com/26628474/67140535-169a4e80-f28e-11e9-97bc-ce14288c8616.jpg)

In LABS(10.21.1):
![20191019155632_1](https://user-images.githubusercontent.com/26628474/67140540-274ac480-f28e-11e9-87e7-286713c5dbf1.jpg)

In Alpha(11.0):
![20191019153845_1](https://user-images.githubusercontent.com/26628474/67140545-2f0a6900-f28e-11e9-9d50-6867dc47e30b.jpg)

**Also, please review my Simplified Chinese in Crowdin. Because some translation is not correct in 11.0 version.**

**Comment by aubergine10** [comment]
TMPE contains it's own translation system - see: https://github.com/krzychu124/Cities-Skylines-Traffic-Manager-President-Edition/wiki/Languages

**Comment by TianQiBuTian** [comment]
Yea. But this is choose same as "Game language", and using local translation mods. It will only display the code.
This bug doesn't appear in STABLE and LABS versions. Only 11.0 alpha had this bug.

**Comment by aubergine10** [comment]
I've just tested all the languages in TM:PE and they all work as expected.

The bug is in those translation mods, not TM:PE. The authors of the external translation mods need to update their mods.

**Comment by aubergine10** [comment]
For reference, here are the changes that were made to TM:PE when we moved to new translation system:

https://github.com/krzychu124/Cities-Skylines-Traffic-Manager-President-Edition/pull/509/files

**Comment by TianQiBuTian** [comment]
I think this bug isn't caused by translation mods, because using translation mods in STABLE and LABS version don't had this bug, only 11.0 alpha version had this bug.
Maybe is new translation system doesn't load those Third-party translation mods. (idk)

**Comment by aubergine10** [comment]
I don't think the older versions loaded anything from the translation mods either. The translation mods must be altering TM:PE somehow and seeing as we've altered the translation system those mods are breaking.

Is there any reason the translations aren't just added directly to TM:PE? We can add local/regional dialects, as many languages as desired...

Also, I think @krzychu124 is investigating what those translation mods do to see how they work.

**Comment by krzychu124** [comment]
Correction of game language name was missing(in case of using custom language file).
PR #534 should fix the issue.

**Comment by aubergine10** [comment]
It would be better if those mods specified correct language - otherwise they'll break any other mod that has inbuilt localisation (eg. @klyte45 mods).

**Comment by krzychu124** [comment]
Mentioned mod is creating new `locale` file with key `zh-cn`, 
CO created locale exporter for modders to help creating new locale files.
Game is loading all files with `.locale` extension from `Locale` folder so any file which pass validation stage is registered and available in-game "out of the box".

**Comment by aubergine10** [comment]
I'll push an update to the v11 workshop page later today.
