### ISSUE TITLE
Shortcut for separate turning lanes 

### ISSUE THREAD

**Issue by kianzarrin** [krzychu124/Cities-Skylines-Traffic-Manager-President-Edition#537]
Hi,
when fixing traffic jams in my cities using TMPE I believe adding shortcuts for the following common scenarios can save a lot of time:
A) separate turning lanes. This is particularly useful in gridlocks to help cars who want to go toward directions without traffic jams avoid waiting behind cars who want to go towards directions where traffic is jammed.
![skylines lane separation addon](https://user-images.githubusercontent.com/26344691/68017382-43436280-fc9f-11e9-91e4-40f39e5a3420.png)
Selecting every segment and then modifying every lane can be time consuming I have created a mod that separates turning lanes with by ctrl+click or alt-click.

see also: #539 #540 #541 

~~B) fixing roundabout rules with one click: people use a lot of roundabouts in their cities. the vanilla roundabout can get a massive boost if pimped by traffic manager. while the roundabout mod automatically adds TMPE rules when creating them, I still want to be able to add traffic rules after creating roundabouts for example because I might modify my roundabout or I am trying to fix other peoples cities.
I am planning to add a simple shortcut to fix all the traffic rules for a roundabout with one click.
I prefer to avoid adding a roundabout tool to traffic manager. I think its best to use the already existing junction priority tool. select the tool and then press alt+shift+click on  a round about to do all of the following:
 give way entering the roundabout
 enter blocked junctions if you are already on the roundabout
 enter blocked junctions if you are entering the roundabout
 separate turning lanes on the roundabout
 choose lanes when entering the roundabout in cases where highway rules apply.
 no lane changing in the nodes in the roundabout (using lane connection tool).
 etc
I also wish to add options so that people can individually choose any of these features.~~
 
~~C)add automatic timed traffic lights:
people spend a tone of time to add timed traffic lights. i suggest to add a default time traffic lights which allows one road to go through at a time and automatically modifies the turning lanes all with one click would be a massive help.~~

~~D) in real life and also in simcity when a small road joins a main avenue, the separation barrier in the middle remains unbroken and people can only turn right (the only advantage of simcity over cities skylines!!!). we already have an asset that visually conserves the junction barrier in such situations 
![previewfile_1319965985](https://user-images.githubusercontent.com/26344691/68018787-b4d0e000-fca2-11e9-8b6e-300a10667370.png)
But TMPE is required to make it function as it should. It can be a bit tedious to apply all the traffic rules particularly when fixing other peoples cities where many minor roads are joining one avenue. so i suggest a shortcut. choose junction priority  tool then hold ctrl to set all rules regarding the above scenario:
 remove zebra crossings on the avenue
 cars on the avenue can enter block junctions
 no left turns
 give way entering the avenue~~

**Comment by kvakvs** [comment]
This would go into Usability section.
But each of your suggestions are not trivial, so if this is accepted we will have to go through each suggestion, make one ticket per each suggestion, discuss UX where the GUI for that will go, and discuss desired behaviour, and then you or one of us can implement.

For example separate turning lanes will have to check if there are enough lanes for all outgoing roads, otherwise it will try to combine some arrows in one lane. And knowing the direction is not trivial either, each direction is an arc approx. 90° but there's logic for that somewhere in the code, for those arcs.

**Comment by kianzarrin** [comment]
@kvakvs I am going to fix all of these myself. I opened this issue mainly for discussions. I spoke on discord with @krzychu124 and he told me to open issue[s] and make pull requests.

> separate turning lanes will have to check if there are enough lanes for all outgoing roads
sure. I already have fixed the lane arrow thing and am about to make a pull request. I even went as far as distributing the number of lanes in each direction in proportion to the sizes of the roads attached in my fix and consideration to left hand and right hand drive as well. if there are left over lanes (when dividing by proportions) then the right lane gets less lanes because its easy to turn right.

One Issue is of there are more source lanes than target lanes in which case there is not much I can do to avoid lanes merging. giving more lanes to the left turn means there is possibility for u turn [i think].

**Comment by kianzarrin** [comment]
Can you assign this to me please

**Comment by kvakvs** [comment]
Please make as small pull requests as possible one per feature.

**Comment by krzychu124** [comment]
Yes, I said that would be good to open issue before you create pull request and I thought you will create one for each suggested features :grin: 
As @kvakvs said you should split this issue, so extract everything which is not related to your current pull request to a new issue[s] :smiley: 
It will be easier for us to track progress, discuss about changes and it will help to organize all info in one place.
Keep PR as small as possible and KISS :wink:
