### ISSUE TITLE
Shortcut for fixing all round about rules in one click

### ISSUE THREAD

**Issue by kianzarrin** [krzychu124/Cities-Skylines-Traffic-Manager-President-Edition#539]
people use a lot of roundabouts in their cities. the vanilla roundabout can get a massive boost if pimped by traffic manager. while the roundabout mod automatically adds TMPE rules when creating them, I still want to be able to add traffic rules after creating roundabouts for example because I might modify my roundabout or I am trying to fix other peoples cities.
I am planning to add a simple shortcut to fix all the traffic rules for a roundabout with one click.
I prefer to avoid adding a roundabout tool to traffic manager. I think its best to use the already existing junction priority tool. select the tool and then press alt+shift+click on a round about to do all of the following:
- give way entering the roundabout
- enter blocked junctions if you are already on the roundabout
- enter blocked junctions if you are entering the roundabout
- separate turning lanes on the roundabout
- choose lanes when entering the roundabout in cases where highway rules apply.
- no lane changing in the nodes in the roundabout (using lane connection tool).
- etc
I also wish to add options so that people can individually choose any of these features.

**Comment by kianzarrin** [comment]
please assign to me.

**Comment by kianzarrin** [comment]
I am thinking that I can write code that auto detects a roundabout when we use priority tool>shift+click

**Comment by krzychu124** [comment]
> I am thinking that I can write code that auto detects a roundabout

That will be the hardest part :)

**Comment by aubergine10** [comment]
Random thoughts:

* Assuming roundabouts are always 1-way roads, that could help filter out _some_ segments at junctions?
* There is also the curvature of roundabouts - given a starting segment, and knowing which side traffic drives on, you could perhaps use that to help identify segments that are part of roundabout?
* Not all roundabouts are round; some have strange shapes such as being more oval, etc.
* I've seen several instances - both in-game and in real life - where two roundabouts connect to each other. In real life, good examples can be found by googling "magic roundabout road".
* Sometimes nodes on roundabouts can have traffic lights on some or all of the entrances to roundabout.

As an example of something that might prove difficult to detect, take this concoction from a city I'm currently making:

![image](https://user-images.githubusercontent.com/1386719/68059240-b1197980-fcf3-11e9-93e6-240dd058c1a1.png)

It started out as two roundabouts (one around the train station, and one around the park) which were merged together, sharing a straight section of road (between park and station). I've since changed some of the road around station to two-way to make traffic more fluid, but the 'oval-about' around the park is still one-way and acts as roundabout.

In cases where roundabouts can be detected, it would be good if the segments could be highlighted to give some visual conformation to user as to which part of their road network will be affected.

However, it might also be beneficial to have an option to allow users to define which segments comprise the roundabout. For example, here I've used routes tool to turn the roundabout in to a named route:

![image](https://user-images.githubusercontent.com/1386719/68059442-6f3d0300-fcf4-11e9-8232-eb11553a48fd.png)

As for what happens at the junctions:

* I assume you mean "yield" when entering the roundabout (ie. if no oncoming traffic the vehicle doesn't have to wait, unless there is a traffic light without an active 'turn on red').
    * It would be worth checking that the 'Yield' sign interacts properly with 'enter blocked junctions' in this scenario
* For junctions with traffic lights, could possibly have two mod options in an "At roundabouts" section on the Policies tab in mod options:
    * Vehicles leaving the roundabout can turn on red
    * Vehicles entering the roundabout can turn on red
* Separate turning lanes are good, but there also needs to be opportunities for vehicles to change lanes within the roundabout (depending on how small it is, whether there are nodes between junctions, etc).
    * Could possibly just limit to 1 lane change per node? (in other words: vehicle can move in to adjacent lane if desired)

Possibly related issues:

Tagging #472 , #73 , #424 , https://github.com/krzychu124/Cities-Skylines-Traffic-Manager-President-Edition/issues/41#issuecomment-462362185

**Comment by kianzarrin** [comment]
@krzychu124  @aubergine10 
Guys take it easy! TMPE already can find a roundabout! look:
![round about](https://user-images.githubusercontent.com/26344691/68062226-b4236280-fd11-11e9-8eaa-617bbeda5cd1.png)

**Comment by kianzarrin** [comment]
@aubergine10 
The objective of this issue is to setup traffic rules for common roundabouts with one click and save time. I will be using already existing features of TMPE. Adding more features to TMPE should be under a different issue. rare and exceptional situations can always use manual tweaking of traffic rules using TMPE. That said I am all for adding cool features. but it should be done under different issue.

>It would be worth checking that the 'Yield' sign interacts properly with 'enter blocked junctions' in this scenario

I use a lot of roundabouts with the rules I have suggested so I am certain yeild +enter blocked junctions works just fine in this scenario. :)

>For junctions with traffic lights, could possibly have two mod options in an "At roundabouts" section on the Policies tab in mod options:
Vehicles leaving the roundabout can turn on red
Vehicles entering the roundabout can turn on red

I don't think adding traffic lights to roundabout is a good idea. In any case I think you might have misunderstood me. What I intend to do is to shift+click on the round about to setup common traffic rules for a normal roundabout. Why should it add a traffic light? You can of course add traffic light manually using TMPE. TMPE junction restriction tool can allow you to do right turn on red if you like. 

>Separate turning lanes are good, but there also needs to be opportunities for vehicles to change lanes within the roundabout (depending on size and complexity, and whether there are nodes between junctions, etc).
Could possibly just limit to 1 lane change per node? (in other words: vehicle can move in to adjacent lane if desired)

In options you can define which one of these rules you like and which one you don't like. I personally don't like changing lanes in roundabout in this game. I don't think cars change more than one lane anyway. Just to be clear I am taking about changing lane on nodes without junctions and two segments with same number of lanes. and I intend to achieve it by using the lane connection tool.

**Comment by kianzarrin** [comment]
@aubergine10
> it might also be beneficial to have an option to allow users to define which segments comprise the roundabout.
Wow that's a good idea. Never though of that. This is what TMPE does already. 
![semi roundabouts](https://user-images.githubusercontent.com/26344691/68063004-95739a80-fd16-11e9-9864-4438b922a983.png)
![round about segment](https://user-images.githubusercontent.com/26344691/68063063-e7b4bb80-fd16-11e9-897a-4e24971c7b25.png)
![hover issue long road](https://user-images.githubusercontent.com/26344691/68063068-ebe0d900-fd16-11e9-9fc0-69685561d524.png)
![hover issue long road2](https://user-images.githubusercontent.com/26344691/68063008-986e8b00-fd16-11e9-8b23-564c1acffd33.png)

Not what you wanted. I will raise another issue to fix this. I prefer to keep my changes small.

**Comment by kianzarrin** [comment]
@aubergine10 Before raising the issue about road segments I need to give this some though. But if you like you can go ahead and do the honors :)

**Comment by kianzarrin** [comment]
@aubergine10 
>it might also be beneficial to have an option to allow users to define which segments comprise the roundabout.

By the way its possible to use #541  #537 on a roundabout to setup rules for each junction individually and that mostly does the job :)

**Comment by kianzarrin** [comment]
#7 is also related to this

**Comment by kianzarrin** [comment]
A bit of progress on the roundabout rules.
![Screenshot (12)](https://user-images.githubusercontent.com/26344691/68176196-8a29a480-ff8c-11e9-871e-4c37fe34f0e7.png)
![Screenshot (14)](https://user-images.githubusercontent.com/26344691/68176197-8a29a480-ff8c-11e9-9eda-9f6284f1d943.png)
TODO:
- highways chose lanes when joining highway roundabout.
- provide user options.
- only traverse oneway paths.
- roundabout detection

**Comment by kianzarrin** [comment]
>only traverse oneway paths.
roundabout detection

For these features I may need to modify the traverse function to use one more input and output variable.

I wonder how hard is it going to be to write a breadth-first traversal functions that trims path that don't form a loop.

**Comment by kianzarrin** [comment]
>I wonder how hard is it going to be to write a breadth-first traversal functions that trims path that don't form a loop.

Its just going to be like breadth first search of binary search tree. I just have too keep pointers to parent.

**Comment by kianzarrin** [comment]
Ok I have arrived at a dilemma:
Traverse all one directional roots that form a loop and:
 A) prefer shortest path (Red Paths)
 B) prefer straight path (Grean Paths)
 C) Only go straight ( works with a normal roundabout but none of the ones bellow ).

![Screenshot (15)](https://user-images.githubusercontent.com/26344691/68214746-ae19d400-ffe6-11e9-8f25-4201edf6d7f5.png)
![Screenshot (16)](https://user-images.githubusercontent.com/26344691/68214745-ad813d80-ffe6-11e9-909d-6394d3941497.png)

What should I do? choose option C which is full proof but not inclusive leaving strange roundabouts to issue #542 ? or choose option A or B that are more inclusive but may suggest strange paths that the user can see by looking at the highlight?

I personally prefer option A. But I need other peoples opinions before I can progress with this.

**Comment by kvakvs** [comment]
How about a shortest loop of the same road type. If the user changes road type to a smaller or larger road and breaks the loop, its on them to fix it manually. In your top picture, there is no roundabout with a single road type, so it should not be detected as such.

**Comment by kianzarrin** [comment]
@kvakvs 
The problem with the same road type restriction is that in many cases people reasonably change the number of lanes in the round about like bellow:
![Screenshot (17)](https://user-images.githubusercontent.com/26344691/68217965-3c448900-ffec-11e9-8ab7-06173821ac77.png)

**Comment by kianzarrin** [comment]
after giving it some though I changed my opinion (lol I cannot make up my mind!) to option  "B) prefer straight path (Grean Paths)".
If the user ALT-clicks over specific part of the roundabout that he wants to be covered it will work in all cases above. There will be super weird cases in which it won't work but that's on the user.
besides TMPE already gets confused in exceptional cases:
![semi roundabouts](https://user-images.githubusercontent.com/26344691/68218484-110e6980-ffed-11e9-8096-252d8e1e29de.png)

Option  C has the advantage of making the code much shorter though.

**Comment by kvakvs** [comment]
B makes no sense at all, it extends onto the highway, i do not want highway be modified, if i am only doing a roundabout. Just prefer the same type road. Also maybe you can also query the Game Engine and get the road assigned the same street name somehow.

**Comment by brunoais** [comment]
@kianzarrin 
What about:
"Choose the most similar one-way road path which leads to a loop and break ambiguity with shortest?"
The main idea is to choose the roads based on possibilities and priorities.

1. Can do a complete loop with close-enough roads (in lane count) and changes in lane count must be in diverging or converging roads.
2. If a connection loses lanes, consider that likely to be the continuation of the roundabout.
2. The one with least lanes is, more likely, an exit (if it then merge into a two-way, it's disqualified).
3. If there's a 1 or 2-node-long triangle connection, likely that's part of an exit and that triangle is not part of the roundabout.
4. If one passage has straight nodes (too small turning angle), penalize those in the decision.
5. If the road type changes without changing the number of lanes, it's less likely to be part of the roundabout (penalize).

Choose the one with highest score. If there's a tie (give a margin of error), choose the shortest path.

Comments?

**Comment by kianzarrin** [comment]
@kvakvs 
>B makes no sense at all, it extends onto the highway, i do not want highway be modified, if i am only doing a roundabout. Just prefer the same type road. Also maybe you can also query the Game Engine and get the road assigned the same street name somehow.

Option B (go straigh at junctions) might make more sense than you think! In almost all cases we stay on the round about. Keep in mind that the roundabout in question is very weird and rare because to go to the highway you need to go straight ahead but to stay in the roundabout you need to turn.  almost all roundabouts are the other way around. But even in this extreme case you can move the mouse on the one lane segment of the roundabout for it to work.

**Comment by kianzarrin** [comment]
I created mass edit options tab 
![Screenshot (25)](https://user-images.githubusercontent.com/26344691/68487125-38627200-024b-11ea-98d9-386bb1272c3c.png)

**Comment by kvakvs** [comment]
Now wait a second.
The tooltip has to be updated to let people know the key combination.

If we hide these settings in Options, many people will have no idea that they exist. We can offset this by having sane defaults.

I'd love to have a way to document these options without writing an entire new Wiki article. Something like a tiny ❔ next to each option. Many people play without even knowing that Wiki exists and remain unaware forever.

**Comment by krzychu124** [comment]
@kvakvs I forgot to push updated translations and tooltip ;)

**Comment by kianzarrin** [comment]
> Now wait a second.
> The tooltip has to be updated to let people know the key combination.
 
Of course I will add tool-tip. this is a work in progress.
And so is this cool feature:
![Screenshot (27)](https://user-images.githubusercontent.com/26344691/68518936-f5c68700-0296-11ea-99b1-e1214a1eaa26.png)
Stay in lane of the node is too close to round about. this option can automatically solve a lot of my city traffic issues.
Creating roundabouts with the roundabout mode usually results in this problem. Its a good idea for roundabout builder to delete nodes that are too close to roundabout. but meanwhile its a good idea for us to ban lane switching too close to the roundabout.

**Comment by brunoais** [comment]
@kianzarrin That one example you show doesn't make sense. There's only one lane in and one lane out. Only the lanes in need to have prevention from changing lane.

**Comment by kianzarrin** [comment]
@brunoais 
> I believe only the lanes in need to have prevention from changing lane

What does this mean

>That one example you show doesn't help at all.

This works if there are more lanes too. I can put an exception for one lane, but does it even matter?

Also note that you can activate more options for more features in the options menu. I have not done that in here.

if you want to try it for your self, you know where my code is :)
https://github.com/kianzarrin/TMPE-kian/tree/PriorityRoad

**Comment by brunoais** [comment]
> > I believe only the lanes in need to have prevention from changing lane
> What does this mean

Ups. I changed it a bit. I mean, only the lanes into the roundabout need to have the changing lane restriction. When coming out of the roundabout, it appears there's no need to restrict lane changing

**Comment by kianzarrin** [comment]
@brunoais 
> I mean, only the lanes into the roundabout need to have the changing lane restriction. When coming out of the roundabout, it appears there's no need to restrict lane changing

The lane on the round about also have this option. I hope you have paid attention to the fact the the lanes leading to round about (optionally) **ONLY** stay in lane when the node is **TOO CLOSE** to the roundabout. if cars do not have enough space to change lanes, there is going to be congested traffic.

God knows how many cities I have fixed who had congestion because of this very common issue. Its very common because this is what the round about mod does.

**Comment by brunoais** [comment]
Oh... In the image you show, both leading to the roundabout and from the roundabout are prevented from changing lanes (at least, to my understanding)

**Comment by kianzarrin** [comment]
@Strdate
As you can in the picture bellow while the round about builder does remove nodes touching the roundabouts it does not remove those close to the round abouts causing all sorts of traffic issues.
![Screenshot (31)](https://user-images.githubusercontent.com/26344691/68552972-b8443400-0425-11ea-8204-d9f0f70b55c1.png)

Also you can see that my not yet committed roundabout mass-edit feature fixes this issue by banning lane switching near the roundabout (but only if the node is too close like 5 units away).

I have some other features to like stay in lane inside a round about (optional of course).

Since you are building the roundabouts I am interested in your thoughts in this. Can you please telll me what do you prefer:
A) ban lane changing close to the roundabouts
B) remove the node to eliminate the problem in the first place.

Here are my thoughts on this:
I like fixing other peoples cities and one common problem is traffic jams caused by lane switching on nodes too close to the roundabouts created by roundabout-builder tool. Another problem is that some times it causes odd elevation issues as in picture bellow:
![Screenshot (33)](https://user-images.githubusercontent.com/26344691/68553164-76b48880-0427-11ea-966a-32f8eaa3756a.png)

So I think its better to remove the node. this might make the segments a little bit longer than usual but that's no biggie.

PS: not that I have tried it but I think the following code change might help:


```
//'//https://github.com/Strdate/AutomaticRoundaboutBuilder/blob/master/RoundaboutBuilder/Tools/EdgeIntersections2.cs#L218
if (VectorDistance(bezier2.a, bezier2.d) < /*MIN_BEZIER_LENGTH*/ 30 ) // 30 = 5 units * 8 meters per units.
{
   VectorDistance(bezier2.a, bezier2.d)); 
   nextSegmentInfo(oldSegmentW, ref endNodeW, ref endDirection);
}
```

**Comment by Strdate** [comment]
@kianzarrin Did you play with different values? I don't even know now what MIN_BEZIER_LENGTH is set to.

**Comment by kianzarrin** [comment]
@Strdate
I opened [new issue ](https://github.com/Strdate/AutomaticRoundaboutBuilder/issues/8) on the roundabout builder to discuss this since some of the issues like the creepy steep slope near the round about has nothing to do with TMPE.

**Comment by aubergine10** [comment]
> I created mass edit options tab

We can't add more tabs. Some languages (\*cough\* German, Polish...) have long words. We already had to simplify tab names to make everything fit so adding another tab is a non-starter IMO.

We should instead make tabs scrollable so they can fit more options. (Look at code for mod compatibility checker to see how to do scroll panels).

The options depicted earlier in this thread all look like they belong on Policies tab, in a "At roundabouts" section maybe?

(I'm still reading through thread so apologies if someone already discussed this).

**Comment by aubergine10** [comment]
Some more thoughts:

* Mod options shouldn't "negate" (it's confusing in some cultures if activating an option has the effect of deactivating something). If I turn an option on, something should be turned on, not off.
* When mass changes are being made via user interaction, we need visual feedback to show where (or, ideally, what) changes are being made:
    * At simplest level this could be highlighting the segments (and nodes?) on the 'route' that will be affected
    * Better still, would be show relevant overlays depicting the end result
    * Visualising what will happen before user applies it gives user confidence to apply it
    * In cases where it gets route wrong (for whatever reason) I might still choose to apply and then make some manual corrective adjustments
    * Visualisation will help with any future bug fixing and enhancement work
* In terms of visualising the roundabout customisations, which comprise multiple TM:PE tools, there are, I think, two viable approaches:
    1. Just turn on the relevant persistent overlays - less work, but they will show customisations for everything on screen, which could be confusing to users. However, this could cause some lag because we've not fully optimised those overlays yet. Each overlay builds a list of all segments/nodes on the map (as applicable to the overlay), then filters that list to stuff that's currently within camera view, then checks if any of that stuff has customisations that differ from defaults, then renders it. 
    2. Considering we know specifically which segments/nodes will be affected, maybe we could refactor the overlays so they get passed in a list of segments/nodes (as applicable) to process. This would cut out all the "scan whole map, work out what's on screen" stuff, and potentially lay some foundations for future optimisation (namely: caching) of what's in camera view for the normal use of overlays?
* If TM:PE gets this new feature, configurable in mod options, we should provide an API for "Roundabout Builder" mod to use
    * Roundabout builder can provide a list of segment id's that comprise the main roundabout (so TM:PE does not need to guess the route)
    * TM:PE then applies the user-configured roundabout settings to those segments, the nodes between them and any entry/exit segments (Roundabout Builder no longer needs to worry about all the minuatae of the different TM:PE featuers, it just says "here's a roundabout, work your magic")

**Comment by kianzarrin** [comment]
@aubergine10 I already turn on relavant overlays. if you hold ctrl then relavant overlays are turned on. Also ofcourse the round about is highlighted when holding shift. My code is in github so you can take a look.i upload my latest version tomorrow.

**Comment by kianzarrin** [comment]
Wow look at this cool implementation of magic roundabout:
![WelllitMilkyDragon-poster 1](https://user-images.githubusercontent.com/26344691/69501938-767db800-0f12-11ea-9979-6699c6685b1f.jpg)

and another type of roundabout: https://www.google.co.uk/maps/@51.8845308,0.9327983,122m/data=!3m1!1e3
![Screenshot (103)](https://user-images.githubusercontent.com/26344691/69502018-497dd500-0f13-11ea-8c81-7aed3ce121c7.png)

I will see how my roundabout mass edit feature works out here.

**Comment by aubergine10** [comment]
I think there are some of those in workshop. Here, try some of these ready made intersection assets :)

* https://steamcommunity.com/sharedfiles/filedetails/?id=1910302061
* https://steamcommunity.com/sharedfiles/filedetails/?id=1910417290
* https://steamcommunity.com/sharedfiles/filedetails/?id=705074476
* https://steamcommunity.com/sharedfiles/filedetails/?id=877114598
* https://steamcommunity.com/sharedfiles/filedetails/?id=884787937 - bidirectional roundabout lol
* https://steamcommunity.com/sharedfiles/filedetails/?id=1266280103
* https://steamcommunity.com/sharedfiles/filedetails/?id=622616395
* https://steamcommunity.com/sharedfiles/filedetails/?id=561554476 - requires NExt2
* https://steamcommunity.com/sharedfiles/filedetails/?id=852984562
* https://steamcommunity.com/sharedfiles/filedetails/?id=829552245
* https://steamcommunity.com/sharedfiles/filedetails/?id=1907883944
* https://steamcommunity.com/sharedfiles/filedetails/?id=1908121926 - I think this is the one from your google earth image! Requires several mods/assets to use.
* https://steamcommunity.com/sharedfiles/filedetails/?id=596679166
* https://steamcommunity.com/sharedfiles/filedetails/?id=643466950
* https://steamcommunity.com/sharedfiles/filedetails/?id=535467797
* https://steamcommunity.com/sharedfiles/filedetails/?id=779009510

I'm still searching for another very unique roundabout from some years back, but the list above should give you some nightmares for now :)

**Comment by aubergine10** [comment]
Still searching for that other roundabout but found this on my travels which might be worth trying out in-game:

![image](https://user-images.githubusercontent.com/1386719/69521544-2d038c00-0f57-11ea-8b7c-481f4378966f.png)

**Comment by aubergine10** [comment]
Still not found the one I'm looking for, but another to test:

https://steamcommunity.com/sharedfiles/filedetails/?id=662904182

Lots of very short roads between junctions, will likely cause problems with UI or even the various tools.

**Comment by aubergine10** [comment]
This is the crazy roundabout I was trying to find: https://steamcommunity.com/sharedfiles/filedetails/?id=467233288

**Comment by aubergine10** [comment]
Sp3ctre18 is doing some interesting roundabout designs which can be found in this collection:

https://steamcommunity.com/workshop/filedetails/?id=1762964190

**Comment by kianzarrin** [comment]
@aubergine10
My roundabout detection algorithms works with most of those crazy roundabouts. 
In every case my roundabout detection algorithm is successful, All the traffic rules are setup properly.

As said in https://github.com/krzychu124/Cities-Skylines-Traffic-Manager-President-Edition/issues/539#issuecomment-549898578 I prefer to upgrade the roundabout finding algorithm in second phase of this issue (or should I open a new issue?). @brunoais I can see now that there is certainly a demand for it. #542 is an alternative solution to the problem.Regardless I prefer to make the roundabout traversal algorithm more clever.

Here are some screenshots:
![Cities_l62wjcXSxE](https://user-images.githubusercontent.com/26344691/69755126-36ac1000-1160-11ea-8bd7-d4cb8679a0fa.jpg)
![Cities_76UqKMprr1](https://user-images.githubusercontent.com/26344691/69755127-3744a680-1160-11ea-8f50-2cd894a11690.jpg)
![Cities_jJNp0TorJv](https://user-images.githubusercontent.com/26344691/69755128-3744a680-1160-11ea-96a0-3115b090f992.jpg)
![Cities_gmlSpFPKBp](https://user-images.githubusercontent.com/26344691/69755129-3744a680-1160-11ea-95af-eb977e876125.jpg)
![Cities_puKlVxNmwS](https://user-images.githubusercontent.com/26344691/69755130-3744a680-1160-11ea-837f-986792eb285d.jpg)
![Cities_U1wuZeppc7](https://user-images.githubusercontent.com/26344691/69755131-37dd3d00-1160-11ea-831a-397afe3f3860.jpg)
![Cities_NiwvuVg2Qq](https://user-images.githubusercontent.com/26344691/69755132-37dd3d00-1160-11ea-8e04-63df1176e5e4.jpg)
![Cities_Bqg2ygPQ7F](https://user-images.githubusercontent.com/26344691/69755133-37dd3d00-1160-11ea-96d8-854fd299a92a.jpg)
![Cities_uI8wsksEkg](https://user-images.githubusercontent.com/26344691/69755134-37dd3d00-1160-11ea-861e-3c627576eeab.jpg)
![Cities_xmCQOsZYuX](https://user-images.githubusercontent.com/26344691/69755135-3875d380-1160-11ea-9477-ab608ba4d5d8.jpg)
![Cities_JtPiNwESdo](https://user-images.githubusercontent.com/26344691/69755136-3875d380-1160-11ea-8176-d533657c6075.jpg)
![Cities_TH4DK7RkAE](https://user-images.githubusercontent.com/26344691/69755137-3875d380-1160-11ea-9cff-5186d1844e94.jpg)
![Cities_OC2UmkUknf](https://user-images.githubusercontent.com/26344691/69755138-3875d380-1160-11ea-990b-5ccab70213f7.jpg)
![Cities_cQDfOqVUOT](https://user-images.githubusercontent.com/26344691/69755139-390e6a00-1160-11ea-9222-ad95bd61fcf1.jpg)
![Cities_8sxXA7cDvC](https://user-images.githubusercontent.com/26344691/69755140-390e6a00-1160-11ea-9bd7-6a8f188ad1a1.jpg)
![Cities_xZkW7HSLkf](https://user-images.githubusercontent.com/26344691/69755142-390e6a00-1160-11ea-9c57-35a87be8b3c1.jpg)
![Cities_p36YRFeMHO](https://user-images.githubusercontent.com/26344691/69755144-390e6a00-1160-11ea-92d3-7ef58a8061e1.jpg)
![Cities_IDMHOYA6nx](https://user-images.githubusercontent.com/26344691/69755145-39a70080-1160-11ea-8e72-f2ef38b0f70f.jpg)

**Comment by kianzarrin** [comment]
@kvakvs  Do I need unit tests here?

**Comment by aubergine10** [comment]
I notice there's some cases where there's only one entry road to a junction, and the entry is given priority.

![image](https://user-images.githubusercontent.com/1386719/69758507-981bb100-1157-11ea-82a5-bc95be5be5e8.png)

Does this incur performance impact over just leaving the junction as vanilla setup?

**Comment by kvakvs** [comment]
@kianzarrin You don't _need_ them to release this work, but if you find a way to test this in some reasonable non-complicated way, absolutely do it.

**Comment by krzychu124** [comment]
> Does this incur performance impact over just leaving the junction as vanilla setup?

@aubergine10 It shouldn't but I'm curious why is this even possible?

**Comment by kianzarrin** [comment]
> > Does this incur performance 
> @krzychu124 It shouldn't but I'm curious why is this even possible?

It's what the code does. To avoid it we can check for node onewayout flag

**Comment by aubergine10** [comment]
> It's what the code does. To avoid it we can check for node onewayout flag

Well, priority signs are about _entrance_ to junction, not leaving junction.

So, specifically, we should ideally disable priority sings on junctions that have one way IN, as that one way in has no competition (and thus no need for priorities to be set).

**Comment by aubergine10** [comment]
Just a random thought: Looking at some of the glitches identified in the test images (great work btw!!) would it be worth having something that classifies as segment as "clockwise, anti-clockwise, or bidirectional"?

That way, if the starting segment is clockwise travel direction (such as roundabout on LHT cities), for example, it would make it easier to filter adjacent segments if, in relation to previous segment, they are going clockwise.

If starting segment is bi-directional, then pick a direction relevant to city setup: LHT = clockwise, RHT = anti-clockwise, and follow that curve?

Rough mockup: based on direction of traffic (on current segment) entering a node, and knowing if clockwise vs. anti-clockwise, could something like this work?

![image](https://user-images.githubusercontent.com/1386719/69808048-a52fb300-11de-11ea-89a8-7b342662ef9b.png)

Example above would be for clockwise travel. So one line is "straight ahead", the other is at some angle of tolerance, and any outgoing segment in between would be considered candidate for "continuation of the road in the (anti)clockwise direction".

**Comment by kianzarrin** [comment]
> Just a random thought: Looking at some of the glitches identified in the test images (great work btw!!) would it be worth having something that classifies as segment as "clockwise, anti-clockwise, or bidirectional"?

I can't see how to implement the clockwise direction thing since the code is not aware of the bigger picture when its focusing on one segment. I have some simple ideas to fix it
- currently i check if `currentSegment =! initaialSegment && segmentList.constains(currentSegment)` then its not a roundabout. A better check would be to check `if nodeList.Contains(CurrentSegment.headNode)`
- Instead of following a preferred direction (forward) follow all possible paths in all directions. if the path is not a roundabout then discard it. among the paths that are roundabout then I choose the one that has the list amount of left/right turns within the roundabout. if the number of turns are equal then I choose the one that is shortest.

**Comment by kianzarrin** [comment]
I now check for `nodeList.Contains(CurrentSegment.headNode)` instead of `segmentList.constains(currentSegment)` Didn't solve the problem but made it a little bit better. No more zig zags.

before
---
![Cities_xmCQOsZYuX](https://user-images.githubusercontent.com/26344691/69843199-2a62a880-126f-11ea-9188-a6b110906bcc.jpg)
![Cities_TH4DK7RkAE](https://user-images.githubusercontent.com/26344691/69843200-2a62a880-126f-11ea-9c32-729e24e72b51.jpg)

A
![Cities_PtXixifMAF](https://user-images.githubusercontent.com/26344691/69843240-51b97580-126f-11ea-8c88-316198f430f2.jpg)
fter
---
![Cities_HdgHjyccJG](https://user-images.githubusercontent.com/26344691/69843201-2a62a880-126f-11ea-94b3-039a4f7f5308.jpg)
