### ISSUE TITLE
shortcut to fix traffic rules where minor road joins a main avenue

### ISSUE THREAD

**Issue by kianzarrin** [krzychu124/Cities-Skylines-Traffic-Manager-President-Edition#541]
in real life and also in simcity when a small road joins a main avenue, the separation barrier in the middle remains unbroken and people can only turn right (the only advantage of simcity over cities skylines!!!). we already have an asset that visually conserves the junction barrier in such situations

![previewfile_1319965985](https://user-images.githubusercontent.com/26344691/68045810-0e58ff00-fce3-11e9-85c5-bf12748d6f36.png)

But TMPE is required to make it function as it should. It can be a bit tedious to apply all the traffic rules particularly when fixing cities where many minor roads are joining one avenue. 

so i suggest a shortcut: choose junction priority tool then press **ctrl+click** on a junction to set all rules regarding the above scenario:
 - remove zebra crossings on the avenue
 - cars on the avenue can enter block junctions
 - no left turns
 - give way entering the avenue

Let me clarify I prefer this feature apply to all big roads such as this:
![median rules](https://user-images.githubusercontent.com/26344691/68053882-b8418700-fcf5-11e9-9f9c-a61a45a8e337.png)

**Comment by krzychu124** [comment]
Ok, that will be the hardest of all you've posted. 
We still don't have algorithm which would properly detect road medians, also I am not sure how do you want properly distinguish road types (I know that we have 'levels' but still, not trivial task.

**Comment by kianzarrin** [comment]
I think the same concept can work on a scenario like this. Except that highway ramps do not need to give way. 
![highway fork](https://user-images.githubusercontent.com/26344691/68046399-765c1500-fce4-11e9-8e48-5dc59aaa9fee.png)

**Comment by kianzarrin** [comment]
@krzychu124 We don't need algorithm to detect road median. if the user uses ctrl-click, then we assume that there is.
Also the smaller road is going to be the one which gives way.
if there are three segments the smalls segment gives way.

**Comment by kianzarrin** [comment]
@krzychu124 even if there is no junction median it still does not mean people wouldn't want to ban left turn.

**Comment by krzychu124** [comment]
I've had to read again description to got the point. Please format it using [markdown](https://help.github.com/en/github/writing-on-github/basic-writing-and-formatting-syntax)
I assume you will apply 'no left turn' to all lanes of clicked segment, what if user click at segment which he shouldn't? 
Will it aplly rules to any segment you click or you are going add filter with requirements(number of lanes, segment type etc.) when applying rules.

**Comment by kianzarrin** [comment]
@krzychu124 
> I've had to read again description to got the point. Please format it using markdown

sorry for bad description. I hope its a bit better now.

> I assume you will apply 'no left turn' to all lanes of clicked segment,
**CTRL**-click on a **NODE** to be more accurate. 

>  what if user click at segment which he shouldn't?

Accidental CTRL+click will make accidental changes.
I can ask the same question  in the junction priority tool what if the user accidentally presses Shift+Click on a long road and messes up his whole road?

>Will it apply rules to any segment you click or you are going add filter with requirements

as for requirements and special case situations we need to decide the following:
 - should I check for road angles?
 - should I require the minor road to be smaller?
 - etc
I am open to ideas!

>We still don't have algorithm which would properly detect road medians, also I am not sure how do you want properly distinguish road types 

the Vanila 6 lane boulevard does not have junction median but I still want to be able to ban left turns.
![median rules](https://user-images.githubusercontent.com/26344691/68053386-73692080-fcf4-11e9-8ea8-8b47d465a3e2.png)

I think checking for junction median is possible though a bad Idea. I can check if there is a central lane with no vehicles on it. or I can check for the 'Can cross lanes' property.

**Comment by kianzarrin** [comment]
#7 and #539 are related.

**Comment by kianzarrin** [comment]
I wrote the code that works in basic circumstances.
https://github.com/kianzarrin/TMPE-kian/tree/PriorityRoad

My UI is a bit more whack than #77 so that might need some fixing.
Also I noticed that the Overlay update functionality is also whack. It does not refresh view soon enough. I have to close and open TMPE tool to see the changes. That also needs some fixing.

My current code can handle some simple and moderately complicated cases:
![Screenshot (6)](https://user-images.githubusercontent.com/26344691/68094928-ce924300-fead-11e9-9a29-0ee41c44b617.png)
![Screenshot (7)](https://user-images.githubusercontent.com/26344691/68094929-cf2ad980-fead-11e9-9f86-ba85ac297ef8.png)
![Screenshot (8)](https://user-images.githubusercontent.com/26344691/68094930-cf2ad980-fead-11e9-9694-ed30e50b9ff2.png)

but it fails when it is very complex. I will work on that.
![Screenshot (9)](https://user-images.githubusercontent.com/26344691/68094932-cf2ad980-fead-11e9-9d7e-06dfbaf5688c.png)

**Comment by kianzarrin** [comment]
@krzychu124 @aubergine10 Give me some ideas. any more complicated cases you can think of.

I can think of this one and I am not sure what should happen.
![Screenshot (10)](https://user-images.githubusercontent.com/26344691/68095158-c20eea00-feaf-11e9-8707-5624226519f3.png)

**Comment by kianzarrin** [comment]
I always can exclude cases where it gets too complicated or nonsensical. I already have decided to exclude one way main road (that is if any of the biggest roads are one way, I return without doing anything).

**Comment by kianzarrin** [comment]
I did some more thinking and changed my opinion:
- I will handle the case where the big road is one way, but only if both segments are one way in the same direction.
- if the two biggest road segments are angled, then I will exclude them. I don't want to make the code too complicated.

**Comment by aubergine10** [comment]
> remove zebra crossings on the avenue

Would be cool if we could hide the crossing decal/prop too, although not sure if it's possible.

> We don't need algorithm to detect road median. if the user uses ctrl-click, then we assume that there is.

I agree with this in principle, essentially we're offloading "median detection" work to the end-user.

However, on a long road with lots of junctions, it could quickly become tedious to click each junction in turn. That being said, auto-median detection is something that could be investigated as separate task at some point in the future.

**Comment by aubergine10** [comment]
What if instead of doing it based on user click, we just make vanilla 'Priority _Routes_' more intelligent?

So, currently, if you set a priority _route_, the result is that side roads get "Stop" signs on them, which is often very annoying and bad for traffic flow.

We could treat a priority route as if a user has Ctrl+Clicked all the junctions along it? But allow user to override any setting at any junction as usual.

So, just as we have "highway rules" stuff in mod options, we could have "priority route rules" stuff that gets applied to any priority route.

If road names are display, user can quickly get to the relevant info view by clicking the route name, then they just draw the road and select the "Priority route" option for that route.

**Comment by kianzarrin** [comment]
I have added the following options to make this more like the options of the roundabout mod:
change lanes minor road
change lanes major road
enter blocked minor road
enter blocked major road
yield minor road

brainiac
This should help a bit with your request too:
![Screenshot (55)](https://user-images.githubusercontent.com/26344691/68790571-32f09780-0650-11ea-8f43-1a8944cefbeb.png)

In any case its a cool Idea to be able to select multiple segments and change all options together for the junction restriction tool. or otherwise be able to ctrl-click on a junction select all connected segments to perform mass edits.

**Comment by kianzarrin** [comment]
I am trying to decide which options to include:
```
* I want to add
< I want to remove
*< does not exist and I don't think I should add
//rabout_DecicatedExitLanes
//rabout_SwitchLanesYeildR<
//rabout_SwitchLanesMainR*<
//rabout_StayInLaneMainR
//rabout_StayInLaneNearRabout
//rabout_NoCrossMainR
//rabout_NoCrossYeildR<
//rabout_PrioritySigns*

//avn_NoCrossMainR
//avn_NoCrossYield*<
//avn_NoLeftTurns*<
//avn_EnterBlockedMain*<
//avn_EnterBlockedYeild*
//avn_StopEntry*
//avn_PrioritySigns*
//avn_SwitchLanesMain*<
//avn_SwtichLanesYeild*<
```

There is a trade off between usability and complexity. 

This is a bit in contradiction to what I said here [in the comment above](https://github.com/krzychu124/Cities-Skylines-Traffic-Manager-President-Edition/issues/541#issuecomment-553529140). 
This also concerns #539 
And here are the options in roundabout builder for comparison:
![Screenshot (67)](https://user-images.githubusercontent.com/26344691/69017130-80049e80-09ad-11ea-875d-a0ea5c5b5a4b.png)

**Comment by kianzarrin** [comment]
Progress report:
code: https://github.com/kianzarrin/Cities-Skylines-Traffic-Manager-President-Edition/tree/PriorityRoad
test city : https://steamcommunity.com/sharedfiles/filedetails/?id=1917803358
do not forget to go to mass edit options and turn on everything :)
Please shift click on different road segments and see what happens.

I handle all these cases:
Roundabouts
- straight roundabouts screenshot 1
-  semi roundabouts screenshot 2
- half roundabouts. screenshot 3
- Choose best path when there are multiple paths that create a loop. 

Priority road:
- small road joining main road gives way screenshot 4B
- If avenue has acceleration lane, small road joining ave does not yield and does not keep clear of the junction. (I do not use lane connection though mass edit of lane connections might be a good idea in feature). This also works with SPUI Screenshot 4C
- road splitting: 4A
![Screenshot (74)](https://user-images.githubusercontent.com/26344691/69380641-8f406080-0cbb-11ea-85c5-f3fd45371007.png)
![ScreenshotA](https://user-images.githubusercontent.com/26344691/69380639-8ea7ca00-0cbb-11ea-9299-f28e0ec5078d.png)
![Screenshot (74) - Copy](https://user-images.githubusercontent.com/26344691/69380640-8ea7ca00-0cbb-11ea-91a6-5a0bcc0389ee.png)
![Untitled](https://user-images.githubusercontent.com/26344691/69380638-8ea7ca00-0cbb-11ea-8d89-89d62ceac560.png)

PS: As much as I am proud of this in future maybe it is best to have all these rules by default. that is TMPE would use such road rules by default so that the user does not even need to mass edit. Although I am not sure if it is even possible.

**Comment by aubergine10** [comment]
> PS: As much as I am proud of this in future maybe it is best to have all these rules by default. that is TMPE would use such road rules by default so that the user does not even need to mass edit. Although I am not sure if it is even possible.

This could be very confusing for a lot of users. For example, we get regular issues where people have set up crazy customisations and then wonder why their traffic is broken. So I think it best to avoid automatically applying customisations; if user has to manually apply (including manual bulk application) and something goes wrong, at least they have some idea of what they did to make it go wrong.

Also note that there is a [16 MB limit](https://github.com/VictorPhilipp/Cities-Skylines-Traffic-Manager-President-Edition/issues/160) (link to old repo) to the amount of data TM:PE can store in save games, and automatically applying customisations could potentially push over that limit on large cities; and even if not, might cause general performance issues.

**Comment by Sipke82** [comment]
If it's possible i would also vote for changing the default..

**Comment by kianzarrin** [comment]
maybe we should put this pictures in the wiki some time:
![Screenshot (979)](https://user-images.githubusercontent.com/26344691/81059171-9e694280-8ed8-11ea-9ca1-6f647a7ea9ba.png)
![Screenshot (984)](https://user-images.githubusercontent.com/26344691/81059173-a1643300-8ed8-11ea-958a-74ab6b97cc41.png)
![Screenshot (983)](https://user-images.githubusercontent.com/26344691/81059175-a32df680-8ed8-11ea-961d-87ad5ad21851.png)
![Screenshot (982)](https://user-images.githubusercontent.com/26344691/81059179-a45f2380-8ed8-11ea-8e2c-b3ab903182a4.png)
![Screenshot (981)](https://user-images.githubusercontent.com/26344691/81059185-a7f2aa80-8ed8-11ea-8301-aa881b70a3ad.png)
![Screenshot (980)](https://user-images.githubusercontent.com/26344691/81059194-ab863180-8ed8-11ea-9473-25947080e9ee.png)
