### ISSUE TITLE
Lane connector: Hovering over lane points is difficult when cars and roads are passing over.

### ISSUE THREAD

**Issue by kianzarrin** [krzychu124/Cities-Skylines-Traffic-Manager-President-Edition#543]
when connecting lanes, it can be frustrating to hover over lane markers if there is a car over it (or if there is a road over it) because the place the mouse pointer has to be to select the marker is different than the place where the marker has been rendered in a 3D setting:
![Cities_VEXJKsBNIG](https://user-images.githubusercontent.com/26344691/68073672-183e3900-fd9b-11e9-8646-c72443e84baf.jpg)

To fix this we need to either change the hovering functionality or the rendering functionality to match one another in a 3D setting.

**Comment by kianzarrin** [comment]
This is the code responsible for hovering:
```
private bool IsLaneMarkerHovered(NodeLaneMarker laneMarker, ref Ray mouseRay) {
    Bounds bounds = new Bounds(Vector3.zero, Vector3.one) {
        center = laneMarker.Position
    };

    if (bounds.IntersectRay(mouseRay)) {
        return true;
    }

    bounds = new Bounds(Vector3.zero, Vector3.one) {
        center = laneMarker.SecondaryPosition
    };
    return bounds.IntersectRay(mouseRay);
}
````

and this is the code for rendering

```
RenderManager.instance.OverlayEffect.DrawCircle(
    cameraInfo,
    circleColor,
    laneMarker.Position,
    laneMarker.Radius,
    laneMarker.Position.y - 100f, // through all the geometry -100..100
    laneMarker.Position.y + 100f,
    false,
    true);
```

**Comment by kvakvs** [comment]
Take some average radius value that will work for most markers (hovered and non-hovered have slightly different radius)..

**Comment by kianzarrin** [comment]
Increasing the radius can help a little bit. but as you can see from the picture I have posted the mouse pointer is a mile away! 

Fixing this may prove difficult as this is may be  intrinsic problem of the game engine.

one solution could be hovering anywhere over the lanes should enlarge the relevant lane marker.

**Comment by aubergine10** [comment]
> one solution could be hovering anywhere over the lanes should enlarge the relevant lane marker.

I like this idea; the enlarged lane maker would give visual feedback as to which lane is hovered and it could be selected by clicking the lane. That could work for both incoming and outgoing lanes.

**Comment by kianzarrin** [comment]
@kvakvs told me:
>can probably raycast to whatever geometry it hits, and then trim the vertical coordinate, because marks are projected vertically

That is also another solution.

**Comment by krzychu124** [comment]
We have to fix both problems. Rendering and raycasting.

I've been working on a prototype of new rendering system for rendering lane connections, connectors, sprites etc. as real overlay (render on quad which is always visible). Using that rendering mode we will get most precise position to select connector (camera angle would be irrelevant).

**Comment by kianzarrin** [comment]
@krzychu124 i created #625 for the ray casting problem.

**Comment by kianzarrin** [comment]
![Screenshot (405)](https://user-images.githubusercontent.com/26344691/73916807-d1466f00-48c6-11ea-853e-04cdc2f1c1e5.png)
