### ISSUE TITLE
Possible bug from lane arrow update

### ISSUE THREAD

**Issue by aubergine10** [krzychu124/Cities-Skylines-Traffic-Manager-President-Edition#546]
Not been able to find a reliable way to reproduce this yet, however I think there's an interaction state bug crept in as a result of #538.

After loading a save, I was going to test the stuff from #538. I opened TMPE main menu and hovered lane arrow button to check what the shortcuts were:

![image](https://user-images.githubusercontent.com/1386719/68617362-078a7300-04bf-11ea-8f55-57e2d7320a7d.png)

> Side note: It would be nice if we could show the button shortcut (in my case `Shift + .`) part of the tooltip in a different colour, eg. yellow, to differentiate from the tool tip text.

So far everything working well. Note: I don't recall clicking the lane arrow button (I had no roads to test with).

I was about to build some roads to do the testing, but noticed some cruft on the map that needed moving out of the way and pressed "M" to open "Move It" mod. _The "Move It" mod UI appeared but I was not able to select anything_ (usually the default "single selection" tool will allow almost anything to be moved).

> I was able to get things working again by escaping out and then reopening Move It UI.

I've not yet been able to reproduce this glitch, maybe it only occurs once on first use or something?

I checked for other mod updates but most recent was 6th/7th November (Theme Mixer 2, Environment Changer, Loading Screen Mod TEST). I've not noticed the issue described above before, despite several sessions since last external mod update. Only thing that's changed is TM:PE which I've built twice in past 48 hours (alpha9 for workshop, and a subsequent build to test #538 - it's this second build where I noticed the issue).

**Comment by kianzarrin** [comment]
Interesting I don't see this at all.
![Screenshot (53)](https://user-images.githubusercontent.com/26344691/68732443-1581e600-05dc-11ea-8f98-e59620d8b989.png)

**Comment by aubergine10** [comment]
The issue wasn't with the tooltip as such, but that it seemed to temporarily break Move It mod.

I'll do some more testing and see if I can make it happen again and, if so, try and document repeatable steps to help track down problem. It's possible that it was just a weird one-off transient issue that might not even be caused by TM:PE.

**Comment by kianzarrin** [comment]
Its compatible  with the move it mod on my computer.

**Comment by aubergine10** [comment]
I've not been able to reproduce this so going to close this issue for now. If it happens again I'll reopen.
