### ISSUE TITLE
Allow the Ability to Switch Between KMH and MPH

### ISSUE THREAD

**Issue by LIPDProductionsInc** [krzychu124/Cities-Skylines-Traffic-Manager-President-Edition#556]
### Describe your idea
I use MPH a lot and it would make it easier for me to do so on my city

### Screenshots?
N/A

### Notes or questions?
N/A

**Comment by krzychu124** [comment]
I think I don't understand your feature request.
Described feature is implemented in LABS and Alpha version.

**Comment by aubergine10** [comment]
This can already be done in the LABS and ALPHA versions of TM:PE.

![image](https://user-images.githubusercontent.com/1386719/69187275-2ff31c80-0b12-11ea-970b-a116038521d1.png)

Note, however, it doesn't yet change the speed sign post props that appear on roads (see https://github.com/krzychu124/Cities-Skylines-Traffic-Manager-President-Edition/issues/49#issuecomment-506969029 for planned work on that).

**Comment by aubergine10** [comment]
Closing this as no response. @LIPDProductionsInc please let us know if you want it reopening.
