### ISSUE TITLE
Issue with mulirow tooltip translation strings

### ISSUE THREAD

**Issue by krzychu124** [krzychu124/Cities-Skylines-Traffic-Manager-President-Edition#574]
I've noticed an issue while working with #572.

If translator add invisible line break instead of `\n` Crowdin generates multiple rows for singe translation string.The rest of translation after line break is not properly loaded in-game.

I suggest split multirow tooltips and separate key modifier (combination Ctrl/Shift/Alt with click) translation from tooltip text because it confuses translators.

**Comment by kvakvs** [comment]
I suggest the plan
1. Check if that is valid CSV
2. If that is, fix CSV loading code to consume newline if a quotation mark is open.
