### ISSUE TITLE
LeftHandDrive returns Right hand drive

### ISSUE THREAD

**Issue by kianzarrin** [krzychu124/Cities-Skylines-Traffic-Manager-President-Edition#577]
Currently Left hand drive is implemented like this:
```c#
        public bool LeftHandDrive =>
            Singleton<SimulationManager>.instance.m_metaData.m_invertTraffic
            == SimulationMetaData.MetaBool.True;
```
I suppose who ever wrote this confused left hand drive with left hand traffic.

I suggest the following fix.
```c#
        //make this [Obsolete]
        public bool LeftHandDrive => LeftHandTraffic; // Intentionally wrong for legacy reasons.

        public bool LeftHandTraffic =>
            Singleton<SimulationManager>.instance.m_metaData.m_invertTraffic
            == SimulationMetaData.MetaBool.True;
```
I didn't remove Left hand drive because I don't want to make too many changes in the code. note that the variable names may also need an update.

**Comment by aubergine10** [comment]
Rather than have something intentionally wrong, why not just do a find and replace across the entire source of the mod?

Also, I think it would be much less ambiguous if it was named `TrafficDrivesOnLeft` to divest from the often confused terms such as LHT/RHD vs. RHT/LHD.

**Comment by kianzarrin** [comment]
@aubergine10 you will need to search and replace a lot of variable names too.

**Comment by aubergine10** [comment]
I think it will be worth doing, to avoid future confusion. We (well, kvakvs specifically) did a lot of similar code clean up shortly after migration to Harmony framework just to improve overall maintainability of the codebase.

**Comment by aubergine10** [comment]
I can have a look at doing the bulk update later today, if you want?

**Comment by kianzarrin** [comment]
@aubergine10 that would be nice.
