### ISSUE TITLE
Improved user messages (guide controller)

### ISSUE THREAD

**Issue by kianzarrin** [krzychu124/Cities-Skylines-Traffic-Manager-President-Edition#593]
In some circumistances when the user makes a small mistake and we want to explain why TM does not make any changes to traffic rules I think its better to show a message like this:
![Screenshot (193)](https://user-images.githubusercontent.com/26344691/70859900-1a132480-1f23-11ea-8f62-16c5086a728e.png)

Rather than an ugly annoying panel like this:
![Screenshot (194)](https://user-images.githubusercontent.com/26344691/70859910-3020e500-1f23-11ea-9319-f99068596ded.png)

This mostly resolves #594

**Comment by kianzarrin** [comment]
Does anyone know what is the name of that top panel ?

**Comment by aubergine10** [comment]
Mod Tools might be able to give some insight in to the panel name. It has a feature that lets you click on any interface element to see details about it. https://steamcommunity.com/sharedfiles/filedetails/?id=450877484&searchtext=mod+tools

**Comment by kianzarrin** [comment]
> @aubergine10  Added: Selection Tool (Ctrl+M or UI button) - allows to select anything and show in SceneExplorer

Mod tools selection tool only works on segments as far as I can tell. I tried it your way activated mod tools selection tool and clicked on the warning panel. But nothing happened in the scene explorer.

There is also a button in scene explorer to show active tool. but the warning panel is not a tool so that's a dead end too.

**Comment by krzychu124** [comment]
try `Ctrl+R`

**Comment by kianzarrin** [comment]
I followed the decompiled code and stumbled upon this:
```c#
// RoadBaseAI
using ColossalFramework;
public override void UpgradeFailed()
{
	GuideController properties = Singleton<GuideManager>.instance.m_properties;
	if ((object)properties != null)
	{
		Singleton<NetManager>.instance.m_upgradeExistingRoad.Activate(properties.m_upgradeExistingRoad);
	}
}
```

**Comment by krzychu124** [comment]
Yup, `GuideManager` spawns popups, so you should search there how to add new popup/set text. You can use ModTools UI debugger view (`Ctrl+R` - pretty slow but does its job) to find out which panel is used

**Comment by kianzarrin** [comment]
Progress report:
 - Guide controller  should be activated from `ToolBase.SimulationStep()` override otherwise it might not work.
 - I made my own guide wrapper and made it work with built in messages (see code snippet)
```C#
    public class GuideWrapper {
        private GenericGuide m_guide;
        public GuideInfo m_info;

        public GuideWrapper() {
            m_guide = new GenericGuide();
            m_info = new GuideInfo {
                m_delayType = GuideInfo.Delay.OccurrenceCount,
                m_displayDelay = 1,
                m_repeatDelay = 1, //3
                m_overrideOptions = true,
                m_icon = "ToolbarIconRoads",
                m_tag = "Generic",
                m_name = "RoadUpgradeNonroad",
            };
        }

        public void Activate() =>m_guide?.Activate(m_info ?? throw new Exception("m_info is null"));
        public void Deactivate() => m_guide?.Deactivate();

        public static GuideWrapper example = new GuideWrapper();
    }
```

**Comment by kianzarrin** [comment]
I need someone to help me to create new crowdin file for guide messages.
