### ISSUE TITLE
The Show error dialog panel can enter a vicious circle

### ISSUE THREAD

**Issue by kianzarrin** [krzychu124/Cities-Skylines-Traffic-Manager-President-Edition#594]
see this https://github.com/krzychu124/Cities-Skylines-Traffic-Manager-President-Edition/pull/538#issuecomment-552160224

Summary of the problem:
steps to reproduce:
A: user clicks on a wrong segment.
B: error panel is displayed.
C: user presses OK
D: the user click from step C is captured by the TM tool. However the `HoveredSegmentID` is not updated. This brings us back to step B.

**Comment by aubergine10** [comment]
Good catch!

**Comment by kianzarrin** [comment]
I think this code maybe responsible:
```c#
// https://github.com/kianzarrin/Cities-Skylines-Traffic-Manager-President-Edition/blob/09974a08b5d0e3c241351e61d982f1ad31752691/TLM/TLM/UI/TrafficManagerTool.cs#L827
if (mouseRayValid)
{
    HoveredSegmentId = 0;
    HoveredSegmentId = 0;
     ...
     return HoveredNodeId != 0 || HoveredSegmentId != 0;
}
return false; // mouseRayValid=false here
```

is there any reason why we don't set `HoveredSegmentId` and `HoveredSegmentId`  to zero when mouseRay is not valid?

**Comment by kianzarrin** [comment]
setting HoveredSegmentId and HoveredSegmentId to zero does fix the problem :) (see comment above)
