### ISSUE TITLE
Attaching debugger to running game

### ISSUE THREAD

**Issue by krzychu124** [krzychu124/Cities-Skylines-Traffic-Manager-President-Edition#60]
@FireController1847, @aubergine10

I've created basic tutorial __[how to attach debugger to running game](https://github.com/krzychu124/Cities-Skylines-Traffic-Manager-President-Edition/blob/1.10.16/TLM/ATTACHING_DEBUGGER.md)__(currently it's inside new branch).

This tool has some small issues (and even more great features which I didn't tested yet).
It will greatly help with debugging issues and digging in game codebase since it has integrated decompiler and you can place breakpoint __anywhere you want__ inside decompiled dll's.

Btw @aubergine10 you can move it to wiki page if you think it's necessary

**Comment by aubergine10** [comment]
Added a version to wiki with some reformatting - lmk if it's valid

https://github.com/krzychu124/Cities-Skylines-Traffic-Manager-President-Edition/wiki/Attaching-Debugger-to-Cities-Skylines

It's normal markdown so it can be copied to the main repo if desired.

IMO it would be worth you posting it as a tutorial over at simtropolis.

**Comment by aubergine10** [comment]
Fixed some typos, improved formatting.

Want me to apply the updated content to the main repo?

**Comment by krzychu124** [comment]
Would be nice, thanks :smile:

**Comment by aubergine10** [comment]
Committed direct to 1.10.16 branch, hope that's ok.

**Comment by krzychu124** [comment]
At lane 25 you can remove ```_``` characters because they are not formated as bold if surrounded with back ticks

**Comment by aubergine10** [comment]
Done :)
