### ISSUE TITLE
Request: Transform parking into extra lane, bike lane or sidewalk

### ISSUE THREAD

**Issue by Monniasza** [krzychu124/Cities-Skylines-Traffic-Manager-President-Edition#602]
### Describe your idea
The tool will allow to transform parking lanes into:
- Bike path
- Sidewalk
- Car lane

### Notes or questions?
Tool name: "Transform parking lanes"

**Comment by auber18** [comment]
Duplicate of #515 

@krzychu124 can u close 602

**Comment by aubergine10** [comment]
@Monniasza Apologies for not posting full response earlier (my gaming rig died so I was forced to use my TV for internet lol). We already had an issue #515 tracking ideas for a lane customiser tool so please subscribe to notifications on that issue if you want to track any future updates.
