### ISSUE TITLE
ArrayIndexOutOfRange when Lane Arrow Tool enabled

### ISSUE THREAD

**Issue by krzychu124** [krzychu124/Cities-Skylines-Traffic-Manager-President-Edition#606]
### Describe the problem
I found a bug related to `hoveredSegmentsId` and `hoveredNodeId`, both values are currently used for rendering overlay when user hover mouse cursor above segment (indication of lane arrows can be changed).
Current Alpha version throws `ArrayIndexOutOfRange` because hoveredSegment is not connected to hoveredNode (`ExtSegmentEndManager.GetIndex(ushort segmentId, ushort nodeId)` returns -1). It's clearly raycasting issue.

### Steps to reproduce

See gif below.

### "Video"
![node_segment_connection](https://user-images.githubusercontent.com/19638970/71855938-b673b580-30e2-11ea-8005-76809d6be0a2.gif)

### Notes
My current fix returns `false` from `HasHoverLaneArrows` if `ExtSegmentEndManager.GetIndex(segmentId, nodeId)` equals `-1` - node is not part of segment.
I will create PR later tomorrow.

BTW, I think I fixed cursor flickering (needs more tests) - easily visible on animation above

**Comment by blueyotis** [comment]
just ran into this bug tonight! glad u know what's going on.

**Comment by aubergine10** [comment]
It's going to be few more days before my gaming rig is repaired (freaking hardware nightmare) - should I revert v11 alpha workshop to alpha10 release in the interim?

**Comment by krzychu124** [comment]
Ohh.. I forgot that you can revert version with one click. I am not really sure in which version half-segment overlays were introduced. I will fix PR later today.
