### ISSUE TITLE
Getting ready for v11 release

### ISSUE THREAD

**Issue by aubergine10** [krzychu124/Cities-Skylines-Traffic-Manager-President-Edition#609]
Planned steps for release of v11 STABLE:

1. Update alpha workshop to alpha 12 (bug fixes to array index errors, localisation updates, etc) - @aubergine10 
2. Make sure that's working well (confirm bugs fixed) - whole team needs to be on lookout for error reports
3. Update changelog to fill in missing info about alpha releases etc (via PR #431) - @aubergine10 
4. Update graphics for workshop pages (see notes below) - @FireController1847 can u do that?
5. Change mod name/version as applicable for LABS/STABLE builds - anyone with source access
6. Once we confirm 11-alpha12 is bug free, we can then update the two workshop pages (text will need some tweaks) - @aubergine10 and @krzychu124 
7. Once 6 is done, it marks the offiical 'end of life' and obsolecence of LinuxFan's version / page; a comment will be posted to that page as necessary to remind users to move over to v11

#### Changes to workshop pages

Old STABLE page (linuxfan's page):

* We are not able to alter anything on this page :(

LABS workshop page (krzychu1245's page):

* Will become "TM:PE V11 STABLE"
* Use `RELEASE` (ie. STABLE) builds
* Preivew image and thumbnail to be updated to reflect new name/version
    * Add "V11" and "STABLE" to the images to make different from linuxfan images
* Updated occasionally to latest stable builds

ALPHA workshp page (aubergine18's page):

* Will become "TM:PE V11 LABS"
* Use `RELEASE LABS` builds
* Preview image and thumbnail to be updated to reflect new name/version
* Regular updates soon after any PRs are merged so we get fast end-user feedback cycle going and thus faster progression of new features to stable releases

#### Other stuff

What happens to labels used on github? I propose:

* LABS -> rename to V11 STABLE
* 11 ALPHA -> rename to V11 LABS

lmk if I missed anything...

**Comment by aubergine10** [comment]
Alpha12 bug fixes seem to be working well. Suggest wait a week or so to be sure, then we formally release v11.

@FireController1847 Will you be able to update the graphics as described above?

**Comment by FireController1847** [comment]
@aubergine10 Yes sir, on it! :)

**Comment by FireController1847** [comment]
Hopefully, this is kind of what you were going for. Let me know if you'd like any changes! :)

![NewPreview LABS](https://user-images.githubusercontent.com/16494272/72226637-8ac45580-3550-11ea-8c66-89570625f744.png)
![NewPreview](https://user-images.githubusercontent.com/16494272/72226638-8ac45580-3550-11ea-8dae-fc491e47010b.png)
![NewThumbnail LABS](https://user-images.githubusercontent.com/16494272/72226639-8d26af80-3550-11ea-9d48-26730be104eb.png)
![NewThumbnail](https://user-images.githubusercontent.com/16494272/72226640-8d26af80-3550-11ea-81de-ffe568cec31a.png)

**Comment by FireController1847** [comment]
As talked about in the Discord and confirmed, here are the four logos to be used anywhere that's necessary. The source files and zip was uploaded to the Discord to not violate copyright by distributing the icon.

![NewThumbnail](https://user-images.githubusercontent.com/16494272/72227315-48067b80-3558-11ea-8cc8-9171f62f0a13.png)
![NewPreview](https://user-images.githubusercontent.com/16494272/72227317-49d03f00-3558-11ea-924a-af9b814f8dde.png)
![NewThumbnail LABS](https://user-images.githubusercontent.com/16494272/72227319-4b016c00-3558-11ea-9c75-347b28828c39.png)
![NewPreview LABS](https://user-images.githubusercontent.com/16494272/72227321-4ccb2f80-3558-11ea-8b78-1f6f6b1ef206.png)

**Comment by aubergine10** [comment]
From discord:

> **FireController:**
> Also, here is the color sheme for the images: https://coolors.co/202225-6cbeeb-427b9c-f7b73c-7cc17b

**Comment by aubergine10** [comment]
Draft of text for TM:PE v11 STABLE page:  [v11.txt](https://github.com/krzychu124/Cities-Skylines-Traffic-Manager-President-Edition/files/4114257/v11.txt)

![image](https://user-images.githubusercontent.com/1386719/73140832-38695580-4075-11ea-8c66-2884232a0dd7.png)

**Comment by aubergine10** [comment]
@krzychu124 stuff for v11 STABLE page:

Please sub and enable [Improved Mod Upload](https://steamcommunity.com/sharedfiles/filedetails/?id=632951976) as it will tag releases with active game version at time of publishing to workshop.

* Title: TM:PE v11 STABLE
* Images: [square preview image](https://user-images.githubusercontent.com/16494272/72227315-48067b80-3558-11ea-8cc8-9171f62f0a13.png) & [slideshow image](https://user-images.githubusercontent.com/16494272/72227317-49d03f00-3558-11ea-924a-af9b814f8dde.png)
* Description: [markup for description](https://github.com/krzychu124/Cities-Skylines-Traffic-Manager-President-Edition/files/4118515/v11.txt)

**Comment by aubergine10** [comment]
v11 released to the wild!
