### ISSUE TITLE
managers should provide reset functions for traffic rules.

### ISSUE THREAD

**Issue by kianzarrin** [krzychu124/Cities-Skylines-Traffic-Manager-President-Edition#623]
## Introduction
For each segment end flag like entering blocked junction allowed as an example (why did I chose the longest name?!) we can have these states:
```
States:
- NotConfigurable(NA) (default 1 or default 0)
- Not Set: true by default or false by default.
- Forced: true or false
```
when we set a flag we force its value. if we force set it to default value it will not change if default changes (eg. change options or change road configuration). 
if we don't set the state then default value is used. `Not configurable` means that the default value cannot be changed. 

we have also these functions for every flag:
```
ToggleEnteringBlockedJunctionAllowed
SetEnteringBlockedJunctionAllowed bool
- NA => force set to input value 0 or 1(the values are lost on game load).
- else => force set to input value 0 or 1 (preserved on game load)

IsEnteringBlockedJunctionAllowed bool 
- not set => return default
- forced => return forced
- NA => return default

GetDefaultEnteringBlockedJunctionAllowed bool  
- set => return default
- not set => return default
- NA => return default

IsEnteringBlockedJunctionAllowedConfigurable bool  TICK logic
- NA => return true
- else => return false

GetEnteringBlockedJunctionAllowed => TernaryBool
- Not set => return TernaryBool.undefined
- NA  => if not set then return  TernaryBool.undefined else returned forced (true or false)
- forced => forced (true or false)
```
## Several problems:
 - (main problem) There is no interface for clearing forced values. this is important for #568 . Note that force setting the flag to default value is not same as not having the flag in the first place because the default value CAN change (change options or add/remove/upgrade segments). see screenshot.
 - SetEnteringBlockedJunctionAllowed does not check if IsEnteringBlockedJunctionAllowedConfigurable. This condition does not matter when using UI but can be reached by programming interface.
 - forced values are removed when they become un-configurable. But this does not work with the [corssings mod](https://steamcommunity.com/sharedfiles/filedetails/?id=427258853). you can put a crossing, set the U turn and then remove crossing but the U turn remains. it is lost on next game load though.

In the picture bellow I toggle every arrow a couple of times to force set it to its default value. but when I delete a segment the lane arrows do not change.
![Screenshot (328)](https://user-images.githubusercontent.com/26344691/73117507-4fae2300-3f4f-11ea-9eac-c49e60635740.png)

## Solution:
- introduce `Clear<traffic rule>()` methods in the interface
- `Set<Traffic rule>` to check for `Is<Traffic rule>Configurable` . This prevents programming errors.
- lane arrow manger to check for invalid arrow directions when segment layout changes.

**Comment by kianzarrin** [comment]
Solving this issue can give a big boost to #542. Is that OK if I start working on this now? if so please assign it to me (so that I know you agree with my approach)
tagging @aubergine10 @kvakvs @krzychu124 

Also I think it would be better to overload Set<traffic rule>( ... bool value) by Set<traffic rule>( ... TernaryBool value) to be able to clear traffic rule.

**Comment by kianzarrin** [comment]
Almost done here. one problem. 

Why does lane connector have configurable hotkey for delete? delete and backspace do the same thing (I have tested it). I am guessing this is a bug:
![Screenshot (378)](https://user-images.githubusercontent.com/26344691/73591393-c9698200-44f6-11ea-9785-f8365ace01d7.png)

I think all tools should use delete for removing traffic rules for all tools. no need to make it configurable. while configurability is good idea this is just too much!

**Comment by kianzarrin** [comment]
maybe we can assign backspace to remove traffic rules of a particular tool  and delete for removing all traffic rules?

**Comment by aubergine10** [comment]
Just random thought on this:

```
- NotConfigurable(NA) (default 1 or default 0)
- Not Set: true by default or false by default.
- Forced: true or false
```

Might be better as:

* `Vanilla` - just use vanilla value
    * I realise this is conceptually different to 'immutable'; maybe we need (separate?) immutable state?
* `Default` - TM:PE applied default (eg. user defined default road speed, or set default policies, etc)
    * Fallback to `Vanilla` value
* `Manual` - user made customisation at node/segment/lane-level
    * Fallback to `Default` value

**Comment by aubergine10** [comment]
> maybe we can assign backspace to remove traffic rules of a particular tool and delete for removing all traffic rules?

* `Backspace` -- for selected thing(s), remove customisations made by active tool
* `Alt+Backspace` -- for selected thing(s), remove customiations made by all tools

**Comment by kvakvs** [comment]
On Mac keyboards Delete does not exist as a separate button, you have to press Fn + Backspace, hence Backspace was added for convenience. Don't give them different meaning, for some users its the same Backspace key.

**Comment by aubergine10** [comment]
@kianzarrin Does this issue need retaining - eg. for speed limits and parking restrictions there is still no way to reset customisations.

**Comment by kianzarrin** [comment]
> @aubergine10 for speed limits and parking restrictions there is still no way to reset customisations.  

I don't know about them. Isn't parking restriction like priority sings, the states are:
- Not applicable
- allowed
- not allowed

so to restore to defaults I should just set it to allowed (if applicable).

I thought we have  a default speed limit. If my recollections are correct setting the default speed limit is same as not setting at all with the exception of the overlay symbol that is shown to the user and storage space. not ideal but its not a big issue.

I was under the impression that we have a 1+ issue per Pull request policy. if that is the case create new issues for them if not reopen this one. It has to be you because I don't use those tools too much.

**Comment by aubergine10** [comment]
Continued in #692
