### ISSUE TITLE
lane connector should raycast the whole lane

### ISSUE THREAD

**Issue by kianzarrin** [krzychu124/Cities-Skylines-Traffic-Manager-President-Edition#625]
see #543 

in https://github.com/krzychu124/Cities-Skylines-Traffic-Manager-President-Edition/issues/543#issuecomment-549069179 @krzychu124 fixing the rendering problem.

EDIT: the current ray-casting would work just fine. 
meanwhile this issue is for making it easier to hover over lane node markers by making the whole lane hover-able.

~~This issue is for fixing the ray-casting problem.
I intend to use `GetClosestLane()`. should be a piece of cake! ~~

**Comment by kianzarrin** [comment]
I gave up on trying to measure the HitPos and instead decided to use full lane markers from the old Traffic++ code.

The freaking HitPos has +-2meter error which is good enough for hovering over segments but way too poor for lane detection. I wrote a code to hover on the exact place of the circle of the lane marker but it intermittently fails because of the inaccuracy in all x  y z directions (it seems that the position is on the mouse-ray but it penetrates the segment a bit before it gets a hit.

It might be able to fix the problem by measuring height of the lane bezier. after measuring the vertical penetration of the mouse ray we can also calculate the x and y penetration too.

in https://github.com/krzychu124/Cities-Skylines-Traffic-Manager-President-Edition/issues/543#issuecomment-549069179 @krzychu124 said he will fix the way things are rendered at which point it would not be necessary to use the hitpos anymore.

So i decided to abort this issue.

**Comment by kianzarrin** [comment]
even thought fixing hitpos is necessary temporarily I could not resist the urge to fix it lol!
I have made partial progress.

**Comment by kianzarrin** [comment]
Its working!
![Screenshot (370)](https://user-images.githubusercontent.com/26344691/73537824-16375500-4432-11ea-99a0-825774b8b972.png)

**Comment by kvakvs** [comment]
Can highlighted lane gain the same color as the connector node?

**Comment by aubergine10** [comment]
At a guess the lane highlight is just there as visual aid during dev testing?

**Comment by kvakvs** [comment]
More visual feedback is nice when a connector origin circle is obstructed by traffic. But maybe some won't like it. Maybe show it only when something liek Shift is held for now, later when i work on the tool UI maybe there will be some space for a toggle switch.

**Comment by kianzarrin** [comment]
@aubergine10 No the white line is not a dev thing. Its final product. I did not show all segment lane markers because i did not wanted it to look like xmass.

> @kvakvs More visual feedback is nice when a connector origin circle is obstructed by traffic. But maybe some won't like it. Maybe show it only when something liek Shift is held for now,

The segment lane marker does not appear when the user is hovering over the lane marker circle. It only appears if the lane marker is hovered as a result of user hovering over the rest of the lane and not the circle. This approach in my opinion is better than the shift thing you mentioned. I can make it same color as node marker.
