### ISSUE TITLE
Enable github pages for /docs

### ISSUE THREAD

**Issue by aubergine10** [krzychu124/Cities-Skylines-Traffic-Manager-President-Edition#642]
Aiming for 11.1, but would be sweet if we could get it done today for 11.0 release (depends on DNS propagation time but as nothing is yet caching `tmpe.me` it hopefully will be fresh from get go).

@krzychu124 : Enabling github pages - In GitHub: Settings tab > GitHub Pages

1. Source: master branch /docs folder
2. Theme: Cayman (it will do for now)
3. Custom domain: `tmpe.me`

@kvakvs : Linking to custom domain:

* Requires github pages to have been setup first, as per steps above
* See: https://help.github.com/en/github/working-with-github-pages/managing-a-custom-domain-for-your-github-pages-site

> The actual content of the docs site will just organically grow via PRs (possibly create docs branch for faster commits, then that can go through intermittent PRs to merge in to master?). Plan is to develop docs on github wiki, then every so often do a bulk update of `/docs` folder with content from the wiki. In theory the wiki (which is just a git repo) could be treated as a submodule. So lots of things to investigate at later date.

**Comment by kvakvs** [comment]
Poke me on Discord for setting up NS records and proving the domain ownership to Github.

**Comment by aubergine10** [comment]
This initial stage is complete; @kvakvs if you need anything regarding SSL either reopen this or create new issue.

**Comment by kvakvs** [comment]
I am waiting for @krzychu124 to click "Enforce SSL" and see what happens. It should become clickable in a few hours from the time of this comment.

**Comment by krzychu124** [comment]
@kvakvs `HTTPS` enforced and it's working 🙂
