### ISSUE TITLE
Social image for docs site

### ISSUE THREAD

**Issue by aubergine10** [krzychu124/Cities-Skylines-Traffic-Manager-President-Edition#643]
@FireController1847 You able to do this?

Setting this for 11.1 milestone, but would be great if we coud get it today for 11.0 release.

Need an image 1280×640px to associate with github repo and docs site. It's used for social media preview whenever anyone links to our repo or docs.

No mention of LABS or STABLE, or version, just generic TMPE. Could possibly just be bigger version of the generic image that's currently on LinuxFan workshop page.

> The image gets uploaded to repository settings screen, not the repo, so it won't bloat the git history.

**Comment by FireController1847** [comment]
I mean, why not just use the one that's currently on the LinuxFan TM:PE page? How big do you need it, that one is a fairly large one?

If you need a transparent one I can send you that

**Comment by aubergine10** [comment]
The github settings screen recommends 1280×640px for best results; I think the one currently on linuxfan page is smaller than that?

**Comment by FireController1847** [comment]
Alright, I'll upscale it to that and send the non-transparent one here and the transparent one in the Discord

**Comment by FireController1847** [comment]
![WIKI_LOGO_BG](https://user-images.githubusercontent.com/16494272/73675763-49672780-4670-11ea-8645-6f0ff30c0950.png)

I've upscaled it easily to 1280x640 with no apparent quality loss. I sent you the transparent version on Discord and here is the background-based version

**Comment by aubergine10** [comment]
transparent version for safe keeping

![WIKI_LOGO_TRANS](https://user-images.githubusercontent.com/1386719/73678493-6885a980-46b0-11ea-80a4-b9e2d76770f0.png)
