### ISSUE TITLE
V11.0: Vehicles does a slight pause at Give Way sign even when there's no traffic

### ISSUE THREAD

**Issue by rogermartensson** [krzychu124/Cities-Skylines-Traffic-Manager-President-Edition#650]
### Describe the problem

When a vehicle come to a cross road where the Give Way sign is set it does a slight Pause even
if there is no traffic on the road where it is entering. This wasn't happening pre-v11.

It's almost like a stop sign but without a full stop.

### Steps to reproduce
Create a Round about. Vehicles entering the round about will pause slightly.

**Comment by aubergine10** [comment]
Hi - please [provide the information listed in #655](https://github.com/krzychu124/Cities-Skylines-Traffic-Manager-President-Edition/issues/655) - it will hopefully enable us to isolate and diagnose the problem.

**Comment by rogermartensson** [comment]
I'll try to dig after the Log-file even if I don't experience an visual error of any kind.
I'll try to reproduce the problem in a new save game.

The only difference between noticing this  "No pause" to "Slight pause" in Give Way-junctions was me doing a unsubscribe old, subscribe new, start game and load city.

If I change Give Way to a Stop sign it acts like it should. Cars make a full stop and accelerate out into the junction when it's clear. Change back to Give Way it does an "slight almost stop" and accelerate. Even when there isno car in road/round about. I've noticed that sometimes it will "let through" one or two cars and then revert back to "slight pause".

This behaviour makes cars stack up on my more used roads creating queues.
I hope we can find what is creating this.

**Comment by rogermartensson** [comment]
I've added the requested information in #655.

**Comment by aubergine10** [comment]
Fixed by  #662 - will be part of the 11.1 release (LABS page will get 11.1 update first)
