### ISSUE TITLE
v11: Vehicles stuttering or stopping at yield signs?

### ISSUE THREAD

**Issue by aubergine10** [krzychu124/Cities-Skylines-Traffic-Manager-President-Edition#655]
Just creating this issue to track a possible bug; several users have reported that since moving from v10 to v11 that vehicles are no longer fluidly moving through yield signs.

More information is required to confirm and subsequently diagnose the problem.

----

**If you are experiencing this problem, please provide the following information:**

1. A [save game](https://github.com/krzychu124/Cities-Skylines-Traffic-Manager-President-Edition/wiki/Share-your-Savegame-on-Steam) that exhibits the problem
    * You can either share to steam workshop (see link above) or drag a zip of the savegame on to the comment box
    * Please indicate where we should be looking on the map (eg. district name or screenshots)
2. The [game log file](https://github.com/krzychu124/Cities-Skylines-Traffic-Manager-President-Edition/wiki/Share-your-Cities-Skylines-log-file) and also the [TMPE.log](https://github.com/krzychu124/Cities-Skylines-Traffic-Manager-President-Edition/wiki/TMPE.log)
    * You can just drag the files on to a comment box, or upload to a public file sharing service
3. (Optional) Any [screenshots](https://github.com/krzychu124/Cities-Skylines-Traffic-Manager-President-Edition/wiki/Share-screenshots) that may help us understand (eg. a screenshot of your junction customisations)
    * Just drag them on to comment box, or upload to https://imgur.com and share the link

----
Possibly related issues: #650, #448

**Comment by rogermartensson** [comment]
Here is some data. 

[TMPE.log](https://github.com/krzychu124/Cities-Skylines-Traffic-Manager-President-Edition/files/4166549/TMPE.log)
[output_log.txt](https://github.com/krzychu124/Cities-Skylines-Traffic-Manager-President-Edition/files/4166550/output_log.txt)
Save game: https://steamcommunity.com/sharedfiles/filedetails/?id=1990217485

Save game is built with Cities standard assets. Nothing special.
The best place to notice the pause/stutter/stop is in the round about.

This is a short clip showing what is happening.
![car-slight-pause](https://user-images.githubusercontent.com/12293031/73961108-45573600-490c-11ea-948c-7be387212060.gif)

**Comment by Priplq** [comment]
Some data:
[output_log.txt](https://github.com/krzychu124/Cities-Skylines-Traffic-Manager-President-Edition/files/4167418/output_log.txt)
[TMPE.log](https://github.com/krzychu124/Cities-Skylines-Traffic-Manager-President-Edition/files/4167420/TMPE.log)

[TMPE v11 YIELD BUG.zip](https://github.com/krzychu124/Cities-Skylines-Traffic-Manager-President-Edition/files/4167428/TMPE.v11.YIELD.BUG.zip)

First file "TMPE v11 BUG" is my main save, but it has a lot of assets. U can see any roundabout or at District "Little Russia" the roundabout connecting the highway and the district(its only 1 connection)

Second file "TMPE v11 BUG new save" is a newly build "city" with standart assets, i just saved when cars are approaching the roundabout from the highway. Its only 1 square city, build it for the purpose of this post. 

Additional info. I did the unsucsribe from v10, game was not launched, subscribed to v11 alpha(didnt have stable yet then), then unsubscribed from the alpha and subscribed to stable. It persisted in both alpha and stable.

**Comment by krzychu124** [comment]
@rogermartensson , @Priplq thanks for reports.
Both `v11` versions are currently identical. 
I found the problem, but now I'm searching for root. 
I can't find what is causing vehicles to complete stop for fraction of a second. 
BTW, there were 12 alpha versions before releasing as Stable and I don't remember that anyone reported that problem :/

**Comment by Priplq** [comment]
@krzychu124 TBH i didn't notice it at the beginning, like 50hours+ but then there was this roundabout where traffic was moving only straight 90% of it, and from there I noticed cars were stopping for no reason, after that every roundabout seemed off flow wise...  More or less like a Baader-Meinhof phenomenon; Hard to notice if you don't know about it :>

BTW great job on this version, digging the game smoothness with AI on and the new additions, specially the lane arrow shortcut 💯

**Comment by krzychu124** [comment]
@Priplq you can try temporal solution by tweaking settings in `TMPE_GlobalConfig.xml` (you can reset it in mod options later)

Change number value in this line:
```xml
<MaxYieldVelocity>2.5</MaxYieldVelocity> 
```
to e.g. `3` or `4`
I will increase max velocity of vehicle approaching yield sign.
`2.5` == 20km/h - `(value * 8 = speed limit in km/h)`

**Comment by aubergine10** [comment]
_edits documentation_ ...

**Comment by Priplq** [comment]
OK so:
3 - kinda better but nah
4 - noticeably better, but still there was some unnatural "stuttering"
5 - 5 looks rly good but sometimes they kinda cut off the cars in the roundabout

IMO maybe some re-balancing between 4 and 5, if that's the issue. Cause i had some old logs from v10 STABLE version, didn't see any difference in the priority values. Only difference in "Advance Vehicle AI" is:

<MinMinSafeSpeedImprovement />
    <MaxMinSafeSpeedImprovement />

In the v11 it's 5 and 30 respectively, the v10 has no values. If that's any help, dunno. Thank you!! I will try some values between 4 and 5, flows a lot better now

**Comment by krzychu124** [comment]
I will fix it, it's temporary solution 😃 
I will check what those options do.

**Comment by Priplq** [comment]
I meant the v11 has no values, v10 has the 5 and 30, my bad.

**Comment by aubergine10** [comment]
We'll be releasing a fix for this issue to the v11 LABS workshop page hopefully in next 24 hours.
