### ISSUE TITLE
Lane arrows: Ctrl+Click turning lanes - lane going wrong way?

### ISSUE THREAD

**Issue by aubergine10** [krzychu124/Cities-Skylines-Traffic-Manager-President-Edition#671]
From steam user [adam.ruscoe](https://steamcommunity.com/workshop/filedetails/discussion/1637663252/1777135944129275602/?tscn=1581156451):

> Not seen this noted as an "issue" on the thread as yet...  
> I love the ctrl click set everything to one lane per action, **but on a two lane each way section, with driving set to the right hand side the mod currently sets the right hand lane as turn right, with the left hand lane being turn left and straight on.**
> Given than on a RHD road where you have priority you may have to wait to turn left, but don't wait to turn right or go straight on this seems incongruous with how it is mostly laid out in real life (and how I always lay out my cities in game)
> Admittedly I've literally just downloaded it and come across this so there may be a setting somewhere I've missed, but as a default I can see that causing more issues than less.

Issue reported for STABLE v11.0

I've asked for screenshots and any other infos to be posted here.

**Comment by kianzarrin** [comment]
duplicates #567
