### ISSUE TITLE
2nd reporting of Mac with trouble loading TM 11.  

### ISSUE THREAD

**Issue by pallamf** [krzychu124/Cities-Skylines-Traffic-Manager-President-Edition#679]
### Describe the problem
See similar problem from Pallamf on Feb 8, 2020.  Start game, (with resume).  Game loads, but the menu bar loads slowly.  When finished, the game visually comes off pause but doesn't run.  All menus work, including TM 11, and keyboard scrolling.  The problem came back after working fine yesterday.

Note, the problem did resolve after enabling all three "Safe Mode" buttons in "Loading Screen Mod"

### Steps to reproduce

1. Open Steam
2. Click on Cities Skylines
3. Click on "resume"

### Log files

[Player with problem, pre safe mode.log](https://github.com/krzychu124/Cities-Skylines-Traffic-Manager-President-Edition/files/4177610/Player.with.problem.pre.safe.mode.log)

[Player Post Safe Mode.log](https://github.com/krzychu124/Cities-Skylines-Traffic-Manager-President-Edition/files/4177612/Player.Post.Safe.Mode.log)

**Comment by krzychu124** [comment]
Post [TMPE.log](https://github.com/krzychu124/Cities-Skylines-Traffic-Manager-President-Edition/wiki/Share-your-Cities-Skylines-log-file) and  [savegame.](https://github.com/krzychu124/Cities-Skylines-Traffic-Manager-President-Edition/wiki/Share-your-Savegame-on-Steam)
Usually when you can't unpause game it means that some internal process in the background is still processing something (updating terrain or something else)

**Comment by aubergine10** [comment]
```Simulation error: Array index is out of range.
  at TerrainManager.GetSurfaceCell```

Is identified as [Array index error - Symptom 11](https://github.com/krzychu124/Cities-Skylines-Traffic-Manager-President-Edition/wiki/Array-Index---Symptom-11)

Exiting game to desktop should fix it hopefully.

Important: DO NOT use the "unlock all tiles" button in 81 Tiles mod

If problems persist, please share additional files as requested by @krzychu124 in https://github.com/krzychu124/Cities-Skylines-Traffic-Manager-President-Edition/issues/679#issuecomment-583889649

**Comment by pallamf** [comment]
I turned off the 81 tiles (but left it subscribed).  I am now able to go in and play, using TM 11.

**Comment by aubergine10** [comment]
It's known bug with 81 Tiles (nothing to do with TM:PE) - when that button is clicked, it somehow corrupts data in the save game.

Strangely, the bug does not occur if you manually unlock each tile via the tile purchase screen in-game.

Usually exit to desktop will sort it, but sometimes it's worse and corrupts the save beyond repair. Very interesting to hear that disabling the mod allowed you back in to game, I will add that to the guide and hopefully it will help others with same problem. Hopefully BP can update 81 Tiles at some point to fix that bug.

I'll close this issue for now as you got your game working but let us know if you have any other problems with TM:PE 11.

**Comment by aubergine10** [comment]
BTW, if you need a 25 Tile mod, I recommend "Purchase It!" by keallu - it's been working very reliably for me and has solid set of features.
