### ISSUE TITLE
CSUR compatibility - TM:PE version number

### ISSUE THREAD

**Issue by aubergine10** [krzychu124/Cities-Skylines-Traffic-Manager-President-Edition#687]
@pcfantasy @kianzarrin @krzychu124 @kvakvs 

I saw in https://github.com/citiesskylines-csur/CSURToolBox/pull/1 that CSUR Toolbox won't patch TM:PE v11.1 or above?

Issue:

* PR #684 (TMPE fix for lane connectors) is not ready for publishing yet; needs more review & test
    * It is planned to be part of the main 11.1 release
* An 11.1 **beta** needs pushing to LABS as soon as possible so that end users can start testing a bunch of other feartures, enhancements and bug fixes

This means that the first 11.1 to hit LABS page is not going to have the CSUR road updates. It will likely be a second beta release to LABS that contains that code. Both will be v11.1

How do we handle this?

My suggestion is to use the `C` version, so 11.1.0, 11.1.1, etc.  So the CSUR toolbox would need to check for TM:PE version 11.1.1 or above (11.1.0 will be beta1, 11.1.1 will be beta 2 with the CSUR code, etc).

In terms of STABLE releases, they'd get periodical deployments of known-good LABS releases, for example it might be something like 11.1.3 that gets pushed to STABLE.

**Comment by kvakvs** [comment]
Publish LABS and let them catch up while its still in LABS?

**Comment by aubergine10** [comment]
CSUR has been updated on workshop to check for TM:PE 11.1.1
