### ISSUE TITLE
New Logo

### ISSUE THREAD

**Issue by FireController1847** [krzychu124/Cities-Skylines-Traffic-Manager-President-Edition#71]
> EDIT: Replaced images with links to avoid older versions mistakenly getting used for workshop pages
> -- aubergine10

----

As suggested by #51, we need a new logo. So, since I owned Photoshop and I was bored, I thought, "Hey, why don't I take a shot at this?" So I did! Here's some prototype logos. Please give me all your opinions, I'm ready to tweak this down to the last pixel!

Icon
[iconfinder_43_277444](https://user-images.githubusercontent.com/16494272/52686701-1df1a700-2f0c-11e9-850d-064526c412aa.png)

Text Logo
[logo](https://user-images.githubusercontent.com/16494272/52686580-a28ff580-2f0b-11e9-95d7-0d9ab25e04cf.png)

Workshop Thumbnail
[thumbnail](https://user-images.githubusercontent.com/16494272/52686584-a4f24f80-2f0b-11e9-8dae-c331828db2fb.png)

Workshop Preview
[preview](https://user-images.githubusercontent.com/16494272/52686585-a58ae600-2f0b-11e9-94f6-6e0dc6016d7f.png)

Workshop Thumbnail Example
[image](https://user-images.githubusercontent.com/16494272/52686746-53969000-2f0c-11e9-94ad-7373efa44587.png)

Workshop Preview Example
[image](https://user-images.githubusercontent.com/16494272/52686724-36fa5800-2f0c-11e9-8c73-0a1c7391f9e1.png)

**Comment by aubergine10** [comment]
Love it. The  icon works exactly as I'd hope, it really does stand out.

But ditch the underlines and **hue** changes on capital letters... users instinctively abbreviate, as they have done with existing logos.

There might be alternate fonts to try. Can you attach a zip of the traffic lights transparent png(s) to this issue?

**Comment by aubergine10** [comment]
For future reference, here is site of the artist who made the traffic light icon:

* http://www.icondrawer.com/icons_512_addon_preview.php
* https://dribbble.com/buzuk

**Comment by FireController1847** [comment]
I made the color changes and the underlines to make the text stand out and give it kind of a unique look to it. However, as requested, here's the versions without the hue and underline, which don't look half bad. As for the font, I went with Roadgeek 2005 Transport Heavy this time, to fit with the theme of roads. Let me know your opinion on it, and if it should be changed again. (If it should, try describing what you're envisioning, like if it should be a bolder or thinner font, letters closer together or further apart)

Text Logo
![logo2](https://user-images.githubusercontent.com/16494272/52763136-ccaee980-2fd7-11e9-98c5-9ec5de891eee.png)

Workshop Thumbnail
![thumbnail2](https://user-images.githubusercontent.com/16494272/52763141-d20c3400-2fd7-11e9-8615-d9c55b678682.png)

Workshop Preview
![preview2](https://user-images.githubusercontent.com/16494272/52763142-d59fbb00-2fd7-11e9-91d2-b2aa627c36cb.png)

Workshop Thumbnail Example
![image](https://user-images.githubusercontent.com/16494272/52763166-f405b680-2fd7-11e9-8a1a-100ef249ccea.png)

Workshop Preview Example
![image](https://user-images.githubusercontent.com/16494272/52763184-054ec300-2fd8-11e9-8595-36bed80f21f8.png)

**Comment by aubergine10** [comment]
Was going to suggest doing the logo for 1.10.16 milestone, but probably better to wait until we've got those pathfinder bugs fixed.

**Comment by krzychu124** [comment]
Haha, I'm still searching for those bugs... 😄

**Comment by FireController1847** [comment]
Alright. Let me know if you guys feel there should be any other changes. I recently got a student discount so I have Adobe Illustrator now too lol

**Comment by 1Tomber** [comment]
Hej @FireController1847,
great work, love the new logo and effort! I had a look at the terrible kerning (font/Roadgeek's fault) and did some test with changing the kerning to optical (in Illustrator) and looked for an alternative. Maybe we should take http://overpassfont.org/ in cosideration? It is a much more professional font and IMHO more true to the original Highway Gothic font.
While at it, I also tried different colors, arrows and compositions 🎨 I think colorwise there could me more emphasis on TM than on PE.

![trafficmanager_logo_tests](https://user-images.githubusercontent.com/24652659/53656959-201a6c00-3c55-11e9-94aa-6283570bbe34.gif)
...and here the Illustrator file: [logo_test_tomber.ai.zip](https://github.com/krzychu124/Cities-Skylines-Traffic-Manager-President-Edition/files/2920553/logo_test_tomber.ai.zip)

**Comment by FireController1847** [comment]
@1Tomber I do like the look of the smaller "President Edition" text over the Traffic Manager text, I think that's a nice edition. I experimented a ton with different arrows and symbols and, like you can probably tell, they all look kind of out of place. The only one that really fit was the original one.

I didn't know there was an official font for the United States road signs, although it does make sense. Overpass appears to look a lot more professional, I'll take a shot at that as well.

When it comes to those color combinations, I'm particularly fond of the blue on blue (dark below below, light blue above). I'll take a shot at that as well

**Comment by FireController1847** [comment]
Okay, so I tried out your color combination and it looks great. The font also looks amazing. I upsized the top text and made the bottom text a little smaller, and I think it looks good centered. What do you think?
![logo3](https://user-images.githubusercontent.com/16494272/53659842-b892fb00-3c19-11e9-8e7a-992a9ddad7c1.png)
![thumbnail3](https://user-images.githubusercontent.com/16494272/53659844-b892fb00-3c19-11e9-8e9c-199d7c74207b.png)
![preview3](https://user-images.githubusercontent.com/16494272/53659843-b892fb00-3c19-11e9-8b57-d079596465b2.png)
![image](https://user-images.githubusercontent.com/16494272/53659880-cfd1e880-3c19-11e9-8907-deab5ae6099a.png)
![image](https://user-images.githubusercontent.com/16494272/53659888-d7918d00-3c19-11e9-81e1-50ae7989a28e.png)

**Comment by krzychu124** [comment]
Great work @1Tomber and @FireController1847 !
@1Tomber I do like that transition between letter and icon.
@FireController1847 Yup, now that font color looks great.

**Comment by aubergine10** [comment]
I'm still not keen on that arrow thing (I don't even know what it means, something from USA I guess?) - maybe just remove the arrow thing? We have an international audience remember :)

For the thumbnail (shown in workshop summary pages) I'd suggest just the traffic light top-center with TM:PE underneath. Keep it super-simple.

On the mod detail page, the main panel will likely be populated with images depicting features (once we start reworking the UI etc) but yes would be nice to have a logo image in the short term.

For font, what about one of the [RoadGeek typefaces](https://www.fontspace.com/michael-d-adams/roadgeek-2005) - maybe ```Roadgeek 2005 Series B (Version 1.000 2)``` ?

**Comment by FireController1847** [comment]
@aubergine10 Basically the arrow is a sign found in the U.S., and it's more of a warning sign that there is a median coming up and you should be to the right of it. (See http://trafficsigns.ntsigns.com/viewitems/traffic-signs-usdot-regulatory-signs/keep-right-of-median-signs-r4-7 ). For the thumbnail, isn't that what it currently is? The traffic light is in the top-center with TM:PE underneath. Also, we've been using the Roadgeek fonts in the original imagery, hence the notice of a change to the Overpass font which looks better imo

**Comment by aubergine10** [comment]
For thumbnail, I meant "TM:PE" rather than the somewhat-wordy "Traffic Manager President Edition"

**Comment by FireController1847** [comment]
@aubergine10 I can do that. Are you okay with keeping the icon to the right of the main text?

**Comment by FireController1847** [comment]
With the resurrection of the STABLE TM:PE and the rebranding of LABS TM:PE, I've come up with a new idea for the logos. I also removed the disliked road icon, and shortened the thumbnail down to "TMPE". It may look weird at first with the color difference, but the more I looked at it the more I thought it looked good. I also created a new color for "LABS". What do you guys think?

# Thumbnails
![Thumbnail4](https://user-images.githubusercontent.com/16494272/57988261-3c09fe80-7a49-11e9-9f38-342a498978bb.png)
![Thumbnail4 LABS](https://user-images.githubusercontent.com/16494272/57988262-3f9d8580-7a49-11e9-8990-1710b11ba0e3.png)

# Logos
![Preview4](https://user-images.githubusercontent.com/16494272/57988264-475d2a00-7a49-11e9-8d25-aa5cd9cbbb35.png)
![Preview4 LABS](https://user-images.githubusercontent.com/16494272/57988265-4a581a80-7a49-11e9-9775-fa708d54402e.png)

**Comment by aubergine10** [comment]
I FREAKING LOVE THAT!!!!!!!

Dude, that's some god-tier gestalt right there! <3 <3 <3

LOVE IT!!!!!!!!!

Maybe a couple of very minor tweaks though:

1. On the square "TMPE LABS" thumbnail image, maybe reduce the font size a little? Ideally the traffic light should be in same position on both thumbnails, and for that to happen the TMPE LABS text would need to be a little smaller.
2. On the larger rectangular images, left-align the "President Edition" with "Traffic Manager"; Centering the text like it currently is makes it look a little messy.

But overall I freaking love those new versions you did, they look really professional!

**Comment by aubergine10** [comment]
3. Maybe reduce the text/image content on the larger rectangular images to create more "breathing space" around the edge of the image content; make it look less crowded. I see you already have same padding around the image/text (great!) - just needs more padding imo.

**Comment by FireController1847** [comment]
Ask and you shall recieve!

# Thumbnails
Note: It's really not possible to keep the image centered while adding on the "LABS" text; they will be off just by a little bit, but that should be okay.
![Thumbnail5](https://user-images.githubusercontent.com/16494272/58051306-10514c00-7b0f-11e9-8546-13b1dd0a9a68.png)
![Thumbnail5 LABS](https://user-images.githubusercontent.com/16494272/58051315-134c3c80-7b0f-11e9-8728-a11ce073fd5d.png)

# Logos
![Preview5](https://user-images.githubusercontent.com/16494272/58051356-2bbc5700-7b0f-11e9-89a0-78252686edb6.png)
![Preview5 LABS](https://user-images.githubusercontent.com/16494272/58051358-2ced8400-7b0f-11e9-9e67-607f07634229.png)

**Comment by aubergine10** [comment]
Perfect!

**Comment by FireController1847** [comment]
Awesome. Just so we're all good, I will be marking the last posted ones as the final version. The following file is a zip file containing the icon and the psd file for the icon, as well as the logos and the corresponding psd files. Glad I was able to help out with this, it was a lot of fun and I'm very happy to see the outcome!

[TMPE Branding.zip](https://github.com/krzychu124/Cities-Skylines-Traffic-Manager-President-Edition/files/3200399/TMPE.Branding.zip)

**Comment by aubergine10** [comment]
Reopening until workshop pages are updated
