### ISSUE TITLE
Steam user saying mod isn't pulling settings from old version

### ISSUE THREAD

**Issue by aubergine10** [krzychu124/Cities-Skylines-Traffic-Manager-President-Edition#72]
From our TMPE workshop page:

> Hindi 1 hour ago  
> i activated this one and deactivated the old TMPE in the content manager, but in my save, nothing has been carried over
> Was that the way to go, or do i have to unsubscribe before subscribing?

# Solution

If you are experiencing this issue, please follow these steps: [Troubleshooting guide](https://github.com/krzychu124/Cities-Skylines-Traffic-Manager-President-Edition/wiki/Settings-not-copied-from-old-TMPE)

**Comment by krzychu124** [comment]
I can't answer now but he has to unsubscribe from old TMPE before enabling this mod.

BTW I've added notification for it if user did not unsubscribed (it's checking user content manager for mod by steamId) maybe there is a bug...

**Comment by aubergine10** [comment]
Thanks :)

I've relayed that to the user and asked him to check a few things, I'll report back here if there's any progress or further action needed.

**Comment by aubergine10** [comment]
> I didnt unsubscribe, just deactivated in content manager. Is that the problem?
>  
> Everything wasnt cariied over, no settings, and no lane connections, speed limit, junction settings etc
>  
> I loaded a savegame

I've asked them to unsub the old mod, and also to share the savegame.

Will report back with updates.

**Comment by aubergine10** [comment]
Apparently he had to quit Cities.exe and reload before it started working.

I'm guessing this has something to do with the mod not handling second load (eg. load from pause menu, or return to main menu then load) without app quit?

**Comment by aubergine10** [comment]
Added troubleshooting guide in case other people have same problem: https://github.com/krzychu124/Cities-Skylines-Traffic-Manager-President-Edition/wiki/Settings-not-copied-from-old-TMPE

**Comment by DaHindi** [comment]
Heyho, here I am
I quitted back to desktop (no loading from pause menu as of the known issues it can cause)

**Comment by aubergine10** [comment]
@DaHindi is the settings bug solved now? If so, please close issue.

**Comment by FireController1847** [comment]
@aubergine10 I am confuzzled, how does he close the issue if you made it?

**Comment by aubergine10** [comment]
Ah, good point! I'll close the issue then. If you have any more problems with settings let us know :)

**Comment by DaHindi** [comment]
Yes, i could load the settings
