### ISSUE TITLE
Mod name change in workshop an mod manager

### ISSUE THREAD

**Issue by aubergine10** [krzychu124/Cities-Skylines-Traffic-Manager-President-Edition#74]
The current mod name "Traffic Manager: President Edition - Industries Updated" is causing confusion in a few areas:

1. People keep asking if it needs Industries DLC
2. It's difficult to discern in Content Manager > Mods list for some users (those who generally tend to struggle with all-things-mod related)

For the title shown in Steam Workshop, I suggest just: **Traffic Manager: President Edition**

* We'd need to update to new logo (see #71) to visually differentiate from old mod

For the title shown in Content Manager > Mods, I suggest just: **TM:PE**

* This will make clear distinction between TMPE editions in the mod list and mod settings list
* In mod settings list, it will make TM:PE easier to find for those of us with >50 active mods

> Note: I don't know if name change will affect mod settings (eg. file paths) or anything?

**Comment by krzychu124** [comment]
Good point, I will change that later today

**Comment by aubergine10** [comment]
I noticed name is also updated in workshop :)

**Comment by FireController1847** [comment]
I'm not entirely sure I understand the purpose of naming the mod "TM:PE" inside the content manager? Wouldn't the user be able to tell which one they're using by looking at the version?

**Comment by aubergine10** [comment]
It's not just differentiation from old mod, it's also differentiation from all the other mods. I've got 100+ mods installed, most of them have long names. A short name stands out more, easier to find in the list.

**Comment by FireController1847** [comment]
You sound like you know what you're talking about 😉, so I believe you. Makes sense to me!
