### ISSUE TITLE
Credits page

### ISSUE THREAD

**Issue by aubergine10** [krzychu124/Cities-Skylines-Traffic-Manager-President-Edition#79]
I've been working on a credits page, for example to attribute some of the key devs, icon artists, etc.

If you want to take a look, make changes, etc., here it is:

https://github.com/krzychu124/Cities-Skylines-Traffic-Manager-President-Edition/wiki/Credits

It should eventually be moved from the wiki to the main repository, but wanted to check with you folks to see if it needs changing first.

Also, I have trouble tracking down some of the icons, particularly some of the vehicle and junction restriction icons. They seem to have  been added by @VictorPhilipp but not sure where he sourced them from.

**Comment by FireController1847** [comment]
I see some of the features are missing credits. For the icons, which ones in particular are you looking for? Are they in the resources folder under TLM/TLM/Resources?

**Comment by aubergine10** [comment]
The icons listed on that page that don't give details of who designed them are the ones I'm interested in. Yes, they are in TLM/TLM/Resources folder. They were added to TMPE by Victor (LinuxFan).

I didn't add the traffic lights ones as I think the entire traffic lights UI is going to end up being replaced (its current form is just too confusing for most users).

**Comment by FireController1847** [comment]
The things on the junctions panel is missing credits?

**Comment by aubergine10** [comment]
Yes, the icons for Junction Restrictions and also some of the Vehicle Restrictions - I could not find details about who created the artwork for those icons. (I put them in the list as a reminder that we need to find out who made them). I searched through Noun Project website, which has huge numbers of icons, but couldn't find exact matches to the glyphs.

**Comment by FireController1847** [comment]
You're making this really hard for me to try and be sincere about it lol

*cough* Turn on Red *cough*

**Comment by aubergine10** [comment]
Ah, that icon wasn't there when I started making the list. Added now :)

**Comment by aubergine10** [comment]
@VictorPhilipp can you remember where you got the icons from: https://github.com/krzychu124/Cities-Skylines-Traffic-Manager-President-Edition/wiki/Credits

**Comment by aubergine10** [comment]
Credits page updated with all available info, unlikely to find sources of remaining icons (mostly vehicle restrictions).
