### ISSUE TITLE
Array out of range

### ISSUE THREAD

**Issue by DaHindi** [krzychu124/Cities-Skylines-Traffic-Manager-President-Edition#82]
I get the following error now every few minutes. The number of errors at one time varies from 1 to about 10.
In outputlog theres no error output before (Only the succesful initiation pf the graphics card)

Simulation error: Array index is out of range.
at PassengerTrainAI.SimulationStep (UInt16 vehicleID, .Vehicle& vehicleData, .Frame& frameData, UInt16 leaderID, .Vehicle& leaderData, Int32 lodPhysics) [0x00000] in <filename unknown>:0 
at VehicleAI.SimulationStep (UInt16 vehicleID, .Vehicle& vehicleData, UInt16 leaderID, .Vehicle& leaderData, Int32 lodPhysics) [0x00000] in <filename unknown>:0 
at TrafficManager.Custom.AI.CustomTrainAI.CustomSimulationStep (UInt16 vehicleId, .Vehicle& vehicleData, Vector3 physicsLodRefPos) [0x00000] in <filename unknown>:0 
at VehicleManager.SimulationStepImpl (Int32 subStep) [0x00000] in <filename unknown>:0 
at SimulationManagerBase`2[Manager,Properties].SimulationStep (Int32 subStep) [0x00000] in <filename unknown>:0 
at VehicleManager.ISimulationManager.SimulationStep (Int32 subStep) [0x00000] in <filename unknown>:0 
at SimulationManager.SimulationStep () [0x00000] in <filename unknown>:0 
at SimulationManager.SimulationThread () [0x00000] in <filename unknown>:0 [Core]

(Filename: C:/buildslave/unity/build/artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

What can cause this issue? I found a few posts over the years with the same error but no solution. As traffic manager is included, can that be the cause?

**Comment by aubergine10** [comment]
Can you share your savegame to workshop so we can investigate further?
See: [How to share save game on Steam](https://github.com/krzychu124/Cities-Skylines-Traffic-Manager-President-Edition/wiki/Share-your-Savegame-on-Steam)

Also if you could share your log file (you can drag-drop it on to a github comment box) that would be useful too in case there are any errors that occurred that might have triggered the recurring error. See: [Log file locations](https://github.com/krzychu124/Cities-Skylines-Traffic-Manager-President-Edition/wiki/Share-your-Cities-Skylines-log-file)

**Comment by krzychu124** [comment]
Hi @DaHindi unfortunately this is not part of our mod. 
Please check if you have any mod which improves passenger train AI

**Comment by DaHindi** [comment]
I now see, theres also a citizen not found error...

[output_log.txt](https://github.com/krzychu124/Cities-Skylines-Traffic-Manager-President-Edition/files/2865128/output_log.txt)

https://steamcommunity.com/sharedfiles/filedetails/?id=1655238807

What mods can improve Passenger Train AI? IPT2? MOM? RealTime?

**Comment by krzychu124** [comment]
MOM is doing something with passegnerAI but iirc you can disable it in MOM options menu

**Comment by aubergine10** [comment]
IPT2 and MOM do.

Random thought: Could this be related to #55

**Comment by DaHindi** [comment]
Disbaling PassengerAI in MOM Options led to the same error after few minutes, but this time they were perpetual

**Comment by DaHindi** [comment]
I think it was related to a deleted metro line. At a save before that, there is no error anymore

**Comment by krzychu124** [comment]
BTW did you created save in between mod update and hotfix few hours later?
[Changelog with timestamps here](https://steamcommunity.com/sharedfiles/filedetails/changelog/1637663252)

There was a bug in update which prevents loading TM:PE settings. If you saved your game between update but before hotfix release any of TM:PE settings wasn't saved.

**Comment by DaHindi** [comment]
I have to look tomorrow

**Comment by DaHindi** [comment]
Nope, didnt have the mod at this time

**Comment by aubergine10** [comment]
@DaHindi did you ever get this error resolved?

**Comment by aubergine10** [comment]
Closing this as no response.

If the issue persists, please see [this troubleshooting guide](https://github.com/krzychu124/Cities-Skylines-Traffic-Manager-President-Edition/wiki/Simulation-error%3A-Array-index-is-out-of-range) which lists all known causes of the **Array index** error and how to fix them.
