### ISSUE TITLE
Mod description page

### ISSUE THREAD

**Issue by aubergine10** [krzychu124/Cities-Skylines-Traffic-Manager-President-Edition#87]
Pondering text update for Steam Workshop page (not any time soon, probably want to get the UI stuff done first).

> I'm using github blockquotes to represent steam quote panels

----

Realistic road and rail traffic for your city - traffic uses all lanes, and follows the rules you set.

> Unsubscribe the [old Traffic Manager mod](https://steamcommunity.com/sharedfiles/filedetails/?id=583429740) first. Your old settings and customisations will still work!
>  
> [Incompatible Mods](https://github.com/krzychu124/Cities-Skylines-Traffic-Manager-President-Edition/wiki/Installation) • [Report a bug](https://github.com/krzychu124/Cities-Skylines-Traffic-Manager-President-Edition/wiki/Report-a-Bug) • [User Guide](https://github.com/krzychu124/Cities-Skylines-Traffic-Manager-President-Edition/wiki)

> (date of latest change) - (very brief summary) [More info...](https://steamcommunity.com/sharedfiles/filedetails/changelog/1637663252)

**Control your traffic**

Set speed limits and vehicle restrictions, edit traffic lights and lane arrows, road rules...

(gif)

**Split passenger and cargo trains**

Sort trains on to different routes, make cargo trains yield to passenger trains...

(gif)

**Extreme parking**

It's like watching paint dry, only more extreme. Who knew parking could be so much fun?!

(gif)

**Reckless drivers**

Watch in horror as some drivers ignore traffic lights, speed limits and vehicle restrictions...

(gif)

**Only use what you need**

Disable features you don't use - the mod instantly recompiles itself to remove unwanted code to get the best possible performance.

**Comment by krzychu124** [comment]
Thanks.
I'm still fighting with those lane connections... 😕

**Comment by aubergine10** [comment]
@krzychu124 could we get description of LABS updated to following bbcode:

```
Realistic road and rail traffic for your city - traffic uses all lanes and follows the rules you set.

[quote]
[h1]LABS is where we beta test new features and bug fixes for Traffic Manager.[/h1]

[list]
[*] [LABS](https://steamcommunity.com/sharedfiles/filedetails/?id=1637663252) might contain bugs, but they are usually fixed quickly
[*] [STABLE](https://steamcommunity.com/sharedfiles/filedetails/?id=583429740) is more reliable, but gets updated much less frequently
[*] [b]Only use one version at a time - unsubscribe the other to avoid conflicts![/b]
[/list]

[url=https://steamcommunity.com/workshop/filedetails/discussion/1637663252/1678063648163943780/]Incompatible mods[/url] • [url=https://steamcommunity.com/linkfilter/?url=https://discord.gg/faKUnST]Discord chat[/url] • [url=https://tmpe.viathinksoft.com/wiki/index.php?title=Main_Page]User guide[/url]
[/quote]

[quote]
[h1]Version %whatever%:[/h1]

[list]
[*] %Release notes%
[/list]

[url=https://github.com/krzychu124/Cities-Skylines-Traffic-Manager-President-Edition/wiki/Report-a-Bug]Report a Bug[/url] • [url=https://github.com/krzychu124/Cities-Skylines-Traffic-Manager-President-Edition]Source Code[/url] • [url=https://github.com/krzychu124/Cities-Skylines-Traffic-Manager-President-Edition/wiki/Contributing]Contribute or Translate[/url]
[/quote]
```

Notable features:

* Text intro first = shown in workshop tooltips
* Shrunk everything down to two boxes
* Fewer links, more gestalt :)

Note; Sometimes list and quote tags insert extra blank lines so the bbcode might need tweaking after update.

**Comment by aubergine10** [comment]
Made obsolete by #432
