### ISSUE TITLE
FileNotFoundException: Could not load file or assembly 'TrafficManager

### ISSUE THREAD

**Issue by aubergine10** [krzychu124/Cities-Skylines-Traffic-Manager-President-Edition#90]
Report from Sp3ctre18 on Steam workshop page.

> I should add that when I tried I got an un-passable error of "could not load file or assembly 'TrafficManager."

Log file: https://www.pastefs.com/pid/101223

Log file with all mods enabled: https://www.pastefs.com/pid/101224

Another log file (Bulldoze It! and Nursing Home Mod were disabled for this one): https://www.pastefs.com/pid/101225

Related forum post with list of mods, etc: https://forum.paradoxplaza.com/forum/index.php?threads/cities-skylines-steam-cant-find-culprit-of-array-index-is-out-of-range.1153131/

Apparently the error occurred after disabling TMPE and then loading a save in which TMPE had been active.

~~This could be relate to #82, still investigating.~~

# Solution

The error is caused by AdvancedJunctionRule mod. See this [Troubleshooting Guide](https://github.com/krzychu124/Cities-Skylines-Traffic-Manager-President-Edition/wiki/FileNotFoundException%3A-Could-not-load-file-or-assembly-%27TrafficManager%27) for fix.

**Comment by aubergine10** [comment]
User has multiple [Incompatible Mods](https://github.com/krzychu124/Cities-Skylines-Traffic-Manager-President-Edition/wiki/Incompatible-mods) installed. Also, many old mods and mods with overlapping functionality (see: [Recommended Mod Substitutions](https://github.com/krzychu124/Cities-Skylines-Traffic-Manager-President-Edition/wiki/Recommended-Mod-Substitutions)).

**Comment by aubergine10** [comment]
⚠️ **Central Services Dispatcher** mod has been added to incompatible mods list (it states it's incompatible [on their website](http://dinkytoyz.github.io/wtmcsServiceDispatcher/docs/1.1/Incompatibilities)).

**Comment by aubergine10** [comment]
In first log file (101223 in url above), this is the error:

```
FileNotFoundException: Could not load file or assembly 'TrafficManager, Version=1.0.6980.25068, Culture=neutral, PublicKeyToken=null' or one of its dependencies.
  at AdvancedJunctionRule.RoadUI.Start () [0x00000] in <filename unknown>:0
(Filename:  Line: -1)
Simulation error: Could not load file or assembly 'TrafficManager, Version=1.0.6980.25068, Culture=neutral, PublicKeyToken=null' or one of its dependencies.
  at ThreadingWrapper.OnBeforeSimulationFrame () [0x00000] in <filename unknown>:0
  at SimulationManager.SimulationStep () [0x00000] in <filename unknown>:0
  at SimulationManager.SimulationThread () [0x00000] in <filename unknown>:0   [Core]
```

**Comment by krzychu124** [comment]
Yup, I can see this...

**Comment by aubergine10** [comment]
Updated some broken links in OP.

Basically his mods are a mess, I think. Although that error posted in my last comment leads me to believe there is something wrong with the recently added "Turn on Red" feature.

**Comment by krzychu124** [comment]
Haha, look inside your output_log 😉

**Comment by aubergine10** [comment]
> Haha, look inside your output_log 😉

With over 100 mods active, I have two errors in my log. One from District Service Limit 3, and one from TM:PE...

```
Colossal Handler caught: 
  at (wrapper managed-to-native) UnityEngine.Component:GetComponentFastPath (System.Type,intptr)
  at UnityEngine.Component.GetComponent[CustomKeyHandler] () [0x00000] in <filename unknown>:0 
  at TrafficManager.UI.UIBase.Finalize () [0x00000] in <filename unknown>:0 
```

**Comment by krzychu124** [comment]
Ok, good to know.
Mine warning seems to be different because I use own build which I copy to AppData
```Non platform assembly: data-000000001AE54040 (this message is harmless)
Fallback handler could not load library D:/steamapps/steamapps/common/Cities_Skylines/Cities_Data/Mono/data-000000001AE54040.dll
Assembly TrafficManager, Version=1.0.6986.3487, Culture=neutral, PublicKeyToken=null loaded.  [Mods - Internal]```

Oh.. now I see...
Your error come from new Esc key handler (Interesting, I will check later why it's happening but as you can see game caught that error without throwing popup or crash)

**Comment by aubergine10** [comment]
I'll create new issue to track my error

**Comment by krzychu124** [comment]
What is  AdvancedJunctionRule?? Mod? I can't find this text neither in base game and our mod.

**Comment by aubergine10** [comment]
> What is AdvancedJunctionRule?

It's the mod by pcfantasy: https://steamcommunity.com/sharedfiles/filedetails/?id=1647686914

The one with the vehicles driving into junction and waiting for gap in traffic.

**Comment by krzychu124** [comment]
Line 56267 and more (around 10k 😄 )
``` FileNotFoundException: Could not load file or assembly 'TrafficManager, Version=1.0.6980.25068, Culture=neutral, PublicKeyToken=null' or one of its dependencies.  at AdvancedJunctionRule.RoadUI.Start () [0x00000] in <filename unknown>:0```

**Comment by krzychu124** [comment]
Ok I know what is going on with this error above.
That error was from log when user unsubscribed TrafficManager which is one of dependencies of AdvancedJunctionRule
@pcfantasy should add run-time check that user has subscribed and enabled TrafficManager

Btw this log seems to be from older version of this mod (before 10 Feb update)
Current version on Steam is ```TrafficManager, Version=1.0.6980.35728```

**Comment by pcfantasy** [comment]
@krzychu124 

OK, I will add this.

**Comment by aubergine10** [comment]
Oh,,,, Hang on, so the AdvancedJunctionRule mod _requires_ TMPE?

I thought it was incompatible.

@pcfantasy  can you confirm which is the case?

**Comment by aubergine10** [comment]
@pcfantasy Did you make that update to your mod yet (to check if TMPE is subscribed and enabled)?

**Comment by pcfantasy** [comment]
@aubergine10 
No, I will finish this soon when I have time :)

**Comment by pcfantasy** [comment]
I update my Github now to check oldTMPE and newTMPE, I will update to stream after a few test soon.
https://github.com/pcfantasy/AdvancedJunctionRule

        public void CheckTMPE()
         {
             if (IsSteamWorkshopItemSubscribed(583429740))
             {
                 UIView.library.ShowModal<ExceptionPanel>("ExceptionPanel").SetMessage("Incompatibility Issue", "Found original version of TM:PE steamID:583429740, We only support New version of TM:PE steamID:1637663252", true);
             }

              if (!this.Check3rdPartyModLoaded("TrafficManager", true))
             {
                 UIView.library.ShowModal<ExceptionPanel>("ExceptionPanel").SetMessage("Incompatibility Issue", "Require New version of TM:PE steamID:1637663252", true);
             }
         }

**Comment by aubergine10** [comment]
Looks like the mod was  updated with new code - @pcfantasy can this issue be closed?

**Comment by aubergine10** [comment]
no response, closing
