### ISSUE TITLE
Just me being stupid. Route diagnostic tool anyone?

### ISSUE THREAD

**Issue by aubergine10** [krzychu124/Cities-Skylines-Traffic-Manager-President-Edition#96]
A Steam user mentioned there was problems with highways, where vehicles were all using one lane.

I've been doing some testing and think I may have replicated the problem with a heinous highway junction like so:

![highway](https://user-images.githubusercontent.com/1386719/52906979-91b6eb00-324f-11e9-8f1d-1d089b854d8a.gif)

Yes, I know that's awful, but it's pretty much how the highway terminates in Liverpool, UK lol (ok, they have a huge freaking roundabout, but still...)

The rest of the city is my trademark huge square 4-lane road with enough zones an services to bring about 5k cims in.

After a few minutes running, this is the result - most of the traffic wants to use the middle lane of the highway, despite needing to turn left or right:

![hmmm](https://user-images.githubusercontent.com/1386719/52906991-e9eded00-324f-11e9-9921-3cacb96ae9c6.gif)

That looks dubious. Something to do with pathfinder?

They are certainly able to use the other lanes, but I suspect those lanes only have single connection to innermost and outermost (depending on direction) lane of the 4-lane avenue road. Forcing any other traffic in to the middle highway lane to get to the other lanes?

Once we get the display of default lane connections for lane arrows, this will be easier to debug. Currently I'm just guessing at what the lane connections are. (I've not any road customisations at this point).

The Steam user mentioned that turning off Advanced AI solved the problem, so I'm going to try that next and will report back.

**Comment by aubergine10** [comment]
Hrm, I had Advanced AI turned off due to yesterday's testing session.

Just turned it on, will see what happens....

**Comment by aubergine10** [comment]
DLS kicks in almost instantly, but obviously those vehicles still have old paths.

![dls](https://user-images.githubusercontent.com/1386719/52907030-e4dd6d80-3250-11e9-89d5-cc2704275e3d.gif)

Need to wait for newly spawned vehicles to arrive....

**Comment by krzychu124** [comment]
> Just turned it on, will see what happens....

It should help a lot 😉

**Comment by aubergine10** [comment]
Just realised what was happening.

Any that wanted building on inside of my square city ring road had to turn left at the junction, and taking middle highway lane was best option for them.

Being a ring road, there was nowhere for them to turn (until I added some extra roads and suddenly realised what was happening).

I imagine many users will struggle with problems like this, so maybe we need some sort of "investigative tool" for end-users to use?

Maybe a sort of "fake bus route" tool.... Click a lane on a segment to set start position, click another lane on another segment to set end position. A route is drawn showing how traffic is likely to flow between the two points. If we transition to using build bar (rather than floating toolbar) we could show icons for different vehicle types so user could see how the route might be different for them, I think this would help track down routing issues much more quickly - users could find where they've blundered lane connections, vehicle restrictions, etc. And if there's bugs in pathfinding logic, it will be easier to diagnose them.

**Comment by ntoff** [comment]
>Maybe a sort of "fake bus route" tool.... Click a lane on a segment to set start position, click another lane on another segment to set end position. A route is drawn showing how traffic is likely to flow between the two points.

It already exists in the base vanilla game, just click on a road and click the routes tool, you'll see the routes of people, service vehicles, trucks, etc.

**Comment by krzychu124** [comment]
I think that @aubergine10 wants to select two lanes on totally different segments to check if pathfinder can find a route between them with taking into account current traffic and to show where vehicles would drive.

BTW there is a little chance that in simulation pause mode we could create point to point path on demand. It should be theoretically possible

**Comment by FireController1847** [comment]
@krzychu124 The in-game tool does not work with the game paused either so I don't know requiring it to be playing makes that much of a difference.

**Comment by krzychu124** [comment]
I was thinking about creating new path finder thread to let user select two segments /lanes to find path between them inside isolated scope that's why I said that pause mode would be useful.

**Comment by aubergine10** [comment]
Or we could just copy and paste the bus route tool and feed it alternate vehicles. Like. "Hey, this donut van wants to be a bus today, show me how it gets from here to the police station, kthxbai".

**Comment by aubergine10** [comment]
Closing this, #341 sets out a better approach.
